# 1 - Imports

In [1]:
%reload_ext autoreload
%autoreload 2

In [2]:
import sys
from pathlib import Path

sys.path.append(str(Path().resolve().parents[0]))

In [3]:
import pandas as pd
import numpy as np

In [4]:
from src.utils import config, io, countries

/Users/hippolytegrandet/Desktop/Dev/country_risk_rating/.venv/lib/python3.9/site-packages/pypdf/_crypt_providers/_cryptography.py:32: CryptographyDeprecationWarning: ARC4 has been moved to cryptography.hazmat.decrepit.ciphers.algorithms.ARC4 and will be removed from cryptography.hazmat.primitives.ciphers.algorithms in 48.0.0.
  from cryptography.hazmat.primitives.ciphers.algorithms import AES, ARC4

# 1 - Build Catalogs

In [ ]:
from extraction import world_bank

/Users/hippolytegrandet/Desktop/Dev/country_risk_rating/.venv/lib/python3.9/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(

In [ ]:
client = world_bank.DBnomicsClient()

## 1.1 Dataset Catalog

In [ ]:
### dbnomics_lib_client.py

import pandas as pd
import dbnomics

def format_api_link(provider: str, dataset: str, indicator: str) -> str:
    """get api link for the indicator.

    Args:
        provider (string): name of the provider of the indicator.
        dataset (string): name of the dataset of the indicator.
        indicator (string): name of the indicator.

    Returns:
        string: formated api link, to get indicator df from dbnomics api.
    """

    link_p1 = 'https://api.db.nomics.world/v22/series/'
    link_p3 = '%22%5D%7D&observations=1'

    if provider == 'WB':
        link_p2 = '?dimensions=%7B%22indicator%22%3A%5B%22'
    elif provider == 'IMF':
        link_p2 = '?dimensions=%7B%22INDICATOR%22%3A%5B%22'
        # link_p3 = link_p3 + '&q=imf'
    else:
        return ''

    api_link = link_p1 + provider + '/' + dataset + link_p2 + indicator + link_p3
    return api_link

def fetch_indicator(provider: str, dataset: str, indicator: str) -> pd.DataFrame:
    """get unformated indicator df from dbnomics api.
    Args:
        provider (string): name of the provider of the indicator.
        dataset (string): name of the dataset of the indicator.
        indicator (string): name of the indicator.
    Returns:
        DataFrame: indicator df from dbnomics api.
    """

    api_link = format_api_link(provider, dataset, indicator)
    try:
        df_indicator = dbnomics.fetch_series_by_api_link(
            api_link,
            max_nb_series=600
        )
    except Exception:
        print('Error Fetching Series for indicator', indicator)
        df_indicator = pd.DataFrame()

    return df_indicator

### 1.1.1 - Build Provider Datasets Catalog (Discontinued, Now Hand Picked List)

In [270]:
from src.metadata import build_provider_dataset_catalog

In [282]:
providers = [
    'IMF', 'WB', 'OECD', 'BIS', 'UNCTAD', 'FAO', 'ILO', 'FH'
]

In [283]:
datasets_df = build_provider_dataset_catalog.get_all_datasets_df(client, providers)
datasets_df

,index,Provider Id,Provider Name,Provider Region,Dataset Id,Dataset Name,Subgroup 1 Id,Subgroup 1 Name,Subgroup 2 Id,Subgroup 2 Name
0,0,IMF,International Monetary Fund,World,AFRREO,Sub-Saharan Africa Regional Economic Outlook (...,NaN,NaN,NaN,NaN
1,1,IMF,International Monetary Fund,World,APDREO,Asia and Pacific Regional Economic Outlook (AP...,NaN,NaN,NaN,NaN
2,2,IMF,International Monetary Fund,World,BOP,Balance of Payments (BOP),NaN,NaN,NaN,NaN
3,3,IMF,International Monetary Fund,World,BOPAGG,"Balance of Payments (BOP), World and Regional ...",NaN,NaN,NaN,NaN
4,4,IMF,International Monetary Fund,World,CDIS,Coordinated Direct Investment Survey (CDIS),NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
2106,2562,ILO,International Labour Organization,World,WBL_TWBL_SEX_EDU_WBL_NB,"Work-based learners by sex, education and type...",WBL,Work-based learning,NaN,NaN
2107,2563,ILO,International Labour Organization,World,WBL_XVET_SEX_EDU_NB,Working-age population with vocational educati...,WBL,Work-based learning,NaN,NaN
2108,2564,ILO,International Labour Organization,World,WBL_3WBL_SEX_WBL_RT,Youth participation rate in work-based learnin...,WBL,Work-based learning,NaN,NaN
2109,2565,FH,Freedom House,World,FIW,"All data, Freedom in the world since 2013",NaN,NaN,NaN,NaN
2110,2566,FH,Freedom House,World,CTRS,Country and Territory Ratings and Statuses,NaN,NaN,NaN,NaN

In [284]:
datasets_df['Provider Id'].value_counts()

Provider Id
ILO       1071
OECD       758
IMF        106
FAO         85
UNCTAD      62
WB          14
BIS         13
FH           2
Name: count, dtype: int64

In [285]:
build_provider_dataset_catalog.TOTAL_AVOIDED

4550

In [ ]:
# io.save_csv(datasets_df, config.METADATA_DIR / 'provider_datasets.csv')

### 1.1.2 Prune Provider Datasets

In [7]:
datasets_df = io.load_csv(config.METADATA_DIR / 'provider_datasets_selected.csv', index_col=0)
datasets_df

,Provider Id,Provider Name,Provider Region,Dataset Id,Dataset Name,Subgroup 1 Id,Subgroup 1 Name,Subgroup 2 Id,Subgroup 2 Name,Country Param Name,Country Param Format,Frequency Param Name,Frequency Annual,Other Param Name
0,IMF,International Monetary Fund,World,BOP,Balance of Payments (BOP),NaN,NaN,NaN,NaN,REF_AREA,ISO2,FREQ,A,INDICATOR
2,IMF,International Monetary Fund,World,CPI,Consumer Price Index (CPI),NaN,NaN,NaN,NaN,REF_AREA,ISO2,FREQ,A,INDICATOR
3,IMF,International Monetary Fund,World,FDI,Financial Development Index,NaN,NaN,NaN,NaN,REF_AREA,ISO2,FREQ,A,INDICATOR
4,IMF,International Monetary Fund,World,FM,Fiscal Monitor (FM),NaN,NaN,NaN,NaN,REF_AREA,ISO2,FREQ,A,INDICATOR
5,IMF,International Monetary Fund,World,FSI,Financial Soundness Indicators (FSIs),NaN,NaN,NaN,NaN,REF_AREA,ISO2,FREQ,A,INDICATOR
6,IMF,International Monetary Fund,World,GENDER_EQUALITY,Gender Equality,NaN,NaN,NaN,NaN,REF_AREA,ISO2,FREQ,A,INDICATOR
7,IMF,International Monetary Fund,World,GFSMAB,"Government Finance Statistics (GFS), Main Aggr...",NaN,NaN,NaN,NaN,REF_AREA,ISO2,FREQ,A,CLASSIFICATION/REF_SECTOR/UNIT_MEASURE
8,IMF,International Monetary Fund,World,HPDD,Historical Public Debt (HPDD),NaN,NaN,NaN,NaN,REF_AREA,ISO2,FREQ,A,INDICATOR
9,IMF,International Monetary Fund,World,IFS,International Financial Statistics (IFS),NaN,NaN,NaN,NaN,REF_AREA,ISO2,FREQ,A,INDICATOR
10,IMF,International Monetary Fund,World,IRFCL,International Reserves and Foreign Currency Li...,NaN,NaN,NaN,NaN,REF_AREA,ISO2,FREQ,A,INDICATOR/REF_SECTOR
11,IMF,International Monetary Fund,World,MFS,Monetary and Financial Statistics (MFS),NaN,NaN,NaN,NaN,REF_AREA,ISO2,FREQ,A,INDICATOR
13,IMF,International Monetary Fund,World,PGCS,Private and Public Capital Stock Dataset,NaN,NaN,NaN,NaN,REF_AREA,NAME,FREQ,A,INDICATOR
15,IMF,International Monetary Fund,World,PSBSFAD,Public Sector Balance Sheet (PSBS)(FAD),NaN,NaN,NaN,NaN,REF_AREA,NAME,FREQ,A,INDICATOR
16,IMF,International Monetary Fund,World,WoRLD,World Revenue Longitudinal Data (WoRLD),NaN,NaN,NaN,NaN,REF_AREA,ISO2,FREQ,A,INDICATOR
17,WB,World Bank,World,DBS,Doing Business,NaN,NaN,NaN,NaN,country,ISO3,frequency,A,indicator
18,WB,World Bank,World,ESY,Enterprise Surveys,NaN,NaN,NaN,NaN,country,ISO3,frequency,A,indicator
19,WB,World Bank,World,FDX,Global Financial Inclusion,NaN,NaN,NaN,NaN,country,ISO3,frequency,A,indicator
20,WB,World Bank,World,GEM,Global Economic Monitor,NaN,NaN,NaN,NaN,country,ISO3,frequency,A,indicator
21,WB,World Bank,World,GEP,Global Economic Prospects,NaN,NaN,NaN,NaN,country,ISO3,frequency,A,indicator
24,WB,World Bank,World,JOB,Jobs,NaN,NaN,NaN,NaN,country,ISO3,frequency,A,indicator
25,WB,World Bank,World,WDI,World Development Indicators,NaN,NaN,NaN,NaN,country,ISO3,frequency,A,indicator
26,WB,World Bank,World,WGI,Worldwide Governance Indicators,NaN,NaN,NaN,NaN,country,ISO3,frequency,A,indicator
27,BIS,Bank for International Settlements,World,WS_GLI,Global liquidity indicators,BISWEB_CATSCHEME,BISWEB_CATSCHEME,WEBSTATS_GLI,Global liquidity,BORROWERS_CTY,ISO2,FREQ,A,BORROWERS_SECTOR/CURR_DENOM/LENDERS_SECTOR/L_I...
29,BIS,Bank for International Settlements,World,WS_CREDIT_GAP,BIS credit-to-GDP gaps,BISWEB_CATSCHEME,BISWEB_CATSCHEME,WEBSTATS_CREDGAP,Credit gaps,BORROWERS_CTY,ISO2,FREQ,A,CG_DTYPE/TC_BORROWERS/TC_LENDERS
32,UNCTAD,United Nation Conference on Trade and Development,World,MTTASA,"Merchandise: Total trade and share, annual",NaN,International merchandise trade,NaN,Trade value and volume,economy,NAME,frequency,A,flow/measure
33,UNCTAD,United Nation Conference on Trade and Development,World,MTBA,"Merchandise: Trade balance, annual",NaN,International merchandise trade,NaN,Trade value and volume,economy,NAME,frequency,A,measure
34,UNCTAD,United Nation Conference on Trade and Development,World,MTTGRA,"Merchandise: Total trade growth rates, annual",NaN,International merchandise trade,NaN,Trade value and volume,economy,NAME,frequency,A,flow/measure
35,UNCTAD,United Nation Conference on Trade and Development,World,MPCADIOEAIA,Merchandise: Product concentration and diversi...,NaN,International merchandise trade,NaN,Trade indicators,economy,NAME,frequency,A,flow/measure
36,UNCTAD,United Nation Conference on Trade and Development,World,GASBTBIA,Goods and services (BPM6): Trade balance indic...,NaN,Balance of payments,NaN,NaN,economy,NAME,frequency,A,flow/measure/series
37,UNCTAD,United Nation Conference on Trade and Development,World,GASBTOIA,Goods and services (BPM6): Trade openness indi...,NaN,Balance of payments,NaN,NaN,economy,NAME,frequency,A,flow/measure/series
38,UNCTAD,United Nation Conference on Trade and Development,World,FDIIAOFASA,Foreign direct investment: Inward and outward ...,NaN,Balance of payments,NaN,NaN,economy,NAME,frequency,A,direction/measure/mode
39,UNCTAD,United Nation Conference on Trade and Development,World,GDPTAPCCAC2PA,"Gross domestic product: Total and per capita, ...",NaN,Output and income,NaN,NaN,economy,NAME,frequency,A,measure
40,UNCTAD,United Nation Conference on Trade and Development,World,RGDPTAPCGRA,Real gross domestic product: Total and per cap...,NaN,Output and income,NaN,NaN,economy,NAME,frequency,A,measure
41,UNCTAD,United Nation Conference on Trade and Development,World,NGTAPCA,"Nominal GNI, total and per capita, annual",NaN,Output and income,NaN,NaN,economy,NAME,frequency,A,measure
43,UNCTAD,United Nation Conference on Trade and Development,World,TAUPA,"Total and urban population, annual",NaN,Population,NaN,NaN,economy,NAME,frequency,A,measure
44,UNCTAD,United Nation Conference on Trade and Development,World,TPGRA,"Total population growth rates, annual",NaN,Population,NaN,NaN,economy,NAME,frequency,A,measure
46,ILO,International Labour Organization,World,EAR_GGAP_OCU_RT,Gender wage gap by occupation (%),EAR,Earnings,NaN,NaN,ref_area,ISO3,frequency,A,classif1/source
47,ILO,International Labour Organization,World,SDG_1041_NOC_RT,SDG indicator 10.4.1 - Labour income share as ...,EAR,Earnings,NaN,NaN,ref_area,ISO3,frequency,A,source
48,ILO,International Labour Organization,World,EES_TEES_ECO_OCU_NB,Employees by economic activity and occupation ...,EMP,Employment,NaN,NaN,ref_area,ISO3,frequency,A,classif1/classif2/source
49,ILO,International Labour Organization,World,PSE_TPSE_GOV_NB,Public employment by sectors and sub-sectors o...,EMP,Employment,NaN,NaN,ref_area,ISO3,frequency,A,classif1/source
52,ILO,International Labour Organization,World,GDP_205U_NOC_NB,Output per worker (GDP constant 2015 US $) -- ...,LPY,Labour productivity,NaN,NaN,ref_area,ISO3,frequency,A,source
53,ILO,International Labour Organization,World,SDG_B821_NOC_RT,SDG indicator 8.2.1 - Annual growth rate of ou...,LPY,Labour productivity,NaN,NaN,ref_area,ISO3,frequency,A,source
54,ILO,International Labour Organization,World,INJ_FATL_ECO_NB,Cases of fatal occupational injury by economic...,INJ,Occupational injuries,NaN,NaN,ref_area,ISO3,frequency,A,classif1/source

In [30]:
providers = datasets_df['Provider Id'].unique()

dataset_params = {}
for i, dataset_row in datasets_df.iterrows():
    provider_id = dataset_row['Provider Id']
    dataset_id = dataset_row['Dataset Id']
    print('Provider:', provider_id, 'Dataset:', dataset_id)

    if provider_id not in dataset_params.keys():
        dataset_params[provider_id] = {dataset_id: {}}
    else:
        dataset_params[provider_id][dataset_id] = {}

    try:
        dataset_dict = client.list_series(provider_id, dataset_id, limit=1)
        dataset_dim_dict = dataset_dict['dataset']['dimensions_values_labels']
        dataset_dim_dict.pop(dataset_row['Country Param Name'])
        dataset_dim_dict.pop(dataset_row['Frequency Param Name'])

        dataset_params[provider_id][dataset_id] = dataset_dim_dict

    except SyntaxError:
            print('Error querying dataset:', provider_id, dataset_id)

Provider: IMF Dataset: BOP
Provider: IMF Dataset: CPI
Provider: IMF Dataset: FDI
Provider: IMF Dataset: FM
Provider: IMF Dataset: FSI
Provider: IMF Dataset: GENDER_EQUALITY
Provider: IMF Dataset: GFSMAB
Provider: IMF Dataset: HPDD
Provider: IMF Dataset: IFS
Provider: IMF Dataset: IRFCL
Provider: IMF Dataset: MFS
Provider: IMF Dataset: PGCS
Provider: IMF Dataset: PSBSFAD
Provider: IMF Dataset: WoRLD
Provider: WB Dataset: DBS
Provider: WB Dataset: ESY
Provider: WB Dataset: FDX
Provider: WB Dataset: GEM
Provider: WB Dataset: GEP
Provider: WB Dataset: JOB
Provider: WB Dataset: WDI
Provider: WB Dataset: WGI
Provider: BIS Dataset: WS_GLI
Provider: BIS Dataset: WS_CREDIT_GAP
Provider: UNCTAD Dataset: MTTASA
Provider: UNCTAD Dataset: MTBA
Provider: UNCTAD Dataset: MTTGRA
Provider: UNCTAD Dataset: MPCADIOEAIA
Provider: UNCTAD Dataset: GASBTBIA
Provider: UNCTAD Dataset: GASBTOIA
Provider: UNCTAD Dataset: FDIIAOFASA
Provider: UNCTAD Dataset: GDPTAPCCAC2PA
Provider: UNCTAD Dataset: RGDPTAPCGRA
Provider: UNCTAD Dataset: NGTAPCA
Provider: UNCTAD Dataset: TAUPA
Provider: UNCTAD Dataset: TPGRA
Provider: ILO Dataset: EAR_GGAP_OCU_RT
Provider: ILO Dataset: SDG_1041_NOC_RT
Provider: ILO Dataset: EES_TEES_ECO_OCU_NB
Provider: ILO Dataset: PSE_TPSE_GOV_NB
Provider: ILO Dataset: GDP_205U_NOC_NB
Provider: ILO Dataset: SDG_B821_NOC_RT
Provider: ILO Dataset: INJ_FATL_ECO_NB

In [31]:
new_d = {}
for provider_id, provider_d in dataset_params.items():
    new_d[provider_id] = {}
    for dataset_id, dataset_d in provider_d.items():
        new_d[provider_id][dataset_id] = {}
        for param, param_d in dataset_d.items():
            new_d[provider_id][dataset_id][param] = {}

            new_param_d = {}
            for k, v in param_d.items():
                if (k[-4:] == '_EUR' or k[-4:] == '_XDC') and (k[:-4] + '_USD') in param_d.keys():
                    pass
                else:
                    new_param_d[k] = v

            new_d[provider_id][dataset_id][param] = new_param_d

In [32]:
new_d

{'IMF': {'BOP': {'INDICATOR': {'BACK_BP6_USD': 'Net Lending (+) / Net Borrowing (-) (Balance from Current and Capital Account), US Dollars',
    'BAXEF_BP6_USD': 'Supplementary Items, Arrears not in Exceptional Financing, US Dollars',
    'BCAXF_BP6_USD': 'Supplementary Items, Current Account, Net (Excluding Exceptional Financing), US Dollars',
    'BCA_BP6_SPE_USD': 'Current Account, Total, Net, Special Purpose Entities, US Dollar',
    'BCA_BP6_USD': 'Current Account, Total, Net, US Dollars',
    'BEFDDAAI_BP6_USD': 'Exceptional Financing, Direct Investment, Debt Instruments, Accumulations of Arrears, Original Interest/Coupon, US Dollars',
    'BEFDDAAPI_BP6_USD': 'Exceptional Financing, Direct Investment, Debt Instruments, Accumulations of Arrears, Penalty Interest, US Dollars',
    'BEFDDAAP_BP6_USD': 'Exceptional Financing, Direct Investment, Debt Instruments, Accumulations of Arrears, Principal, US Dollars',
    'BEFDDAA_BP6_USD': 'Exceptional Financing, Direct Investment, Debt Instruments, Accumulations of Arrears, US Dollars',
    'BEFDDCAI_BP6_USD': 'Exceptional Financing, Direct Investment, Debt Instruments, Cancellation of Arrears, Interest/Coupon, US Dollars',
    'BEFDDCAP_BP6_USD': 'Exceptional Financing, Direct Investment, Debt Instruments, Cancellation of Arrears, Principal, US Dollars',
    'BEFDDCA_BP6_USD': 'Exceptional Financing, Direct Investment, Debt Instruments, Cancellation of Arrears, US Dollars',
    'BEFDDRAI_BP6_USD': 'Exceptional Financing, Direct Investment, Debt Instruments, Repayment of Arrears, Interest/Coupon, US Dollars',
    'BEFDDRAP_BP6_USD': 'Exceptional Financing, Direct Investment, Debt Instruments, Repayment of Arrears, Principal, US Dollars',
    'BEFDDRA_BP6_USD': 'Exceptional Financing, Direct Investment, Debt Instruments, Repayment of Arrears, US Dollars',
    'BEFDDRPI_BP6_USD': 'Exceptional Financing, Direct Investment, Debt Instruments, Rescheduling of Payments Due in Current Reporting Period, Interest/Coupon, US Dollars',
    'BEFDDRPP_BP6_USD': 'Exceptional Financing, Direct Investment, Debt Instruments, Rescheduling of Payments Due in Current Reporting Period, Principal, US Dollars',
    'BEFDDRP_BP6_USD': 'Exceptional Financing, Direct Investment, Debt Instruments, Rescheduling of Payments Due in Current Reporting Period, US Dollars',
    'BEFDDSAI_BP6_USD': 'Exceptional Financing, Direct Investment, Debt Instruments, Rescheduling of Arrears, Interest/Coupon, US Dollars',
    'BEFDDSAP_BP6_USD': 'Exceptional Financing, Direct Investment, Debt Instruments, Rescheduling of Arrears, Principal, US Dollars',
    'BEFDDSA_BP6_USD': 'Exceptional Financing, Direct Investment, Debt Instruments, Rescheduling of Arrears, US Dollars',
    'BEFDD_BP6_USD': 'Exceptional Financing, Direct Investment, Debt Instruments, US Dollars',
    'BEFDE_BP6_USD': 'Exceptional Financing, Direct Investment, Equity Investment Associated with Debt Reduction, US Dollars',
    'BEFD_BP6_USD': 'Exceptional Financing, Direct Investment, US Dollars',
    'BEFISGIMF_BP6_USD': 'Exceptional Financing, Secondary Income, Grants Received from IMF Subsidy Accounts, US Dollars',
    'BEFISIG_BP6_USD': 'Exceptional Financing, Secondary Income, Other Intergovernmental grants, US Dollars',
    'BEFIS_BP6_USD': 'Exceptional Financing, Secondary Income, US Dollars',
    'BEFOE_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Equity Investment Associated with Debt Reduction, US Dollars',
    'BEFOODCBAAI_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Central Bank, Accumulation of Arrears, Original Interest, US Dollars',
    'BEFOODCBAAPI_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Central Bank, Accumulation of Arrears, Penalty Interest, US Dollars',
    'BEFOODCBAAP_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Central Bank, Accumulation of Arrears, Principal, US Dollars',
    'BEFOODCBAA_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Central Bank, Accumulation of Arrears, US Dollars',
    'BEFOODCBCAI_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Central Bank, Cancellation of Arrears, Interest, US Dollars',
    'BEFOODCBCAP_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Central Bank, Cancellation of Arrears, Principal, US Dollars',
    'BEFOODCBCA_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Central Bank, Cancellation of Arrears, US Dollars',
    'BEFOODCBND_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Central Bank, New Drawings/Deposits, US Dollars',
    'BEFOODCBPP_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Central Bank, Prepayment, US Dollars',
    'BEFOODCBRAI_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Central Bank, Repayment of Arrears, Interest, US Dollars',
    'BEFOODCBRAP_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Central Bank, Repayment of Arrears, Principal, US Dollars',
    'BEFOODCBRA_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Central Bank, Repayment of Arrears, US Dollars',
    'BEFOODCBRPI_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Central Bank, Rescheduling of Payments Due in Current Reporting Period, Interest, US Dollars',
    'BEFOODCBRPP_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Central Bank, Rescheduling of Payments Due in Current Reporting Period, Principal, US Dollars',
    'BEFOODCBRP_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Central Bank, Rescheduling of Payments Due in Current Reporting Period, US Dollars',
    'BEFOODCBSAI_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Central Bank, Rescheduling of Arrears, Interest, US Dollars',
    'BEFOODCBSAP_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Central Bank, Rescheduling of Arrears, Principal, US Dollars',
    'BEFOODCBSA_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Central Bank, Rescheduling of Arrears, US Dollars',
    'BEFOODCB_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Central Bank, US Dollars',
    'BEFOODDCAAI_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Deposit-taking Corporations, Except Central Bank, Accumulation of Arrears, Original Interest, US Dollars',
    'BEFOODDCAAPI_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Deposit-taking Corporations, Except Central Bank, Accumulation of Arrears, Penalty Interest, US Dollars',
    'BEFOODDCAAP_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Deposit-taking Corporations, Except Central Bank, Accumulation of Arrears, Principal, US Dollars',
    'BEFOODDCAA_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Deposit-taking Corporations, Except Central Bank, Accumulation of Arrears, US Dollars',
    'BEFOODDCCAI_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Deposit-taking Corporations, Except Central Bank, Cancellation of Arrears, Interest, US Dollars',
    'BEFOODDCCAP_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Deposit-taking Corporations, Except Central Bank, Cancellation of Arrears, Principal, US Dollars',
    'BEFOODDCCA_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Deposit-taking Corporations, Except Central Bank, Cancellation of Arrears, US Dollars',
    'BEFOODDCND_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Deposit-taking Corporations, Except Central Bank, New Drawings/Deposits on Behalf of Authorities, US Dollars',
    'BEFOODDCPP_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Deposit-taking Corporations, Except Central Bank, Prepayment, US Dollars',
    'BEFOODDCRAI_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Deposit-taking Corporations, Except Central Bank, Repayment of Arrears, Interest, US Dollars',
    'BEFOODDCRAP_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Deposit-taking Corporations, Except Central Bank, Repayment of Arrears, Principal, US Dollars',
    'BEFOODDCRA_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Deposit-taking Corporations, Except Central Bank, Repayment of Arrears, US Dollars',
    'BEFOODDCRPI_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Deposit-taking Corporations, Except Central Bank, Rescheduling of Payments Due in Current Reporting Period, Interest, US Dollars',
    'BEFOODDCRPP_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Deposit-taking Corporations, Except Central Bank, Rescheduling of Payments Due in Current Reporting Period, Principal, US Dollars',
    'BEFOODDCRP_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Deposit-taking Corporations, Except Central Bank, Rescheduling of Payments Due in Current Reporting Period, US Dollars',
    'BEFOODDCSAI_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Deposit-taking Corporations, Except Central Bank, Rescheduling of Arrears, Interest, US Dollars',
    'BEFOODDCSAP_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Deposit-taking Corporations, Except Central Bank, Rescheduling of Arrears, Principal, US Dollars',
    'BEFOODDCSA_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Deposit-taking Corporations, Except Central Bank, Rescheduling of Arrears, US Dollars',
    'BEFOODDC_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Deposit-taking Corporations, Except Central Bank, US Dollars',
    'BEFOODGAAI_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, General Government, Accumulation of Arrears, Original Interest, US Dollars',
    'BEFOODGAAPI_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, General Government, Accumulation of Arrears, Penalty Interest, US Dollars',
    'BEFOODGAAP_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, General Government, Accumulation of Arrears, Principal, US Dollars',
    'BEFOODGAA_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, General Government, Accumulation of Arrears, US Dollars',
    'BEFOODGCAI_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, General Government, Cancellation of Arrears, Interest, US Dollars',
    'BEFOODGCAP_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, General Government, Cancellation of Arrears, Principal, US Dollars',
    'BEFOODGCA_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, General Government, Cancellation of Arrears, US Dollars',
    'BEFOODGND_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, General Government, New Drawings/Deposits, US Dollars',
    'BEFOODGPP_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, General Government, Prepayment, US Dollars',
    'BEFOODGRAI_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, General Government, Repayment of Arrears, Interest, US Dollars',
    'BEFOODGRAP_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, General Government, Repayment of Arrears, Principal, US Dollars',
    'BEFOODGRA_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, General Government, Repayment of Arrears, US Dollars',
    'BEFOODGRPI_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, General Government, Rescheduling of Payments Due in Current Reporting Period, Interest, US Dollars',
    'BEFOODGRPP_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, General Government, Rescheduling of Payments Due in Current Reporting Period, Principal, US Dollars',
    'BEFOODGRP_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, General Government, Rescheduling of Payments Due in Current Reporting Period, US Dollars',
    'BEFOODGSAI_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, General Government, Rescheduling of Arrears, Interest, US Dollars',
    'BEFOODGSAP_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, General Government, Rescheduling of Arrears, Principal, US Dollars',
    'BEFOODGSA_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, General Government, Rescheduling of Arrears, US Dollars',
    'BEFOODG_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, General Government, US Dollars',
    'BEFOODOAAI_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Other Sectors, Accumulation of Arrears, Original Interest, US Dollars',
    'BEFOODOAAPI_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Other Sectors, Accumulation of Arrears, Penalty Interest, US Dollars',
    'BEFOODOAAP_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Other Sectors, Accumulation of Arrears, Principal, US Dollars',
    'BEFOODOAA_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Other Sectors, Accumulation of Arrears, US Dollars',
    'BEFOODOCAI_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Other Sectors, Cancellation of Arrears, Interest, US Dollars',
    'BEFOODOCAP_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Other Sectors, Cancellation of Arrears, Principal, US Dollars',
    'BEFOODOCA_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Other Sectors, Cancellation of Arrears, US Dollars',
    'BEFOODOFAAI_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Other Financial Corporations, Accumulation of Arrears, Original Interest, US Dollars',
    'BEFOODOFAAPI_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Other Financial Corporations, Accumulation of Arrears, Penalty Interest, US Dollars',
    'BEFOODOFAAP_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Other Financial Corporations, Accumulation of Arrears, Principal, US Dollars',
    'BEFOODOFAA_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Other Financial Corporations, Accumulation of Arrears, US Dollars',
    'BEFOODOFCAI_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Other Financial Corporations, Cancellation of Arrears, Interest, US Dollars',
    'BEFOODOFCAP_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Other Financial Corporations, Cancellation of Arrears, Principal, US Dollars',
    'BEFOODOFCA_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Other Financial Corporations, Cancellation of Arrears, US Dollars',
    'BEFOODOFND_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Other Financial Corporations, New Drawings/Deposits on Behalf of Authorities, US Dollars',
    'BEFOODOFPP_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Other Financial Corporations, Prepayment, US Dollars',
    'BEFOODOFRAI_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Other Financial Corporations, Repayment of Arrears, Interest, US Dollars',
    'BEFOODOFRAP_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Other Financial Corporations, Repayment of Arrears, Principal, US Dollars',
    'BEFOODOFRA_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Other Financial Corporations, Repayment of Arrears, US Dollars',
    'BEFOODOFRPI_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Other Financial Corporations, Rescheduling of Payments Due in Current Reporting Period, Interest, US Dollars',
    'BEFOODOFRPP_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Other Financial Corporations, Rescheduling of Payments Due in Current Reporting Period, Principal, US Dollars',
    'BEFOODOFRP_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Other Financial Corporations, Rescheduling of Payments Due in Current Reporting Period, US Dollars',
    'BEFOODOFSAI_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Other Financial Corporations, Rescheduling of Arrears, Interest, US Dollars',
    'BEFOODOFSAP_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Other Financial Corporations, Rescheduling of Arrears, Principal, US Dollars',
    'BEFOODOFSA_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Other Financial Corporations, Rescheduling of Arrears, US Dollars',
    'BEFOODOF_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Other Financial Corporations, US Dollars',
    'BEFOODOND_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Other Sectors, New Drawings/Deposits on Behalf of Authorities, US Dollars',
    'BEFOODONFAAI_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Nonfinancial Corporations, Households, NPISHs, Accumulation of Arrears, Original Interest, US Dollars',
    'BEFOODONFAAPI_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Nonfinancial Corporations, Households, NPISHs, Accumulation of Arrears, Penalty Interest, US Dollars',
    'BEFOODONFAAP_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Nonfinancial Corporations, Households, NPISHs, Accumulation of Arrears, Principal, US Dollars',
    'BEFOODONFAA_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Nonfinancial Corporations, Households, NPISHs, Accumulation of Arrears, US Dollars',
    'BEFOODONFCAI_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Nonfinancial Corporations, Households, NPISHs, Cancellation of Arrears, Interest, US Dollars',
    'BEFOODONFCAP_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Nonfinancial Corporations, Households, NPISHs, Cancellation of Arrears, Principal, US Dollars',

In [34]:
import json

json_str = json.dumps(new_d, indent=4)
with open(config.METADATA_DIR / 'datasets_dimensions.json', 'w') as f:
    f.write(json_str)

In [37]:
count_dataset_d = {}
count_d = {}
for provider_id, provider_d in new_d.items():
    count_d[provider_id] = {}
    count_dataset_d[provider_id] = {}
    for dataset_id, dataset_d in provider_d.items():
        count_d[provider_id][dataset_id] = {}
        count_dataset_d[provider_id][dataset_id] = {}
        v = 1
        for param, param_d in dataset_d.items():
            v = v * len(new_d[provider_id][dataset_id][param])
        
        count_dataset_d[provider_id][dataset_id] = v

In [36]:
count_d

{'IMF': {'BOP': {'INDICATOR': 2218},
  'CPI': {'INDICATOR': 178},
  'FDI': {'INDICATOR': 9},
  'FM': {'INDICATOR': 9},
  'FSI': {'INDICATOR': 959},
  'GENDER_EQUALITY': {'INDICATOR': 3},
  'GFSMAB': {'CLASSIFICATION': 35, 'REF_SECTOR': 8, 'UNIT_MEASURE': 2},
  'HPDD': {'INDICATOR': 1},
  'IFS': {'INDICATOR': 1301},
  'IRFCL': {'INDICATOR': 295, 'REF_SECTOR': 5},
  'MFS': {'INDICATOR': 575},
  'PGCS': {'INDICATOR': 15},
  'PSBSFAD': {'INDICATOR': 1235},
  'WoRLD': {'INDICATOR': 15}},
 'WB': {'DBS': {'indicator': 194},
  'ESY': {'indicator': 115},
  'FDX': {'indicator': 1226},
  'GEM': {'indicator': 36},
  'GEP': {'indicator': 1},
  'JOB': {'indicator': 166},
  'WDI': {'indicator': 1492},
  'WGI': {'indicator': 36}},
 'BIS': {'WS_GLI': {'BORROWERS_SECTOR': 20,
   'CURR_DENOM': 324,
   'LENDERS_SECTOR': 20,
   'L_INSTR': 23,
   'L_POS_TYPE': 8,
   'UNIT_MEASURE': 1088},
  'WS_CREDIT_GAP': {'CG_DTYPE': 3, 'TC_BORROWERS': 5, 'TC_LENDERS': 20}},
 'UNCTAD': {'MTTASA': {'flow': 2, 'measure': 2},
  'MTBA': {'measure': 2},
  'MTTGRA': {'flow': 2, 'measure': 1},
  'MPCADIOEAIA': {'flow': 2, 'measure': 3},
  'GASBTBIA': {'flow': 1, 'measure': 4, 'series': 2},
  'GASBTOIA': {'flow': 4, 'measure': 2, 'series': 2},
  'FDIIAOFASA': {'direction': 2, 'measure': 5, 'mode': 2},
  'GDPTAPCCAC2PA': {'measure': 4},
  'RGDPTAPCGRA': {'measure': 2},
  'NGTAPCA': {'measure': 2},
  'TAUPA': {'measure': 2},
  'TPGRA': {'measure': 1}},
 'ILO': {'EAR_GGAP_OCU_RT': {'classif1': 29, 'source': 150},
  'SDG_1041_NOC_RT': {'source': 199},
  'EES_TEES_ECO_OCU_NB': {'classif1': 56, 'classif2': 29, 'source': 238},
  'PSE_TPSE_GOV_NB': {'classif1': 10, 'source': 204},
  'GDP_205U_NOC_NB': {'source': 274},
  'SDG_B821_NOC_RT': {'source': 199},
  'INJ_FATL_ECO_NB': {'classif1': 61, 'source': 205}}}

In [38]:
count_dataset_d

{'IMF': {'BOP': 2218,
  'CPI': 178,
  'FDI': 9,
  'FM': 9,
  'FSI': 959,
  'GENDER_EQUALITY': 3,
  'GFSMAB': 560,
  'HPDD': 1,
  'IFS': 1301,
  'IRFCL': 1475,
  'MFS': 575,
  'PGCS': 15,
  'PSBSFAD': 1235,
  'WoRLD': 15},
 'WB': {'DBS': 194,
  'ESY': 115,
  'FDX': 1226,
  'GEM': 36,
  'GEP': 1,
  'JOB': 166,
  'WDI': 1492,
  'WGI': 36},
 'BIS': {'WS_GLI': 25944883200, 'WS_CREDIT_GAP': 300},
 'UNCTAD': {'MTTASA': 4,
  'MTBA': 2,
  'MTTGRA': 2,
  'MPCADIOEAIA': 6,
  'GASBTBIA': 8,
  'GASBTOIA': 16,
  'FDIIAOFASA': 20,
  'GDPTAPCCAC2PA': 4,
  'RGDPTAPCGRA': 2,
  'NGTAPCA': 2,
  'TAUPA': 2,
  'TPGRA': 1},
 'ILO': {'EAR_GGAP_OCU_RT': 4350,
  'SDG_1041_NOC_RT': 199,
  'EES_TEES_ECO_OCU_NB': 386512,
  'PSE_TPSE_GOV_NB': 2040,
  'GDP_205U_NOC_NB': 274,
  'SDG_B821_NOC_RT': 199,
  'INJ_FATL_ECO_NB': 12505}}

In [48]:
with open(config.METADATA_DIR / 'datasets_dimensions.json', 'r') as f:
    d = json.load(f)

print(d)

{'IMF': {'BOP': {'INDICATOR': {'BACK_BP6_USD': 'Net Lending (+) / Net Borrowing (-) (Balance from Current and Capital Account), US Dollars', 'BAXEF_BP6_USD': 'Supplementary Items, Arrears not in Exceptional Financing, US Dollars', 'BCAXF_BP6_USD': 'Supplementary Items, Current Account, Net (Excluding Exceptional Financing), US Dollars', 'BCA_BP6_SPE_USD': 'Current Account, Total, Net, Special Purpose Entities, US Dollar', 'BCA_BP6_USD': 'Current Account, Total, Net, US Dollars', 'BEFDDAAI_BP6_USD': 'Exceptional Financing, Direct Investment, Debt Instruments, Accumulations of Arrears, Original Interest/Coupon, US Dollars', 'BEFDDAAPI_BP6_USD': 'Exceptional Financing, Direct Investment, Debt Instruments, Accumulations of Arrears, Penalty Interest, US Dollars', 'BEFDDAAP_BP6_USD': 'Exceptional Financing, Direct Investment, Debt Instruments, Accumulations of Arrears, Principal, US Dollars', 'BEFDDAA_BP6_USD': 'Exceptional Financing, Direct Investment, Debt Instruments, Accumulations of Arrears, US Dollars', 'BEFDDCAI_BP6_USD': 'Exceptional Financing, Direct Investment, Debt Instruments, Cancellation of Arrears, Interest/Coupon, US Dollars', 'BEFDDCAP_BP6_USD': 'Exceptional Financing, Direct Investment, Debt Instruments, Cancellation of Arrears, Principal, US Dollars', 'BEFDDCA_BP6_USD': 'Exceptional Financing, Direct Investment, Debt Instruments, Cancellation of Arrears, US Dollars', 'BEFDDRAI_BP6_USD': 'Exceptional Financing, Direct Investment, Debt Instruments, Repayment of Arrears, Interest/Coupon, US Dollars', 'BEFDDRAP_BP6_USD': 'Exceptional Financing, Direct Investment, Debt Instruments, Repayment of Arrears, Principal, US Dollars', 'BEFDDRA_BP6_USD': 'Exceptional Financing, Direct Investment, Debt Instruments, Repayment of Arrears, US Dollars', 'BEFDDRPI_BP6_USD': 'Exceptional Financing, Direct Investment, Debt Instruments, Rescheduling of Payments Due in Current Reporting Period, Interest/Coupon, US Dollars', 'BEFDDRPP_BP6_USD': 'Exceptional Financing, Direct Investment, Debt Instruments, Rescheduling of Payments Due in Current Reporting Period, Principal, US Dollars', 'BEFDDRP_BP6_USD': 'Exceptional Financing, Direct Investment, Debt Instruments, Rescheduling of Payments Due in Current Reporting Period, US Dollars', 'BEFDDSAI_BP6_USD': 'Exceptional Financing, Direct Investment, Debt Instruments, Rescheduling of Arrears, Interest/Coupon, US Dollars', 'BEFDDSAP_BP6_USD': 'Exceptional Financing, Direct Investment, Debt Instruments, Rescheduling of Arrears, Principal, US Dollars', 'BEFDDSA_BP6_USD': 'Exceptional Financing, Direct Investment, Debt Instruments, Rescheduling of Arrears, US Dollars', 'BEFDD_BP6_USD': 'Exceptional Financing, Direct Investment, Debt Instruments, US Dollars', 'BEFDE_BP6_USD': 'Exceptional Financing, Direct Investment, Equity Investment Associated with Debt Reduction, US Dollars', 'BEFD_BP6_USD': 'Exceptional Financing, Direct Investment, US Dollars', 'BEFISGIMF_BP6_USD': 'Exceptional Financing, Secondary Income, Grants Received from IMF Subsidy Accounts, US Dollars', 'BEFISIG_BP6_USD': 'Exceptional Financing, Secondary Income, Other Intergovernmental grants, US Dollars', 'BEFIS_BP6_USD': 'Exceptional Financing, Secondary Income, US Dollars', 'BEFOE_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Equity Investment Associated with Debt Reduction, US Dollars', 'BEFOODCBAAI_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Central Bank, Accumulation of Arrears, Original Interest, US Dollars', 'BEFOODCBAAPI_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Central Bank, Accumulation of Arrears, Penalty Interest, US Dollars', 'BEFOODCBAAP_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Central Bank, Accumulation of Arrears, Principal, US Dollars', 'BEFOODCBAA_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Central Bank, Accumulation of Arrears, US Dollars', 'BEFOODCBCAI_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Central Bank, Cancellation of Arrears, Interest, US Dollars', 'BEFOODCBCAP_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Central Bank, Cancellation of Arrears, Principal, US Dollars', 'BEFOODCBCA_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Central Bank, Cancellation of Arrears, US Dollars', 'BEFOODCBND_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Central Bank, New Drawings/Deposits, US Dollars', 'BEFOODCBPP_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Central Bank, Prepayment, US Dollars', 'BEFOODCBRAI_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Central Bank, Repayment of Arrears, Interest, US Dollars', 'BEFOODCBRAP_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Central Bank, Repayment of Arrears, Principal, US Dollars', 'BEFOODCBRA_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Central Bank, Repayment of Arrears, US Dollars', 'BEFOODCBRPI_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Central Bank, Rescheduling of Payments Due in Current Reporting Period, Interest, US Dollars', 'BEFOODCBRPP_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Central Bank, Rescheduling of Payments Due in Current Reporting Period, Principal, US Dollars', 'BEFOODCBRP_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Central Bank, Rescheduling of Payments Due in Current Reporting Period, US Dollars', 'BEFOODCBSAI_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Central Bank, Rescheduling of Arrears, Interest, US Dollars', 'BEFOODCBSAP_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Central Bank, Rescheduling of Arrears, Principal, US Dollars', 'BEFOODCBSA_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Central Bank, Rescheduling of Arrears, US Dollars', 'BEFOODCB_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Central Bank, US Dollars', 'BEFOODDCAAI_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Deposit-taking Corporations, Except Central Bank, Accumulation of Arrears, Original Interest, US Dollars', 'BEFOODDCAAPI_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Deposit-taking Corporations, Except Central Bank, Accumulation of Arrears, Penalty Interest, US Dollars', 'BEFOODDCAAP_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Deposit-taking Corporations, Except Central Bank, Accumulation of Arrears, Principal, US Dollars', 'BEFOODDCAA_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Deposit-taking Corporations, Except Central Bank, Accumulation of Arrears, US Dollars', 'BEFOODDCCAI_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Deposit-taking Corporations, Except Central Bank, Cancellation of Arrears, Interest, US Dollars', 'BEFOODDCCAP_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Deposit-taking Corporations, Except Central Bank, Cancellation of Arrears, Principal, US Dollars', 'BEFOODDCCA_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Deposit-taking Corporations, Except Central Bank, Cancellation of Arrears, US Dollars', 'BEFOODDCND_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Deposit-taking Corporations, Except Central Bank, New Drawings/Deposits on Behalf of Authorities, US Dollars', 'BEFOODDCPP_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Deposit-taking Corporations, Except Central Bank, Prepayment, US Dollars', 'BEFOODDCRAI_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Deposit-taking Corporations, Except Central Bank, Repayment of Arrears, Interest, US Dollars', 'BEFOODDCRAP_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Deposit-taking Corporations, Except Central Bank, Repayment of Arrears, Principal, US Dollars', 'BEFOODDCRA_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Deposit-taking Corporations, Except Central Bank, Repayment of Arrears, US Dollars', 'BEFOODDCRPI_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Deposit-taking Corporations, Except Central Bank, Rescheduling of Payments Due in Current Reporting Period, Interest, US Dollars', 'BEFOODDCRPP_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Deposit-taking Corporations, Except Central Bank, Rescheduling of Payments Due in Current Reporting Period, Principal, US Dollars', 'BEFOODDCRP_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Deposit-taking Corporations, Except Central Bank, Rescheduling of Payments Due in Current Reporting Period, US Dollars', 'BEFOODDCSAI_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Deposit-taking Corporations, Except Central Bank, Rescheduling of Arrears, Interest, US Dollars', 'BEFOODDCSAP_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Deposit-taking Corporations, Except Central Bank, Rescheduling of Arrears, Principal, US Dollars', 'BEFOODDCSA_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Deposit-taking Corporations, Except Central Bank, Rescheduling of Arrears, US Dollars', 'BEFOODDC_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Deposit-taking Corporations, Except Central Bank, US Dollars', 'BEFOODGAAI_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, General Government, Accumulation of Arrears, Original Interest, US Dollars', 'BEFOODGAAPI_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, General Government, Accumulation of Arrears, Penalty Interest, US Dollars', 'BEFOODGAAP_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, General Government, Accumulation of Arrears, Principal, US Dollars', 'BEFOODGAA_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, General Government, Accumulation of Arrears, US Dollars', 'BEFOODGCAI_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, General Government, Cancellation of Arrears, Interest, US Dollars', 'BEFOODGCAP_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, General Government, Cancellation of Arrears, Principal, US Dollars', 'BEFOODGCA_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, General Government, Cancellation of Arrears, US Dollars', 'BEFOODGND_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, General Government, New Drawings/Deposits, US Dollars', 'BEFOODGPP_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, General Government, Prepayment, US Dollars', 'BEFOODGRAI_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, General Government, Repayment of Arrears, Interest, US Dollars', 'BEFOODGRAP_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, General Government, Repayment of Arrears, Principal, US Dollars', 'BEFOODGRA_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, General Government, Repayment of Arrears, US Dollars', 'BEFOODGRPI_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, General Government, Rescheduling of Payments Due in Current Reporting Period, Interest, US Dollars', 'BEFOODGRPP_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, General Government, Rescheduling of Payments Due in Current Reporting Period, Principal, US Dollars', 'BEFOODGRP_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, General Government, Rescheduling of Payments Due in Current Reporting Period, US Dollars', 'BEFOODGSAI_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, General Government, Rescheduling of Arrears, Interest, US Dollars', 'BEFOODGSAP_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, General Government, Rescheduling of Arrears, Principal, US Dollars', 'BEFOODGSA_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, General Government, Rescheduling of Arrears, US Dollars', 'BEFOODG_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, General Government, US Dollars', 'BEFOODOAAI_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Other Sectors, Accumulation of Arrears, Original Interest, US Dollars', 'BEFOODOAAPI_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Other Sectors, Accumulation of Arrears, Penalty Interest, US Dollars', 'BEFOODOAAP_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Other Sectors, Accumulation of Arrears, Principal, US Dollars', 'BEFOODOAA_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Other Sectors, Accumulation of Arrears, US Dollars', 'BEFOODOCAI_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Other Sectors, Cancellation of Arrears, Interest, US Dollars', 'BEFOODOCAP_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Other Sectors, Cancellation of Arrears, Principal, US Dollars', 'BEFOODOCA_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Other Sectors, Cancellation of Arrears, US Dollars', 'BEFOODOFAAI_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Other Financial Corporations, Accumulation of Arrears, Original Interest, US Dollars', 'BEFOODOFAAPI_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Other Financial Corporations, Accumulation of Arrears, Penalty Interest, US Dollars', 'BEFOODOFAAP_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Other Financial Corporations, Accumulation of Arrears, Principal, US Dollars', 'BEFOODOFAA_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Other Financial Corporations, Accumulation of Arrears, US Dollars', 'BEFOODOFCAI_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Other Financial Corporations, Cancellation of Arrears, Interest, US Dollars', 'BEFOODOFCAP_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Other Financial Corporations, Cancellation of Arrears, Principal, US Dollars', 'BEFOODOFCA_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Other Financial Corporations, Cancellation of Arrears, US Dollars', 'BEFOODOFND_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Other Financial Corporations, New Drawings/Deposits on Behalf of Authorities, US Dollars', 'BEFOODOFPP_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Other Financial Corporations, Prepayment, US Dollars', 'BEFOODOFRAI_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Other Financial Corporations, Repayment of Arrears, Interest, US Dollars', 'BEFOODOFRAP_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Other Financial Corporations, Repayment of Arrears, Principal, US Dollars', 'BEFOODOFRA_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Other Financial Corporations, Repayment of Arrears, US Dollars', 'BEFOODOFRPI_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Other Financial Corporations, Rescheduling of Payments Due in Current Reporting Period, Interest, US Dollars', 'BEFOODOFRPP_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Other Financial Corporations, Rescheduling of Payments Due in Current Reporting Period, Principal, US Dollars', 'BEFOODOFRP_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Other Financial Corporations, Rescheduling of Payments Due in Current Reporting Period, US Dollars', 'BEFOODOFSAI_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Other Financial Corporations, Rescheduling of Arrears, Interest, US Dollars', 'BEFOODOFSAP_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Other Financial Corporations, Rescheduling of Arrears, Principal, US Dollars', 'BEFOODOFSA_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Other Financial Corporations, Rescheduling of Arrears, US Dollars', 'BEFOODOF_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Other Financial Corporations, US Dollars', 'BEFOODOND_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Other Sectors, New Drawings/Deposits on Behalf of Authorities, US Dollars', 'BEFOODONFAAI_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Nonfinancial Corporations, Households, NPISHs, Accumulation of Arrears, Original Interest, US Dollars', 'BEFOODONFAAPI_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Nonfinancial Corporations, Households, NPISHs, Accumulation of Arrears, Penalty Interest, US Dollars', 'BEFOODONFAAP_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Nonfinancial Corporations, Households, NPISHs, Accumulation of Arrears, Principal, US Dollars', 'BEFOODONFAA_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Nonfinancial Corporations, Households, NPISHs, Accumulation of Arrears, US Dollars', 'BEFOODONFCAI_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Nonfinancial Corporations, Households, NPISHs, Cancellation of Arrears, Interest, US Dollars', 'BEFOODONFCAP_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Nonfinancial Corporations, Households, NPISHs, Cancellation of Arrears, Principal, US Dollars', 'BEFOODONFCA_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Nonfinancial Corporations, Households, NPISHs, Cancellation of Arrears, US Dollars', 'BEFOODONFND_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Nonfinancial Corporations, Households, NPISHs, New Drawings/Deposits on Behalf of Authorities, US Dollars', 'BEFOODONFPP_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instrumen

In [51]:
d['BIS']['WS_GLI']

{'BORROWERS_SECTOR': {'A': 'All sectors',
  'B': 'Banks, total',
  'G': 'General government',
  'H': 'Households and NPISHs',
  'N': 'Non-banks, total'},
 'CURR_DENOM': {'USD': 'US dollar'},
 'LENDERS_SECTOR': {'A': 'All sectors',
  'B': 'Banks, total',
  'G': 'General government',
  'H': 'Households and NPISHs',
  'N': 'Non-banks, total'},
 'L_INSTR': {'A': 'All instruments',
  'B': 'Credit (loans & debt securities)',
  'D': 'Debt securities',
  'E': 'Risk-weighted assets',
  'G': 'Loans and deposits',
  'X': 'Equity instruments',
  'Y': 'Residual instrument'},
 'L_POS_TYPE': {'A': 'All'},
 'UNIT_MEASURE': {'770': 'Percentage of GDP'}}

In [53]:
count_dataset_d = {}
count_provider_d = {}
count_d = {}
for provider_id, provider_d in d.items():
    count_d[provider_id] = {}
    count_dataset_d[provider_id] = {}
    v_provider = 0
    for dataset_id, dataset_d in provider_d.items():
        count_d[provider_id][dataset_id] = {}
        count_dataset_d[provider_id][dataset_id] = {}
        v_dataset = 1
        for param, param_d in dataset_d.items():
            v_dataset = v_dataset * len(param_d)
        
        count_dataset_d[provider_id][dataset_id] = v_dataset
        v_provider = v_provider + v_dataset
    count_provider_d[provider_id] = v_provider

count_provider_d

{'IMF': 8547, 'WB': 3266, 'BIS': 250, 'UNCTAD': 69}

In [54]:
count_dataset_d

{'IMF': {'BOP': 2218,
  'CPI': 178,
  'FDI': 9,
  'FM': 9,
  'FSI': 959,
  'GENDER_EQUALITY': 3,
  'GFSMAB': 560,
  'HPDD': 1,
  'IFS': 1301,
  'IRFCL': 1475,
  'MFS': 575,
  'PGCS': 9,
  'PSBSFAD': 1235,
  'WoRLD': 15},
 'WB': {'DBS': 194,
  'ESY': 115,
  'FDX': 1226,
  'GEM': 36,
  'GEP': 1,
  'JOB': 166,
  'WDI': 1492,
  'WGI': 36},
 'BIS': {'WS_GLI': 175, 'WS_CREDIT_GAP': 75},
 'UNCTAD': {'MTTASA': 4,
  'MTBA': 2,
  'MTTGRA': 2,
  'MPCADIOEAIA': 6,
  'GASBTBIA': 8,
  'GASBTOIA': 16,
  'FDIIAOFASA': 20,
  'GDPTAPCCAC2PA': 4,
  'RGDPTAPCGRA': 2,
  'NGTAPCA': 2,
  'TAUPA': 2,
  'TPGRA': 1}}

In [756]:
d = client.list_series('ILO', 'LAP_2FTM_NOC_RT', limit=1)
d

{'_meta': {'args': {'align_periods': False,
   'dataset_code': 'LAP_2FTM_NOC_RT',
   'dimensions': {},
   'facets': False,
   'format': 'json',
   'limit': 1,
   'metadata': True,
   'observations': False,
   'offset': 0,
   'provider_code': 'ILO',
   'q': '',
   'series_code': None},
  'version': '22.1.17'},
 'dataset': {'attributes_labels': {'OBSV_STATUS': 'Observation status'},
  'attributes_values_labels': {'OBSV_STATUS': {'A': 'Adjusted',
    'B': 'Break in series',
    'C': 'Confidential',
    'E': 'Estimate',
    'I': 'Imputation',
    'M': 'Model-based extrapolation',
    'P': 'Provisional',
    'R': 'Real value',
    'S': 'Not significant',
    'U': 'Unreliable'}},
  'code': 'LAP_2FTM_NOC_RT',
  'dimensions_codes_order': ['ref_area', 'source', 'frequency'],
  'dimensions_labels': {'frequency': 'Frequency',
   'ref_area': 'Reference area',
   'source': 'Source'},
  'dimensions_values_labels': {'frequency': {'A': 'Annual'},
   'ref_area': {'X01': 'World',
    'X02': 'World: Low income',
    'X03': 'World: Lower-middle income',
    'X04': 'World: Upper-middle income',
    'X05': 'World: High income',
    'X06': 'Africa',
    'X07': 'Africa: Low income',
    'X08': 'Africa: Lower-middle income',
    'X09': 'Africa: Upper-middle income',
    'X10': 'Northern Africa',
    'X11': 'Northern Africa: Lower-middle income',
    'X13': 'Sub-Saharan Africa',
    'X14': 'Sub-Saharan Africa: Low income',
    'X15': 'Sub-Saharan Africa: Lower-middle income',
    'X16': 'Sub-Saharan Africa: Upper-middle income',
    'X17': 'Central Africa',
    'X18': 'Eastern Africa',
    'X19': 'Southern Africa',
    'X20': 'Western Africa',
    'X21': 'Americas',
    'X23': 'Americas: Lower-middle income',
    'X24': 'Americas: Upper-middle income',
    'X25': 'Americas: High income',
    'X26': 'Latin America and the Caribbean',
    'X28': 'Latin America and the Caribbean: Lower-middle income',
    'X29': 'Latin America and the Caribbean: Upper-middle income',
    'X30': 'Latin America and the Caribbean: High income',
    'X31': 'Caribbean',
    'X32': 'Central America',
    'X33': 'South America',
    'X34': 'Northern America',
    'X35': 'Northern America: High income',
    'X36': 'Arab States',
    'X37': 'Arab States: Lower-middle income',
    'X38': 'Arab States: Upper-middle income',
    'X39': 'Arab States: High income',
    'X40': 'Asia and the Pacific',
    'X41': 'Asia and the Pacific: Low income',
    'X42': 'Asia and the Pacific: Lower-middle income',
    'X43': 'Asia and the Pacific: Upper-middle income',
    'X44': 'Asia and the Pacific: High income',
    'X45': 'Eastern Asia',
    'X48': 'Eastern Asia: High income',
    'X49': 'South-Eastern Asia and the Pacific',
    'X51': 'South-Eastern Asia and the Pacific: Lower-middle income',
    'X52': 'South-Eastern Asia and the Pacific: Upper-middle income',
    'X53': 'South-Eastern Asia and the Pacific: High income',
    'X54': 'South-Eastern Asia',
    'X55': 'Pacific Islands',
    'X56': 'Southern Asia',
    'X58': 'Southern Asia: Lower-middle income',
    'X60': 'Europe and Central Asia',
    'X61': 'Europe and Central Asia: Lower-middle income',
    'X62': 'Europe and Central Asia: Upper-middle income',
    'X63': 'Europe and Central Asia: High income',
    'X64': 'Northern, Southern and Western Europe',
    'X65': 'Northern, Southern and Western Europe: Upper-middle income',
    'X66': 'Northern, Southern and Western Europe: High income',
    'X67': 'Northern Europe',
    'X68': 'Southern Europe',
    'X69': 'Western Europe',
    'X70': 'Eastern Europe',
    'X72': 'Eastern Europe: Upper-middle income',
    'X73': 'Eastern Europe: High income',
    'X74': 'Central Asia',
    'X75': 'Central and Western Asia: Lower-middle income',
    'X76': 'Central and Western Asia: Upper-middle income',
    'X77': 'Central and Western Asia: High income',
    'X78': 'Central and Western Asia',
    'X79': 'Western Asia',
    'X82': 'European Union 28',
    'X83': 'G20',
    'X84': 'ASEAN',
    'X85': 'BRICS',
    'X87': 'World excluding BRICS',
    'X88': 'G7',
    'X89': 'MENA',
    'X90': 'Arab League',
    'X91': 'CARICOM',
    'X92': 'European Union 27',
    'X94': 'Arab States: Low income',
    'X97': 'APEC'},
   'source': {'XA_12987': 'ILO - Modelled Estimates',
    'XA_12988': 'ILO - Modelled Estimates',
    'XA_12989': 'ILO - Modelled Estimates',
    'XA_12990': 'ILO - Modelled Estimates',
    'XA_13329': 'ILO - Modelled Estimates',
    'XA_14065': 'ILO - Modelled Estimates',
    'XA_14066': 'ILO - Modelled Estimates',
    'XA_15672': 'ILO - Modelled Estimates',
    'XA_15716': 'ILO - Modelled Estimates',
    'XA_15724': 'ILO - Modelled Estimates',
    'XA_15736': 'ILO - Modelled Estimates',
    'XA_16111': 'ILO - Modelled Estimates',
    'XA_8372': 'ILO - Modelled Estimates',
    'XA_8373': 'ILO - Modelled Estimates',
    'XA_8374': 'ILO - Modelled Estimates',
    'XA_8375': 'ILO - Modelled Estimates',
    'XA_8376': 'ILO - Modelled Estimates',
    'XA_8377': 'ILO - Modelled Estimates',
    'XA_8378': 'ILO - Modelled Estimates',
    'XA_8379': 'ILO - Modelled Estimates',
    'XA_8380': 'ILO - Modelled Estimates',
    'XA_8381': 'ILO - Modelled Estimates',
    'XA_8382': 'ILO - Modelled Estimates',
    'XA_8383': 'ILO - Modelled Estimates',
    'XA_8384': 'ILO - Modelled Estimates',
    'XA_8385': 'ILO - Modelled Estimates',
    'XA_8386': 'ILO - Modelled Estimates',
    'XA_8387': 'ILO - Modelled Estimates',
    'XA_8388': 'ILO - Modelled Estimates',
    'XA_8389': 'ILO - Modelled Estimates',
    'XA_8390': 'ILO - Modelled Estimates',
    'XA_8391': 'ILO - Modelled Estimates',
    'XA_8392': 'ILO - Modelled Estimates',
    'XA_8393': 'ILO - Modelled Estimates',
    'XA_8394': 'ILO - Modelled Estimates',
    'XA_8395': 'ILO - Modelled Estimates',
    'XA_8396': 'ILO - Modelled Estimates',
    'XA_8397': 'ILO - Modelled Estimates',
    'XA_8398': 'ILO - Modelled Estimates',
    'XA_8399': 'ILO - Modelled Estimates',
    'XA_8400': 'ILO - Modelled Estimates',
    'XA_8401': 'ILO - Modelled Estimates',
    'XA_8402': 'ILO - Modelled Estimates',
    'XA_8403': 'ILO - Modelled Estimates',
    'XA_8404': 'ILO - Modelled Estimates',
    'XA_8405': 'ILO - Modelled Estimates',
    'XA_8406': 'ILO - Modelled Estimates',
    'XA_8407': 'ILO - Modelled Estimates',
    'XA_8408': 'ILO - Modelled Estimates',
    'XA_8409': 'ILO - Modelled Estimates',
    'XA_8411': 'ILO - Modelled Estimates',
    'XA_8412': 'ILO - Modelled Estimates',
    'XA_8413': 'ILO - Modelled Estimates',
    'XA_8415': 'ILO - Modelled Estimates',
    'XA_8416': 'ILO - Modelled Estimates',
    'XA_8417': 'ILO - Modelled Estimates',
    'XA_8419': 'ILO - Modelled Estimates',
    'XA_8420': 'ILO - Modelled Estimates',
    'XA_8421': 'ILO - Modelled Estimates',
    'XA_8422': 'ILO - Modelled Estimates',
    'XA_8423': 'ILO - Modelled Estimates',
    'XA_8424': 'ILO - Modelled Estimates',
    'XA_8425': 'ILO - Modelled Estimates',
    'XA_8426': 'ILO - Modelled Estimates',
    'XA_8427': 'ILO - Modelled Estimates',
    'XA_8428': 'ILO - Modelled Estimates',
    'XA_8429': 'ILO - Modelled Estimates',
    'XA_8432': 'ILO - Modelled Estimates',
    'XA_8434': 'ILO - Modelled Estimates',
    'XA_8435': 'ILO - Modelled Estimates',
    'XA_8436': 'ILO - Modelled Estimates',
    'XA_8438': 'ILO - Modelled Estimates',
    'XA_8440': 'ILO - Modelled Estimates',
    'XA_8441': 'ILO - Modelled Estimates',
    'XA_8442': 'ILO - Modelled Estimates',
    'XA_8443': 'ILO - Modelled Estimates',
    'XA_8444': 'ILO - Modelled Estimates',
    'XA_8446': 'ILO - Modelled Estimates',
    'XA_8447': 'ILO - Modelled Estimates',
    'XA_8448': 'ILO - Modelled Estimates',
    'XA_8449': 'ILO - Modelled Estimates',
    'XA_8450': 'ILO - Modelled Estimates'}},
  'dir_hash': 'b9583d49c913d05b2fc4888b9b5f6c6f563fa7e1',
  'indexed_at': '2023-11-27T04:33:32.919Z',
  'name': "Gender income gap, ratio of women's to men's labour income -- ILO modelled estimates, Nov. 2022 (%)",
  'nb_series': 82,
  'provider_code': 'ILO',
  'provider_name': 'International Labour Organization'},
 'errors': None,
 'provider': {'code': 'ILO',
  'indexed_at': '2024-02-20T03:34:29.870Z',
  'name': 'International Labour Organization',
  'region': 'World',
  'slug': 'ilo',
  'terms_of_use': 'http://www.ilo.org/global/copyright/request-for-permission/lang--en/index.htm',
  'website': 'https://www.ilo.org'},
 'series': {'docs': [{'dataset_code': 'LAP_2FTM_NOC_RT',
    'dataset_name': "Gender income gap, ratio of women's to men's labour income -- ILO modelled estimates, Nov. 2022 (%)",
    'dimensions': {'frequency': 'A', 'ref_area': 'X01', 'source': 'XA_8405'},
    'indexed_at': '2023-11-27T04:33:32.919Z',
    'provider_code': 'ILO',
    'series_code': 'X01.XA_8405.A',
    'series_name': 'World – ILO - Modelled Estimates (XA_8405) – Annual'}],
  'limit': 1,
  'num_found': 82,
  'offset': 0}}

In [752]:
d.keys()

dict_keys(['_meta', 'dataset', 'errors', 'provider', 'series'])

In [753]:
d['dataset'].keys()

dict_keys(['attributes_labels', 'attributes_values_labels', 'code', 'dimensions_codes_order', 'dimensions_labels', 'dimensions_values_labels', 'dir_hash', 'indexed_at', 'name', 'nb_series', 'provider_code', 'provider_name'])

In [757]:
d['dataset']['dimensions_values_labels'].keys()

dict_keys(['frequency', 'ref_area', 'source'])

In [758]:
d['dataset']['dimensions_values_labels']['ref_area']

{'X01': 'World',
 'X02': 'World: Low income',
 'X03': 'World: Lower-middle income',
 'X04': 'World: Upper-middle income',
 'X05': 'World: High income',
 'X06': 'Africa',
 'X07': 'Africa: Low income',
 'X08': 'Africa: Lower-middle income',
 'X09': 'Africa: Upper-middle income',
 'X10': 'Northern Africa',
 'X11': 'Northern Africa: Lower-middle income',
 'X13': 'Sub-Saharan Africa',
 'X14': 'Sub-Saharan Africa: Low income',
 'X15': 'Sub-Saharan Africa: Lower-middle income',
 'X16': 'Sub-Saharan Africa: Upper-middle income',
 'X17': 'Central Africa',
 'X18': 'Eastern Africa',
 'X19': 'Southern Africa',
 'X20': 'Western Africa',
 'X21': 'Americas',
 'X23': 'Americas: Lower-middle income',
 'X24': 'Americas: Upper-middle income',
 'X25': 'Americas: High income',
 'X26': 'Latin America and the Caribbean',
 'X28': 'Latin America and the Caribbean: Lower-middle income',
 'X29': 'Latin America and the Caribbean: Upper-middle income',
 'X30': 'Latin America and the Caribbean: High income',
 'X31': 'Caribbean',
 'X32': 'Central America',
 'X33': 'South America',
 'X34': 'Northern America',
 'X35': 'Northern America: High income',
 'X36': 'Arab States',
 'X37': 'Arab States: Lower-middle income',
 'X38': 'Arab States: Upper-middle income',
 'X39': 'Arab States: High income',
 'X40': 'Asia and the Pacific',
 'X41': 'Asia and the Pacific: Low income',
 'X42': 'Asia and the Pacific: Lower-middle income',
 'X43': 'Asia and the Pacific: Upper-middle income',
 'X44': 'Asia and the Pacific: High income',
 'X45': 'Eastern Asia',
 'X48': 'Eastern Asia: High income',
 'X49': 'South-Eastern Asia and the Pacific',
 'X51': 'South-Eastern Asia and the Pacific: Lower-middle income',
 'X52': 'South-Eastern Asia and the Pacific: Upper-middle income',
 'X53': 'South-Eastern Asia and the Pacific: High income',
 'X54': 'South-Eastern Asia',
 'X55': 'Pacific Islands',
 'X56': 'Southern Asia',
 'X58': 'Southern Asia: Lower-middle income',
 'X60': 'Europe and Central Asia',
 'X61': 'Europe and Central Asia: Lower-middle income',
 'X62': 'Europe and Central Asia: Upper-middle income',
 'X63': 'Europe and Central Asia: High income',
 'X64': 'Northern, Southern and Western Europe',
 'X65': 'Northern, Southern and Western Europe: Upper-middle income',
 'X66': 'Northern, Southern and Western Europe: High income',
 'X67': 'Northern Europe',
 'X68': 'Southern Europe',
 'X69': 'Western Europe',
 'X70': 'Eastern Europe',
 'X72': 'Eastern Europe: Upper-middle income',
 'X73': 'Eastern Europe: High income',
 'X74': 'Central Asia',
 'X75': 'Central and Western Asia: Lower-middle income',
 'X76': 'Central and Western Asia: Upper-middle income',
 'X77': 'Central and Western Asia: High income',
 'X78': 'Central and Western Asia',
 'X79': 'Western Asia',
 'X82': 'European Union 28',
 'X83': 'G20',
 'X84': 'ASEAN',
 'X85': 'BRICS',
 'X87': 'World excluding BRICS',
 'X88': 'G7',
 'X89': 'MENA',
 'X90': 'Arab League',
 'X91': 'CARICOM',
 'X92': 'European Union 27',
 'X94': 'Arab States: Low income',
 'X97': 'APEC'}

In [ ]:
BORROWERS_CTY/DSR_BORROWERS/FREQ

In [499]:
d['series'].keys()

dict_keys(['docs', 'limit', 'num_found', 'offset'])

In [659]:
d['series']['docs'][0]

{'dataset_code': 'WS_TC',
 'dataset_name': 'BIS long series on total credit',
 'dimensions': {'BORROWERS_CTY': '4T',
  'FREQ': 'Q',
  'TC_ADJUST': 'A',
  'TC_BORROWERS': 'C',
  'TC_LENDERS': 'A',
  'UNIT_TYPE': '770',
  'VALUATION': 'M'},
 'indexed_at': '2025-06-20T14:22:50.994Z',
 'provider_code': 'BIS',
 'series_code': 'Q.4T.C.A.M.770.A',
 'series_name': 'Quarterly – Emerging market economies (aggregate) – Non financial sector – All sectors – Market value – Percentage of GDP – Adjusted for breaks'}

In [656]:
import requests

url = "https://api.db.nomics.world/v22" + "/series/WB/ESY/?"

r = requests.get(url)
r.raise_for_status()
r.json()

{'_meta': {'args': {'align_periods': False,
   'dataset_code': 'ESY',
   'dimensions': {},
   'facets': False,
   'format': 'json',
   'limit': 1000,
   'metadata': True,
   'observations': False,
   'offset': 0,
   'provider_code': 'WB',
   'q': '',
   'series_code': None},
  'version': '22.1.17'},
 'dataset': {'code': 'ESY',
  'dimensions_codes_order': ['frequency', 'indicator', 'country'],
  'dimensions_values_labels': {'country': {'AFG': 'Afghanistan',
    'AGO': 'Angola',
    'ALB': 'Albania',
    'ARG': 'Argentina',
    'ARM': 'Armenia',
    'ATG': 'Antigua and Barbuda',
    'AZE': 'Azerbaijan',
    'BDI': 'Burundi',
    'BEL': 'Belgium',
    'BEN': 'Benin',
    'BFA': 'Burkina Faso',
    'BGD': 'Bangladesh',
    'BGR': 'Bulgaria',
    'BHS': 'Bahamas, The',
    'BIH': 'Bosnia and Herzegovina',
    'BLR': 'Belarus',
    'BLZ': 'Belize',
    'BOL': 'Bolivia',
    'BRA': 'Brazil',
    'BRB': 'Barbados',
    'BTN': 'Bhutan',
    'BWA': 'Botswana',
    'CAF': 'Central African Republic',
    'CHL': 'Chile',
    'CHN': 'China',
    'CIV': "Cote d'Ivoire",
    'CMR': 'Cameroon',
    'COD': 'Congo, Dem. Rep.',
    'COG': 'Congo, Rep.',
    'COL': 'Colombia',
    'CPV': 'Cabo Verde',
    'CRI': 'Costa Rica',
    'CYP': 'Cyprus',
    'CZE': 'Czech Republic',
    'DJI': 'Djibouti',
    'DMA': 'Dominica',
    'DOM': 'Dominican Republic',
    'ECU': 'Ecuador',
    'EGY': 'Egypt, Arab Rep.',
    'ERI': 'Eritrea',
    'EST': 'Estonia',
    'ETH': 'Ethiopia',
    'FJI': 'Fiji',
    'FSM': 'Micronesia, Fed. Sts.',
    'GAB': 'Gabon',
    'GEO': 'Georgia',
    'GHA': 'Ghana',
    'GIN': 'Guinea',
    'GMB': 'Gambia, The',
    'GNB': 'Guinea-Bissau',
    'GRC': 'Greece',
    'GRD': 'Grenada',
    'GTM': 'Guatemala',
    'GUY': 'Guyana',
    'HND': 'Honduras',
    'HRV': 'Croatia',
    'HUN': 'Hungary',
    'IDN': 'Indonesia',
    'IND': 'India',
    'IRQ': 'Iraq',
    'ISR': 'Israel',
    'ITA': 'Italy',
    'JAM': 'Jamaica',
    'JOR': 'Jordan',
    'KAZ': 'Kazakhstan',
    'KEN': 'Kenya',
    'KGZ': 'Kyrgyz Republic',
    'KHM': 'Cambodia',
    'KNA': 'St. Kitts and Nevis',
    'LAO': 'Lao PDR',
    'LBN': 'Lebanon',
    'LBR': 'Liberia',
    'LCA': 'St. Lucia',
    'LKA': 'Sri Lanka',
    'LSO': 'Lesotho',
    'LTU': 'Lithuania',
    'LUX': 'Luxembourg',
    'LVA': 'Latvia',
    'MAR': 'Morocco',
    'MDA': 'Moldova',
    'MDG': 'Madagascar',
    'MEX': 'Mexico',
    'MKD': 'North Macedonia',
    'MLI': 'Mali',
    'MLT': 'Malta',
    'MMR': 'Myanmar',
    'MNE': 'Montenegro',
    'MNG': 'Mongolia',
    'MOZ': 'Mozambique',
    'MRT': 'Mauritania',
    'MUS': 'Mauritius',
    'MWI': 'Malawi',
    'MYS': 'Malaysia',
    'NAM': 'Namibia',
    'NER': 'Niger',
    'NGA': 'Nigeria',
    'NIC': 'Nicaragua',
    'NPL': 'Nepal',
    'PAK': 'Pakistan',
    'PAN': 'Panama',
    'PER': 'Peru',
    'PHL': 'Philippines',
    'PNG': 'Papua New Guinea',
    'POL': 'Poland',
    'PRT': 'Portugal',
    'PRY': 'Paraguay',
    'PSE': 'West Bank and Gaza',
    'ROU': 'Romania',
    'RUS': 'Russian Federation',
    'RWA': 'Rwanda',
    'SDN': 'Sudan',
    'SEN': 'Senegal',
    'SLB': 'Solomon Islands',
    'SLE': 'Sierra Leone',
    'SLV': 'El Salvador',
    'SRB': 'Serbia',
    'SSD': 'South Sudan',
    'SUR': 'Suriname',
    'SVK': 'Slovak Republic',
    'SVN': 'Slovenia',
    'SWE': 'Sweden',
    'SWZ': 'Eswatini',
    'TCD': 'Chad',
    'TGO': 'Togo',
    'THA': 'Thailand',
    'TJK': 'Tajikistan',
    'TLS': 'Timor-Leste',
    'TON': 'Tonga',
    'TTO': 'Trinidad and Tobago',
    'TUN': 'Tunisia',
    'TUR': 'Turkey',
    'TZA': 'Tanzania',
    'UGA': 'Uganda',
    'UKR': 'Ukraine',
    'URY': 'Uruguay',
    'UZB': 'Uzbekistan',
    'VCT': 'St. Vincent and the Grenadines',
    'VEN': 'Venezuela, RB',
    'VNM': 'Vietnam',
    'VUT': 'Vanuatu',
    'WSM': 'Samoa',
    'XKX': 'Kosovo',
    'YEM': 'Yemen, Rep.',
    'ZAF': 'South Africa',
    'ZMB': 'Zambia',
    'ZWE': 'Zimbabwe'},
   'frequency': {'A': 'Annual'},
   'indicator': {'IC.FRM.BRIB.GRAFT2': 'Bribery depth (% of public transactions where a gift or informal payment was requested)',
    'IC.FRM.BRIB.GRAFT3': 'Bribery incidence (percent of firms experiencing at least one bribe payment request)',
    'IC.FRM.CORR.CORR1': 'Percent of firms expected to give gifts in meetings with tax officials',
    'IC.FRM.CORR.CORR10': 'Percent of firms expected to give gifts to get an operating license',
    'IC.FRM.CORR.CORR11': 'Percent of firms identifying corruption as a major constraint',
    'IC.FRM.CORR.CORR2': 'Percent of firms expected to give gifts to secure government contract',
    'IC.FRM.CORR.CORR3': 'Value of gift expected to secure a government contract (% of contract value)',
    'IC.FRM.CORR.CORR4': 'Percent of firms expected to give gifts to public officials "to get things done"',
    'IC.FRM.CORR.CORR6': 'Percent of firms expected to give gifts to get an electrical connection',
    'IC.FRM.CORR.CORR7': 'Percent of firms expected to give gifts to get a water connection',
    'IC.FRM.CORR.CORR8': 'Percent of firms expected to give gifts to get a construction permit',
    'IC.FRM.CORR.CORR9': 'Percent of firms expected to give gifts to get an import license',
    'IC.FRM.CORR.CRIME9': 'Percent of firms identifying the courts system as a major constraint',
    'IC.FRM.CRM.CRIME1': 'Percent of firms paying for security',
    'IC.FRM.CRM.CRIME10': 'Percent of firms experiencing losses due to theft and vandalism',
    'IC.FRM.CRM.CRIME2_C': 'If the establishment pays for security, average security costs (% of annual sales)',
    'IC.FRM.CRM.CRIME3_C': 'If there were losses, average losses due to theft and vandalism (% of annual sales)',
    'IC.FRM.CRM.CRIME5': 'Products shipped to supply domestic markets that were lost due to theft (% of product value)',
    'IC.FRM.CRM.CRIME8': 'Percent of firms identifying crime, theft and disorder as a major constraint',
    'IC.FRM.EMP.GROW.PEFT2': 'Annual employment growth (%)',
    'IC.FRM.FCHAR.CAR1': 'Age of the establishment (years)',
    'IC.FRM.FCHAR.CAR2': 'Proportion of private domestic ownership in a firm (%)',
    'IC.FRM.FCHAR.CAR7': 'Percent of firms with at least 10% of foreign ownership',
    'IC.FRM.FCHAR.CAR8': 'Percent of firms with at least 10% of government/state ownership',
    'IC.FRM.FCHAR.LFORM3': 'Percent of firms with legal status of Sole Proprietorship',
    'IC.FRM.FIAS.PEFT4': 'Percent of firms buying fixed assets',
    'IC.FRM.FIN.FIN1': 'Proportion of investment financed internally (%)',
    'IC.FRM.FIN.FIN10': 'Value of collateral needed for a loan (% of the loan amount)',
    'IC.FRM.FIN.FIN11': 'Proportion of loans requiring collateral (%)',
    'IC.FRM.FIN.FIN12': 'Percent of firms using banks to finance investments',
    'IC.FRM.FIN.FIN13': 'Percent of firms using banks to finance working capital',
    'IC.FRM.FIN.FIN14': 'Percent of firms with a bank loan/line of credit',
    'IC.FRM.FIN.FIN15': 'Percent of firms with a checking or savings account',
    'IC.FRM.FIN.FIN16': 'Percent of firms identifying access to finance as a major constraint',
    'IC.FRM.FIN.FIN2': 'Proportion of investment financed by banks (%)',
    'IC.FRM.FIN.FIN20': 'Percent of firms not needing a loan',
    'IC.FRM.FIN.FIN21': 'Percent of firms whose recent loan application was rejected',
    'IC.FRM.FIN.FIN22': 'Percent of firms using supplier/customer credit to finance working capital',
    'IC.FRM.FIN.FIN7': 'Proportion of working capital financed by banks (%)',
    'IC.FRM.GEN.GEND1': 'Percent of firms with female participation in ownership',
    'IC.FRM.GEN.GEND2': 'Proportion of permanent full-time workers that are female (%)',
    'IC.FRM.GEN.GEND3': 'Proportion of permanent full-time non-production workers that are female (%)',
    'IC.FRM.GEN.GEND4': 'Percent of firms with a female top manager',
    'IC.FRM.GEN.GEND5': 'Proportion of permanent full-time production workers that are female (%)',
    'IC.FRM.GEN.GEND6': 'Percent of firms with majority female ownership',
    'IC.FRM.INFOR.INFOR1': 'Percent of firms competing against unregistered or informal firms',
    'IC.FRM.INFOR.INFOR2': 'Percent of firms identifying practices of competitors in the informal sector as a major constraint',
    'IC.FRM.INFOR.INFOR4': 'Percent of firms formally registered when they started operations in the country',
    'IC.FRM.INFOR.INFOR5': 'Number of years firm operated without formal registration',
    'IC.FRM.INFRA.IN1': 'Days to obtain an electrical connection (upon application)',
    'IC.FRM.INFRA.IN10_C': 'If a generator is used, average proportion of electricity from a generator (%)',
    'IC.FRM.INFRA.IN11': 'Percent of firms identifying transportation as a major constraint',
    'IC.FRM.INFRA.IN12': 'Percent of firms identifying electricity as a major constraint',
    'IC.FRM.INFRA.IN14': 'Proportion of products lost to breakage or spoilage during shipping to domestic markets (%)',
    'IC.FRM.INFRA.IN16': 'Percent of firms experiencing electrical outages',
    'IC.FRM.INFRA.IN17': 'Percent of firms experiencing water insufficiencies',
    'IC.FRM.INFRA.IN2': 'Number of electrical outages in a typical month',
    'IC.FRM.INFRA.IN3_C': 'If there were outages, average duration of a typical electrical outage (hours)',
    'IC.FRM.INFRA.IN4_C': 'If there were outages, average losses due to electrical outages (% of annual sales)',
    'IC.FRM.INFRA.IN6': 'Number of water insufficiencies in a typical month',
    'IC.FRM.INFRA.IN9': 'Percent of firms owning or sharing a generator',
    'IC.FRM.INNOV.T1': 'Percent of firms with an internationally-recognized quality certification',
    'IC.FRM.INNOV.T10': 'Percent of firms that spend on R&D',
    'IC.FRM.INNOV.T2': 'Percent of firms with an annual financial statement reviewed by external auditors',
    'IC.FRM.INNOV.T3': 'Capacity utilization (%)',
    'IC.FRM.INNOV.T4': 'Percent of firms using technology licensed from foreign companies',
    'IC.FRM.INNOV.T5': 'Percent of firms having their own Web site',
    'IC.FRM.INNOV.T6': 'Percent of firms using e-mail to interact with clients/suppliers',
    'IC.FRM.INNOV.T7': 'Percent of firms that introduced a new product/service',
    'IC.FRM.INNOV.T8': 'Percent of firms whose new product/service is also new to the main market',
    'IC.FRM.INNOV.T9': 'Percent of firms that introduced a process innovation',
    'IC.FRM.OBS.OBST1': 'Percent of firms choosing access to finance as their biggest obstacle',
    'IC.FRM.OBS.OBST10': 'Percent of firms choosing labor regulations as their biggest obstacle',
    'IC.FRM.OBS.OBST11': 'Percent of firms choosing political instability as their biggest obstacle',
    'IC.FRM.OBS.OBST12': 'Percent of firms choosing practices of the informal sector as their biggest obstacle',
    'IC.FRM.OBS.OBST13': 'Percent of firms choosing tax administration as their biggest obstacle',
    'IC.FRM.OBS.OBST14': 'Percent of firms choosing tax rates as their biggest obstacle',
    'IC.FRM.OBS.OBST15': 'Percent of firms choosing transportation as their biggest obstacle',
    'IC.FRM.OBS.OBST2': 'Percent of firms choosing access to land as their biggest obstacle',
    'IC.FRM.OBS.OBST3': 'Percent of firms choosing business licensing and permits as their biggest obstacle',
    'IC.FRM.OBS.OBST4': 'Percent of firms choosing corruption as their biggest obstacle',
    'IC.FRM.OBS.OBST5': 'Percent of firms choosing courts as their biggest obstacle',
    'IC.FRM.OBS.OBST6': 'Percent of firms choosing crime, theft and disorder as their biggest obstacle',
    'IC.FRM.OBS.OBST7': 'Percent of firms choosing customs and trade regulations as their biggest obstacle',
    'IC.FRM.OBS.OBST8': 'Percent of firms choosing electricity as their biggest obstacle',
    'IC.FRM.OBS.OBST9': 'Percent of firms choosing inadequately educated workforce as their biggest obstacle',
    'IC.FRM.PROD.GROW.PEFT3': 'Real annual labor productivity growth (%)',
    'IC.FRM.REG.BUS1': 'Days to obtain an import license',
    'IC.FRM.REG.BUS2': 'Days to obtain an operating license',
    'IC.FRM.REG.BUS3': 'Days to obtain a construction-related permit',
    'IC.FRM.REG.BUS5': 'Percent of firms identifying business licensing and permits as a major constraint',
    'IC.FRM.REG.REG1': 'Senior management time spent dealing with the requirements of government regulation (%)',
    'IC.FRM.REG.REG2_C': 'If there were visits, average number of visits or required meetings with tax officials',
    'IC.FRM.REG.REG4': 'Percent of firms identifying tax rates as a major constraint',
    'IC.FRM.REG.REG5': 'Percent of firms identifying tax administration as a major constraint',
    'IC.FRM.REG.REG6': 'Percent of firms visited or required to meet with tax officials',
    'IC.FRM.SLS.GROW.PEFT1': 'Real annual sales growth (%)',
    'IC.FRM.TRD.TR1': 'Days to clear direct exports through customs',
    'IC.FRM.TRD.TR11': 'Percent of firms using material inputs and/or supplies of foreign origin',
    'IC.FRM.TRD.TR16': 'Percent of firms exporting directly (at least 10% of sales)',
    'IC.FRM.TRD.TR17': 'Percent of firms exporting directly or indirectly (at least 10% of sales)',
    'IC.FRM.TRD.TR2': 'Days to clear imports from customs',
    'IC.FRM.TRD.TR5': 'Proportion of total sales that are exported directly (%)',
    'IC.FRM.TRD.TR8': 'Proportion of total inputs that are of foreign origin (%)',
    'IC.FRM.TRD.TR9': 'Percent of firms identifying customs and trade regulations as a major constraint',
    'IC.FRM.WRKF.WK1': 'Percent of firms offering formal training',
    'IC.FRM.WRKF.WK10': 'Percent of firms identifying an inadequately educated workforce as a major constraint',
    'IC.FRM.WRKF.WK14': 'Number of workers',
    'IC.FRM.WRKF.WK15': 'Proportion of production workers (out of all permanent workers)',
    'IC.FRM.WRKF.WK17': 'Proportion of temporary workers (out of all workers)',
    'IC.FRM.WRKF.WK18': 'Proportion of permanent workers (out of all workers)',
    'IC.FRM.WRKF.WK19': 'Proportion of skilled workers (out of all production workers) (%)',
    'IC.FRM.WRKF.WK2': 'Proportion of workers offered formal training (%)',
    'IC.FRM.WRKF.WK8': "Years of the top manager's experience working in the firm's sector",
    'IC.FRM.WRKF.WK9': 'Percent of firms identifying labor regulations as a major constraint'}},
  'dir_hash': 'dfc9891c32572664f2e51c73da222636d4675fb2',
  'indexed_at': '2022-07-01T19:18:23.311Z',
  'name': 'Enterprise Surveys',
  'nb_series': 16790,
  'provider_code': 'WB',
  'provider_name': 'World Bank'},
 'errors': None,
 'provider': {'code': 'WB',
  'indexed_at': '2024-09-19T06:51:52.592Z',
  'name': 'World Bank',
  'region': 'World',
  'slug': 'wb',
  'website': 'https://www.worldbank.org/'},
 'series': {'docs': [{'dataset_code': 'ESY',
    'dataset_name': 'Enterprise Surveys',
    'dimensions': {'country': 'AFG',
     'frequency': 'A',
     'indicator': 'IC.FRM.BRIB.GRAFT2'},
    'indexed_at': '2022-07-01T19:18:23.311Z',
    'provider_code': 'WB',
    'series_code': 'A-IC.FRM.BRIB.GRAFT2-AFG',
    'series_name': 'Annual – Bribery depth (% of public transactions where a gift or informal payment was requested) – Afghanistan'},
   {'dataset_code': 'ESY',
    'dataset_name': 'Enterprise Surveys',
    'dimensions': {'country': 'AGO',
     'frequency': 'A',
     'indicator': 'IC.FRM.BRIB.GRAFT2'},
    'indexed_at': '2022-07-01T19:18:23.311Z',
    'provider_code': 'WB',
    'series_code': 'A-IC.FRM.BRIB.GRAFT2-AGO',
    'series_name': 'Annual – Bribery depth (% of public transactions where a gift or informal payment was requested) – Angola'},
   {'dataset_code': 'ESY',
    'dataset_name': 'Enterprise Surveys',
    'dimensions': {'country': 'ALB',
     'frequency': 'A',
     'indicator': 'IC.FRM.BRIB.GRAFT2'},
    'indexed_at': '2022-07-01T19:18:23.311Z',
    'provider_code': 'WB',
    'series_code': 'A-IC.FRM.BRIB.GRAFT2-ALB',
    'series_name': 'Annual – Bribery depth (% of public transactions where a gift or informal payment was requested) – Albania'},
   {'dataset_code': 'ESY',
    'dataset_name': 'Enterprise Surveys',
    'dimensions': {'country': 'ARG',
     'frequency': 'A',
     'indicator': 'IC.FRM.BRIB.GRAFT2'},
    'indexed_at': '2022-07-01T19:18:23.311Z',
    'provider_code': 'WB',
    'series_code': 'A-IC.FRM.BRIB.GRAFT2-ARG',
    'series_name': 'Annual – Bribery depth (% of public transactions where a gift or informal payment was requested) – Argentina'},
   {'dataset_code': 'ESY',
    'dataset_name': 'Enterprise Surveys',
    'dimensions': {'country': 'ARM',
     'frequency': 'A',
     'indicator': 'IC.FRM.BRIB.GRAFT2'},
    'indexed_at': '2022-07-01T19:18:23.311Z',
    'provider_code': 'WB',
    'series_code': 'A-IC.FRM.BRIB.GRAFT2-ARM',
    'series_name': 'Annual – Bribery depth (% of public transactions where a gift or informal payment was requested) – Armenia'},
   {'dataset_code': 'ESY',
    'dataset_name': 'Enterprise Surveys',
    'dimensions': {'country': 'ATG',
     'frequency': 'A',
     'indicator': 'IC.FRM.BRIB.GRAFT2'},
    'indexed_at': '2022-07-01T19:18:23.311Z',
    'provider_code': 'WB',
    'series_code': 'A-IC.FRM.BRIB.GRAFT2-ATG',
    'series_name': 'Annual – Bribery depth (% of public transactions where a gift or informal payment was requested) – Antigua and Barbuda'},
   {'dataset_code': 'ESY',
    'dataset_name': 'Enterprise Surveys',
    'dimensions': {'country': 'AZE',
     'frequency': 'A',
     'indicator': 'IC.FRM.BRIB.GRAFT2'},
    'indexed_at': '2022-07-01T19:18:23.311Z',
    'provider_code': 'WB',
    'series_code': 'A-IC.FRM.BRIB.GRAFT2-AZE',
    'series_name': 'Annual – Bribery depth (% of public transactions where a gift or informal payment was requested) – Azerbaijan'},
   {'dataset_code': 'ESY',
    'dataset_name': 'Enterprise Surveys',
    'dimensions': {'country': 'BDI',
     'frequency': 'A',
     'indicator': 'IC.FRM.BRIB.GRAFT2'},
    'indexed_at': '2022-07-01T19:18:23.311Z',
    'provider_code': 'WB',
    'series_code': 'A-IC.FRM.BRIB.GRAFT2-BDI',
    'series_name': 'Annual – Bribery depth (% of public transactions where a gift or informal payment was requested) – Burundi'},
   {'dataset_code': 'ESY',
    'dataset_name': 'Enterprise Surveys',
    'dimensions': {'country': 'BEL',
     'frequency': 'A',
     'indicator': 'IC.FRM.BRIB.GRAFT2'},
    'indexed_at': '2022-07-01T19:18:23.311Z',
    'provider_code': 'WB',
    'series_code': 'A-IC.FRM.BRIB.GRAFT2-BEL',
    'series_name': 'Annual – Bribery depth (% of public transactions where a gift or informal payment was requested) – Belgium'},
   {'dataset_code': 'ESY',
    'dataset_name': 'Enterprise Surveys',
    'dimensions': {'country': 'BEN',
     'frequency': 'A',
     'indicator': 'IC.FRM.BRIB.GRAFT2'},
    'indexed_at': '2022-07-01T19:18:23.311Z',
    'provider_code': 'WB',
    'series_code': 'A-IC.FRM.BRIB.GRAFT2-BEN',
    'series_name': 'Annual – Bribery depth (% of public transactions where a gift or informal payment was requested) – Benin'},
   {'dataset_code': 'ESY',
    'dataset_name': 'Enterprise Surveys',
    'dimensions': {'country': 'BFA',
     'frequency': 'A',
     'indicator': 'IC.FRM.BRIB.GRAFT2'},
    'indexed_at': '2022-07-01T19:18:23.311Z',
    'provider_code': 'WB',
    'series_code': 'A-IC.FRM.BRIB.GRAFT2-BFA',
    'series_name': 'Annual – Bribery depth (% of public transactions where a gift or informal payment was requested) – Burkina Faso'},
   {'dataset_code': 'ESY',
    'dataset_name': 'Enterprise Surveys',
    'dimensions': {'country': 'BGD',
     'frequency': 'A',
     'indicator': 'IC.FRM.BRIB.GRAFT2'},
    'indexed_at': '2022-07-01T19:18:23.311Z',
    'provider_code': 'WB',
    'series_code': 'A-IC.FRM.BRIB.GRAFT2-BGD',
    'series_name': 'Annual – Bribery depth (% of public transactions where a gift or informal payment was requested) – Bangladesh'},
   {'dataset_code': 'ESY',
    'dataset_name': 'Enterprise Surveys',
    'dimensions': {'country': 'BGR',
     'frequency': 'A',
     'indicator': 'IC.FRM.BRIB.GRAFT2'},

In [610]:
d = r.json()
d.keys()

dict_keys(['_meta', 'dataset', 'errors', 'provider', 'series'])

In [611]:
d['series']

{'docs': [{'dataset_code': 'ESY',
   'dataset_name': 'Enterprise Surveys',
   'dimensions': {'country': 'CHN',
    'frequency': 'A',
    'indicator': 'IC.FRM.BRIB.GRAFT2'},
   'indexed_at': '2022-07-01T19:18:23.311Z',
   'provider_code': 'WB',
   'series_code': 'A-IC.FRM.BRIB.GRAFT2-CHN',
   'series_name': 'Annual – Bribery depth (% of public transactions where a gift or informal payment was requested) – China'}],
 'limit': 1000,
 'num_found': 1,
 'offset': 0}

In [612]:
d['dataset'].keys()

dict_keys(['code', 'dimensions_codes_order', 'dimensions_values_labels', 'dir_hash', 'indexed_at', 'name', 'nb_series', 'provider_code', 'provider_name'])

In [613]:
d['dataset']['dimensions_values_labels'].keys()

dict_keys(['country', 'frequency', 'indicator'])

In [615]:
d['dataset']['dimensions_values_labels']

{'country': {'AFG': 'Afghanistan',
  'AGO': 'Angola',
  'ALB': 'Albania',
  'ARG': 'Argentina',
  'ARM': 'Armenia',
  'ATG': 'Antigua and Barbuda',
  'AZE': 'Azerbaijan',
  'BDI': 'Burundi',
  'BEL': 'Belgium',
  'BEN': 'Benin',
  'BFA': 'Burkina Faso',
  'BGD': 'Bangladesh',
  'BGR': 'Bulgaria',
  'BHS': 'Bahamas, The',
  'BIH': 'Bosnia and Herzegovina',
  'BLR': 'Belarus',
  'BLZ': 'Belize',
  'BOL': 'Bolivia',
  'BRA': 'Brazil',
  'BRB': 'Barbados',
  'BTN': 'Bhutan',
  'BWA': 'Botswana',
  'CAF': 'Central African Republic',
  'CHL': 'Chile',
  'CHN': 'China',
  'CIV': "Cote d'Ivoire",
  'CMR': 'Cameroon',
  'COD': 'Congo, Dem. Rep.',
  'COG': 'Congo, Rep.',
  'COL': 'Colombia',
  'CPV': 'Cabo Verde',
  'CRI': 'Costa Rica',
  'CYP': 'Cyprus',
  'CZE': 'Czech Republic',
  'DJI': 'Djibouti',
  'DMA': 'Dominica',
  'DOM': 'Dominican Republic',
  'ECU': 'Ecuador',
  'EGY': 'Egypt, Arab Rep.',
  'ERI': 'Eritrea',
  'EST': 'Estonia',
  'ETH': 'Ethiopia',
  'FJI': 'Fiji',
  'FSM': 'Micronesia, Fed. Sts.',
  'GAB': 'Gabon',
  'GEO': 'Georgia',
  'GHA': 'Ghana',
  'GIN': 'Guinea',
  'GMB': 'Gambia, The',
  'GNB': 'Guinea-Bissau',
  'GRC': 'Greece',
  'GRD': 'Grenada',
  'GTM': 'Guatemala',
  'GUY': 'Guyana',
  'HND': 'Honduras',
  'HRV': 'Croatia',
  'HUN': 'Hungary',
  'IDN': 'Indonesia',
  'IND': 'India',
  'IRQ': 'Iraq',
  'ISR': 'Israel',
  'ITA': 'Italy',
  'JAM': 'Jamaica',
  'JOR': 'Jordan',
  'KAZ': 'Kazakhstan',
  'KEN': 'Kenya',
  'KGZ': 'Kyrgyz Republic',
  'KHM': 'Cambodia',
  'KNA': 'St. Kitts and Nevis',
  'LAO': 'Lao PDR',
  'LBN': 'Lebanon',
  'LBR': 'Liberia',
  'LCA': 'St. Lucia',
  'LKA': 'Sri Lanka',
  'LSO': 'Lesotho',
  'LTU': 'Lithuania',
  'LUX': 'Luxembourg',
  'LVA': 'Latvia',
  'MAR': 'Morocco',
  'MDA': 'Moldova',
  'MDG': 'Madagascar',
  'MEX': 'Mexico',
  'MKD': 'North Macedonia',
  'MLI': 'Mali',
  'MLT': 'Malta',
  'MMR': 'Myanmar',
  'MNE': 'Montenegro',
  'MNG': 'Mongolia',
  'MOZ': 'Mozambique',
  'MRT': 'Mauritania',
  'MUS': 'Mauritius',
  'MWI': 'Malawi',
  'MYS': 'Malaysia',
  'NAM': 'Namibia',
  'NER': 'Niger',
  'NGA': 'Nigeria',
  'NIC': 'Nicaragua',
  'NPL': 'Nepal',
  'PAK': 'Pakistan',
  'PAN': 'Panama',
  'PER': 'Peru',
  'PHL': 'Philippines',
  'PNG': 'Papua New Guinea',
  'POL': 'Poland',
  'PRT': 'Portugal',
  'PRY': 'Paraguay',
  'PSE': 'West Bank and Gaza',
  'ROU': 'Romania',
  'RUS': 'Russian Federation',
  'RWA': 'Rwanda',
  'SDN': 'Sudan',
  'SEN': 'Senegal',
  'SLB': 'Solomon Islands',
  'SLE': 'Sierra Leone',
  'SLV': 'El Salvador',
  'SRB': 'Serbia',
  'SSD': 'South Sudan',
  'SUR': 'Suriname',
  'SVK': 'Slovak Republic',
  'SVN': 'Slovenia',
  'SWE': 'Sweden',
  'SWZ': 'Eswatini',
  'TCD': 'Chad',
  'TGO': 'Togo',
  'THA': 'Thailand',
  'TJK': 'Tajikistan',
  'TLS': 'Timor-Leste',
  'TON': 'Tonga',
  'TTO': 'Trinidad and Tobago',
  'TUN': 'Tunisia',
  'TUR': 'Turkey',
  'TZA': 'Tanzania',
  'UGA': 'Uganda',
  'UKR': 'Ukraine',
  'URY': 'Uruguay',
  'UZB': 'Uzbekistan',
  'VCT': 'St. Vincent and the Grenadines',
  'VEN': 'Venezuela, RB',
  'VNM': 'Vietnam',
  'VUT': 'Vanuatu',
  'WSM': 'Samoa',
  'XKX': 'Kosovo',
  'YEM': 'Yemen, Rep.',
  'ZAF': 'South Africa',
  'ZMB': 'Zambia',
  'ZWE': 'Zimbabwe'},
 'frequency': {'A': 'Annual'},
 'indicator': {'IC.FRM.BRIB.GRAFT2': 'Bribery depth (% of public transactions where a gift or informal payment was requested)',
  'IC.FRM.BRIB.GRAFT3': 'Bribery incidence (percent of firms experiencing at least one bribe payment request)',
  'IC.FRM.CORR.CORR1': 'Percent of firms expected to give gifts in meetings with tax officials',
  'IC.FRM.CORR.CORR10': 'Percent of firms expected to give gifts to get an operating license',
  'IC.FRM.CORR.CORR11': 'Percent of firms identifying corruption as a major constraint',
  'IC.FRM.CORR.CORR2': 'Percent of firms expected to give gifts to secure government contract',
  'IC.FRM.CORR.CORR3': 'Value of gift expected to secure a government contract (% of contract value)',
  'IC.FRM.CORR.CORR4': 'Percent of firms expected to give gifts to public officials "to get things done"',
  'IC.FRM.CORR.CORR6': 'Percent of firms expected to give gifts to get an electrical connection',
  'IC.FRM.CORR.CORR7': 'Percent of firms expected to give gifts to get a water connection',
  'IC.FRM.CORR.CORR8': 'Percent of firms expected to give gifts to get a construction permit',
  'IC.FRM.CORR.CORR9': 'Percent of firms expected to give gifts to get an import license',
  'IC.FRM.CORR.CRIME9': 'Percent of firms identifying the courts system as a major constraint',
  'IC.FRM.CRM.CRIME1': 'Percent of firms paying for security',
  'IC.FRM.CRM.CRIME10': 'Percent of firms experiencing losses due to theft and vandalism',
  'IC.FRM.CRM.CRIME2_C': 'If the establishment pays for security, average security costs (% of annual sales)',
  'IC.FRM.CRM.CRIME3_C': 'If there were losses, average losses due to theft and vandalism (% of annual sales)',
  'IC.FRM.CRM.CRIME5': 'Products shipped to supply domestic markets that were lost due to theft (% of product value)',
  'IC.FRM.CRM.CRIME8': 'Percent of firms identifying crime, theft and disorder as a major constraint',
  'IC.FRM.EMP.GROW.PEFT2': 'Annual employment growth (%)',
  'IC.FRM.FCHAR.CAR1': 'Age of the establishment (years)',
  'IC.FRM.FCHAR.CAR2': 'Proportion of private domestic ownership in a firm (%)',
  'IC.FRM.FCHAR.CAR7': 'Percent of firms with at least 10% of foreign ownership',
  'IC.FRM.FCHAR.CAR8': 'Percent of firms with at least 10% of government/state ownership',
  'IC.FRM.FCHAR.LFORM3': 'Percent of firms with legal status of Sole Proprietorship',
  'IC.FRM.FIAS.PEFT4': 'Percent of firms buying fixed assets',
  'IC.FRM.FIN.FIN1': 'Proportion of investment financed internally (%)',
  'IC.FRM.FIN.FIN10': 'Value of collateral needed for a loan (% of the loan amount)',
  'IC.FRM.FIN.FIN11': 'Proportion of loans requiring collateral (%)',
  'IC.FRM.FIN.FIN12': 'Percent of firms using banks to finance investments',
  'IC.FRM.FIN.FIN13': 'Percent of firms using banks to finance working capital',
  'IC.FRM.FIN.FIN14': 'Percent of firms with a bank loan/line of credit',
  'IC.FRM.FIN.FIN15': 'Percent of firms with a checking or savings account',
  'IC.FRM.FIN.FIN16': 'Percent of firms identifying access to finance as a major constraint',
  'IC.FRM.FIN.FIN2': 'Proportion of investment financed by banks (%)',
  'IC.FRM.FIN.FIN20': 'Percent of firms not needing a loan',
  'IC.FRM.FIN.FIN21': 'Percent of firms whose recent loan application was rejected',
  'IC.FRM.FIN.FIN22': 'Percent of firms using supplier/customer credit to finance working capital',
  'IC.FRM.FIN.FIN7': 'Proportion of working capital financed by banks (%)',
  'IC.FRM.GEN.GEND1': 'Percent of firms with female participation in ownership',
  'IC.FRM.GEN.GEND2': 'Proportion of permanent full-time workers that are female (%)',
  'IC.FRM.GEN.GEND3': 'Proportion of permanent full-time non-production workers that are female (%)',
  'IC.FRM.GEN.GEND4': 'Percent of firms with a female top manager',
  'IC.FRM.GEN.GEND5': 'Proportion of permanent full-time production workers that are female (%)',
  'IC.FRM.GEN.GEND6': 'Percent of firms with majority female ownership',
  'IC.FRM.INFOR.INFOR1': 'Percent of firms competing against unregistered or informal firms',
  'IC.FRM.INFOR.INFOR2': 'Percent of firms identifying practices of competitors in the informal sector as a major constraint',
  'IC.FRM.INFOR.INFOR4': 'Percent of firms formally registered when they started operations in the country',
  'IC.FRM.INFOR.INFOR5': 'Number of years firm operated without formal registration',
  'IC.FRM.INFRA.IN1': 'Days to obtain an electrical connection (upon application)',
  'IC.FRM.INFRA.IN10_C': 'If a generator is used, average proportion of electricity from a generator (%)',
  'IC.FRM.INFRA.IN11': 'Percent of firms identifying transportation as a major constraint',
  'IC.FRM.INFRA.IN12': 'Percent of firms identifying electricity as a major constraint',
  'IC.FRM.INFRA.IN14': 'Proportion of products lost to breakage or spoilage during shipping to domestic markets (%)',
  'IC.FRM.INFRA.IN16': 'Percent of firms experiencing electrical outages',
  'IC.FRM.INFRA.IN17': 'Percent of firms experiencing water insufficiencies',
  'IC.FRM.INFRA.IN2': 'Number of electrical outages in a typical month',
  'IC.FRM.INFRA.IN3_C': 'If there were outages, average duration of a typical electrical outage (hours)',
  'IC.FRM.INFRA.IN4_C': 'If there were outages, average losses due to electrical outages (% of annual sales)',
  'IC.FRM.INFRA.IN6': 'Number of water insufficiencies in a typical month',
  'IC.FRM.INFRA.IN9': 'Percent of firms owning or sharing a generator',
  'IC.FRM.INNOV.T1': 'Percent of firms with an internationally-recognized quality certification',
  'IC.FRM.INNOV.T10': 'Percent of firms that spend on R&D',
  'IC.FRM.INNOV.T2': 'Percent of firms with an annual financial statement reviewed by external auditors',
  'IC.FRM.INNOV.T3': 'Capacity utilization (%)',
  'IC.FRM.INNOV.T4': 'Percent of firms using technology licensed from foreign companies',
  'IC.FRM.INNOV.T5': 'Percent of firms having their own Web site',
  'IC.FRM.INNOV.T6': 'Percent of firms using e-mail to interact with clients/suppliers',
  'IC.FRM.INNOV.T7': 'Percent of firms that introduced a new product/service',
  'IC.FRM.INNOV.T8': 'Percent of firms whose new product/service is also new to the main market',
  'IC.FRM.INNOV.T9': 'Percent of firms that introduced a process innovation',
  'IC.FRM.OBS.OBST1': 'Percent of firms choosing access to finance as their biggest obstacle',
  'IC.FRM.OBS.OBST10': 'Percent of firms choosing labor regulations as their biggest obstacle',
  'IC.FRM.OBS.OBST11': 'Percent of firms choosing political instability as their biggest obstacle',
  'IC.FRM.OBS.OBST12': 'Percent of firms choosing practices of the informal sector as their biggest obstacle',
  'IC.FRM.OBS.OBST13': 'Percent of firms choosing tax administration as their biggest obstacle',
  'IC.FRM.OBS.OBST14': 'Percent of firms choosing tax rates as their biggest obstacle',
  'IC.FRM.OBS.OBST15': 'Percent of firms choosing transportation as their biggest obstacle',
  'IC.FRM.OBS.OBST2': 'Percent of firms choosing access to land as their biggest obstacle',
  'IC.FRM.OBS.OBST3': 'Percent of firms choosing business licensing and permits as their biggest obstacle',
  'IC.FRM.OBS.OBST4': 'Percent of firms choosing corruption as their biggest obstacle',
  'IC.FRM.OBS.OBST5': 'Percent of firms choosing courts as their biggest obstacle',
  'IC.FRM.OBS.OBST6': 'Percent of firms choosing crime, theft and disorder as their biggest obstacle',
  'IC.FRM.OBS.OBST7': 'Percent of firms choosing customs and trade regulations as their biggest obstacle',
  'IC.FRM.OBS.OBST8': 'Percent of firms choosing electricity as their biggest obstacle',
  'IC.FRM.OBS.OBST9': 'Percent of firms choosing inadequately educated workforce as their biggest obstacle',
  'IC.FRM.PROD.GROW.PEFT3': 'Real annual labor productivity growth (%)',
  'IC.FRM.REG.BUS1': 'Days to obtain an import license',
  'IC.FRM.REG.BUS2': 'Days to obtain an operating license',
  'IC.FRM.REG.BUS3': 'Days to obtain a construction-related permit',
  'IC.FRM.REG.BUS5': 'Percent of firms identifying business licensing and permits as a major constraint',
  'IC.FRM.REG.REG1': 'Senior management time spent dealing with the requirements of government regulation (%)',
  'IC.FRM.REG.REG2_C': 'If there were visits, average number of visits or required meetings with tax officials',
  'IC.FRM.REG.REG4': 'Percent of firms identifying tax rates as a major constraint',
  'IC.FRM.REG.REG5': 'Percent of firms identifying tax administration as a major constraint',
  'IC.FRM.REG.REG6': 'Percent of firms visited or required to meet with tax officials',
  'IC.FRM.SLS.GROW.PEFT1': 'Real annual sales growth (%)',
  'IC.FRM.TRD.TR1': 'Days to clear direct exports through customs',
  'IC.FRM.TRD.TR11': 'Percent of firms using material inputs and/or supplies of foreign origin',
  'IC.FRM.TRD.TR16': 'Percent of firms exporting directly (at least 10% of sales)',
  'IC.FRM.TRD.TR17': 'Percent of firms exporting directly or indirectly (at least 10% of sales)',
  'IC.FRM.TRD.TR2': 'Days to clear imports from customs',
  'IC.FRM.TRD.TR5': 'Proportion of total sales that are exported directly (%)',
  'IC.FRM.TRD.TR8': 'Proportion of total inputs that are of foreign origin (%)',
  'IC.FRM.TRD.TR9': 'Percent of firms identifying customs and trade regulations as a major constraint',
  'IC.FRM.WRKF.WK1': 'Percent of firms offering formal training',
  'IC.FRM.WRKF.WK10': 'Percent of firms identifying an inadequately educated workforce as a major constraint',
  'IC.FRM.WRKF.WK14': 'Number of workers',
  'IC.FRM.WRKF.WK15': 'Proportion of production workers (out of all permanent workers)',
  'IC.FRM.WRKF.WK17': 'Proportion of temporary workers (out of all workers)',
  'IC.FRM.WRKF.WK18': 'Proportion of permanent workers (out of all workers)',
  'IC.FRM.WRKF.WK19': 'Proportion of skilled workers (out of all production workers) (%)',
  'IC.FRM.WRKF.WK2': 'Proportion of workers offered formal training (%)',
  'IC.FRM.WRKF.WK8': "Years of the top manager's experience working in the firm's sector",
  'IC.FRM.WRKF.WK9': 'Percent of firms identifying labor regulations as a major constraint'}}

## 1.3 Build Indicators Catalog

In [ ]:
from src.metadata import build_indicator_catalog

indicators_catalog = build_indicator_catalog.get_indicator_catalog(datasets_df, client)
indicators_catalog

In [ ]:
import sdmx

In [ ]:
IMF_DATA = sdmx.Client('IMF_DATA')

In [ ]:
IMF_DATA.data('CPI')

/Users/hippolytegrandet/Desktop/Dev/country_risk_rating/.venv/lib/python3.9/site-packages/sdmx/rest/common.py:367: UserWarning: 'agency_id' argument is redundant for data queries
  getattr(self, f"handle_{query_type}")()
xml.Reader got no structure=… argument for StructureSpecificData

KeyboardInterrupt:

In [ ]:
IMF_DATA.data

ValueError: can't determine a reader for response content type None

In [ ]:
data_msg = IMF_DATA.data('CPI', key='USA+CAN.CPI.CP01.IX.M', params={'startPeriod': 2018})
cpi_df = sdmx.to_pandas(data_msg)
cpi_df

xml.Reader got no structure=… argument for StructureSpecificData

TIME_PERIOD  INDEX_TYPE  COICOP_1999  TYPE_OF_TRANSFORMATION  COUNTRY  FREQUENCY  COMMON_REFERENCE_PERIOD  OVERLAP  SCALE  ACCESS_SHARING_LEVEL  SECURITY_CLASSIFICATION
2018-M01     CPI         CP01         IX                      CAN      M          2002A                    OL       0      PUBLIC_OPEN           PUB                        142.600000
2018-M02     CPI         CP01         IX                      CAN      M          2002A                    OL       0      PUBLIC_OPEN           PUB                        142.300000
2018-M03     CPI         CP01         IX                      CAN      M          2002A                    OL       0      PUBLIC_OPEN           PUB                        141.300000
2018-M04     CPI         CP01         IX                      CAN      M          2002A                    OL       0      PUBLIC_OPEN           PUB                        141.900000
2018-M05     CPI         CP01         IX                      CAN      M          2002A                    OL       0      PUBLIC_OPEN           PUB                        141.400000
                                                                                                                                                                               ...
2025-M06     CPI         CP01         IX                      USA      M          2010A                    OL       0      PUBLIC_OPEN           PUB                        145.143003
2025-M07     CPI         CP01         IX                      USA      M          2010A                    OL       0      PUBLIC_OPEN           PUB                        145.251977
2025-M08     CPI         CP01         IX                      USA      M          2010A                    OL       0      PUBLIC_OPEN           PUB                        145.875600
2025-M09     CPI         CP01         IX                      USA      M          2010A                    OL       0      PUBLIC_OPEN           PUB                        146.540493
2025-M11     CPI         CP01         IX                      USA      M          2010A                    OL       0      PUBLIC_OPEN           PUB                        145.572400
Name: value, Length: 189, dtype: float64

In [ ]:
from extraction import world_bank
client = world_bank.DBnomicsClient()

In [ ]:
BIS_datasets = client.list_datasets("BIS")

In [ ]:
provider_info = {}
provider_info[datasets['provider']['code']] = BIS_datasets['provider']['region'] + ' Region. ' + BIS_datasets['provider']['name']
provider_info

{'BIS': 'World Region. Bank for International Settlements'}

In [ ]:
BIS_datasets.keys()

dict_keys(['_meta', 'category_tree', 'provider'])

In [ ]:
datasets_BIS = {}

def get_datasets_pairs(l):
    datsets_descriptions = {}

    subname = ''
    for e in l:
        print(e['name'])
        subname = e['name']
        subsubname = ''
        for f in e['children']:
            subsubname = f['name']
            subsubsubname = ''
            for g in f['children']:
                subsubsubname = g['name']
                code = g['code']

                datsets_descriptions[code] = subname + subsubname + subsubsubname

    return datsets_descriptions

datasets_BIS_mapping = get_datasets_pairs(BIS_datasets['category_tree'])
datasets_BIS_mapping

BISWEB_CATSCHEME

Dataportal Category Scheme

{'WS_LBS_D_PUB': 'Dataportal Category Scheme\n        International banking\n          BIS locational banking',
 'WS_CBS_PUB': 'Dataportal Category Scheme\n        International banking\n          BIS consolidated banking',
 'WS_DEBT_SEC2_PUB': 'Dataportal Category Scheme\n        Debt securities\n          BIS international debt securities (BIS-compiled)',
 'WS_OTC_DERIV2': 'Dataportal Category Scheme\n        Derivatives\n          OTC derivatives outstanding',
 'WS_DER_OTC_TOV': 'Dataportal Category Scheme\n        Derivatives\n          OTC derivatives turnover',
 'WS_XTD_DERIV': 'Dataportal Category Scheme\n        Derivatives\n          Exchange traded derivatives',
 'WS_GLI': 'Dataportal Category Scheme\n        Global liquidity\n          Global liquidity indicators',
 'WS_TC': 'Dataportal Category Scheme\n        Credit\n          BIS long series on total credit',
 'WS_CREDIT_GAP': 'Dataportal Category Scheme\n        Credit\n          BIS credit-to-GDP gaps',
 'WS_DSR': 'Dataportal Category Scheme\n        Credit\n          BIS debt service ratio',
 'WS_SPP': 'Dataportal Category Scheme\n        Property prices\n          Selected residential property prices',
 'WS_LONG_CPI': 'Dataportal Category Scheme\n        Consumer prices\n          BIS long consumer prices',
 'WS_XRU': 'Dataportal Category Scheme\n        Exchange rates\n          US dollar exchange rates',
 'LBS': 'Dataportal Category Scheme\n        International banking\n          Locational banking statistics\n            ',
 'CBS': 'Dataportal Category Scheme\n        International banking\n          Consolidated banking statistics\n            ',
 'DSS': 'Dataportal Category Scheme\n        Debt securities\n          Debt securities statistics\n            ',
 'IDS': 'Dataportal Category Scheme\n        Debt securities\n          International debt securities (BIS-compiled)\n            ',
 'TOTAL_CREDIT': 'Dataportal Category Scheme\n        Credit\n          Credit to the non-financial sector\n            ',
 'CREDIT_GAPS': 'Dataportal Category Scheme\n        Credit\n          Credit-to-GDP gaps\n            ',
 'DSR': 'Dataportal Category Scheme\n        Credit\n          Debt service ratios\n            ',
 'XTD_DER': 'Dataportal Category Scheme\n        Derivatives\n          Exchange-traded derivatives statistics\n            ',
 'OTC_DER': 'Dataportal Category Scheme\n        Derivatives\n          OTC derivatives outstanding\n            ',
 'DER': 'Dataportal Category Scheme\n        Derivatives\n          Triennial Survey\n            ',
 'RPP': 'Dataportal Category Scheme\n        Property prices\n          Residential property prices\n            ',
 'CPP': 'Dataportal Category Scheme\n        Property prices\n          Commercial property prices\n            ',
 'XRU': 'Dataportal Category Scheme\n        Exchange rates\n          Bilateral exchange rates\n            ',
 'EER': 'Dataportal Category Scheme\n        Exchange rates\n          Effective exchange rates\n            ',
 'WS_EER': 'Dataportal Category Scheme\n        Exchange rates\n          BIS effective exchange rates',
 'WS_CBPOL': 'Dataportal Category Scheme\n        Policy rates\n          Policy rate',
 'CPMI_CT': 'Dataportal Category Scheme\n        Payment statistics\n          Retail payments, currency and related indicators\n            ',
 'CPMI_FMI': 'Dataportal Category Scheme\n        Payment statistics\n          Financial market infrastructures and critical service providers\n            ',
 'WS_CPMI_CT1': 'Dataportal Category Scheme\n        Payment statistics\n          CPMI comparative tables type 1',
 'WS_CPMI_CT2': 'Dataportal Category Scheme\n        Payment statistics\n          CPMI comparative tables type 2',
 'WS_CPMI_DEVICES': 'Dataportal Category Scheme\n        Payment statistics\n          CPMI payment devices (T4)',
 'WS_CPMI_CASHLESS': 'Dataportal Category Scheme\n        Payment statistics\n          CPMI cashless payments (T5,T6)',
 'WS_CPMI_INSTITUT': 'Dataportal Category Scheme\n        Payment statistics\n          CPMI institutions (T3)',
 'WS_CPMI_SYSTEMS': 'Dataportal Category Scheme\n        Payment statistics\n          CPMI systems (T8,T9,T11,T13,T14,T16,T17,T18,T19)',
 'WS_CPMI_MACRO': 'Dataportal Category Scheme\n        Payment statistics\n          CPMI macro (T1,T2)',
 'WS_CPMI_PARTICIP': 'Dataportal Category Scheme\n        Payment statistics\n          CPMI participants (T7,T10,T12,T15)',
 'CBTA': 'Dataportal Category Scheme\n        Central bank statistics\n          Central bank total assets\n            ',
 'CBPOL': 'Dataportal Category Scheme\n        Central bank statistics\n          Central bank policy rates\n            '}

In [ ]:
len(datasets_BIS_mapping)

41

In [ ]:
client.list_series('BIS', 'WS_CBTA')

{'_meta': {'args': {'align_periods': False,
   'dataset_code': 'WS_CBTA',
   'dimensions': {},
   'facets': False,
   'format': 'json',
   'limit': 1000,
   'metadata': True,
   'observations': False,
   'offset': 0,
   'provider_code': 'BIS',
   'q': '',
   'series_code': None},
  'version': '22.1.17'},
 'dataset': {'attributes_labels': {'BREAKS': 'Breaks',
   'COLLECTION': 'Collection Indicator',
   'COLLECTION_DETAIL': 'Collection explanation detail',
   'COMMENT_DSET': '',
   'COMMENT_TS': 'Series comment',
   'COMPILING_ORG': 'Compiling agency',
   'CONF_STATUS': 'Confidentiality - status',
   'DATA_COMP': 'Data compilation',
   'DECIMALS': 'Decimals',
   'DISS_ORG': 'Data dissemination agency',
   'FISCAL_YEAR': 'Fiscal year',
   'METHOD_REF': 'Methodology reference',
   'OBS_PRE_BREAK': 'Observation pre-break value',
   'OBS_STATUS': 'Observation status',
   'SUPP_INFO_BREAKS': 'Supplemental information and breaks',
   'TIME_FORMAT': 'Time format',
   'UNIT_MULT': 'Unit multiplier'},
  'attributes_values_labels': {'BREAKS': {'ADMIN': 'Administrative procedures',
    'CLASS': 'Classifications',
    'CONF': 'Confidentiality',
    'CUR': 'Currency',
    'DEF': 'Definition',
    'LEGAL': 'Legal basis',
    'METH': 'Methodologies',
    'NONSTAT': 'Non-statistical factors',
    'POL': 'Policy',
    'REF_PER': 'Reference period',
    'SAMPLE': 'Sample redesigned',
    'SCOPE': 'Revision of scope or coverage',
    'SOURCE': 'Data source',
    'STD': 'Standard(s)',
    'TRANSF': 'Data transformation',
    'UNIT': 'Statistical unit(s)',
    'VAL': 'Valuation methods',
    'WEIGHT': 'Base weight',
    '_O': 'Other',
    '_U': 'No data/unknown'},
   'COLLECTION': {'A': 'Average of observations through period',
    'B': 'Beginning of period',
    'E': 'End of period',
    'H': 'Highest in period',
    'L': 'Lowest in period',
    'M': 'Middle of period',
    'S': 'Summed through period',
    'U': 'Unknown',
    'V': 'Other',
    'Y': 'Annualised summed'},
   'CONF_STATUS': {'A': 'Primary confidentiality due to small counts',
    'C': 'Confidential statistical information',
    'D': 'Secondary confidentiality set by the sender, not for publication',
    'E': 'Not for publication, restricted for internal use only (equivalent to the code N) until the embargo time elapses; Free for publication (equivalent to the code F) after the embargo time elapses.',
    'F': 'Free (free for publication)',
    'G': 'Primary confidentiality due to dominance by one or two units',
    'M': 'Primary confidentiality due to data declared confidential based on other measures of concentration',
    'N': 'Not for publication, restricted for internal use only',
    'O': 'Primary confidentiality due to dominance by one unit',
    'S': 'Secondary confidentiality set and managed by the receiver, not for publication',
    'T': 'Primary confidentiality due to dominance by two units',
    'X': 'Confidentiality due to military secrecy'},
   'DECIMALS': {'0': 'Zero',
    '1': 'One',
    '10': 'Ten',
    '11': 'Eleven',
    '12': 'Twelve',
    '13': 'Thirteen',
    '14': 'Fourteen',
    '15': 'Fifteen',
    '16': 'Sixteen',
    '2': 'Two',
    '3': 'Three',
    '4': 'Four',
    '5': 'Five',
    '6': 'Six',
    '7': 'Seven',
    '8': 'Eight',
    '9': 'Nine'},
   'DISS_ORG': {'1A0': 'International organisations',
    '1B0': 'UN organisations',
    '1C0': 'IMF (International Monetary Fund)',
    '1D0': 'World Trade Organisation',
    '1E0': 'International Bank for Reconstruction and Development',
    '1F0': 'International Development Association',
    '1G0': 'ICSID (International Centre for Settlement of Investment Disputes)',
    '1H0': 'UNESCO (United Nations Educational, Scientific and Cultural Organisation)',
    '1J0': 'FAO (Food and Agriculture Organisation)',
    '1K0': 'WHO (World Health Organisation)',
    '1L0': 'IFAD (International Fund for Agricultural Development)',
    '1M0': 'IFC (International Finance Corporation)',
    '1N0': 'MIGA (Multilateral Investment Guarantee Agency)',
    '1O0': 'UNICEF (United Nations Children Fund)',
    '1P0': 'UNHCR (United Nations High Commissioner for Refugees)',
    '1Q0': 'UNRWA (United Nations Relief and Works Agency for Palestine)',
    '1R0': 'IAEA (International Atomic Energy Agency)',
    '1S0': 'ILO (International Labour Organisation)',
    '1T0': 'ITU (International Telecommunication Union)',
    '1U0': 'Rest of\xa0UN Organisations\xa0n.i.e.',
    '1V0': 'Universal Postal Union',
    '1X0': 'United Nations Office on Drugs and Crimes(UNODC)',
    '1Y0': 'The United Nations World Food Programme',
    '4A0': 'All the European Union Institutions excluding the ECB and ESM  deprecated',
    '4C0': 'EIB (European Investment Bank)',
    '4D0': 'European Commission (including Eurostat)',
    '4D1': 'Statistical Office of the European Commission (Eurostat)',
    '4E0': 'EDF (European Development Fund)',
    '4F0': 'ECB (European Central Bank)',
    '4G0': 'EIF (European Investment Fund)',
    '4H0': 'European Community of Steel and Coal deprecated',
    '4J0': 'Other EC Institutions, Organs and Organisms covered by General budget deprecated',
    '4J10': 'European Parliament',
    '4J20': 'Council of the European Union',
    '4J30': 'Court of Justice',
    '4J40': 'Court of Auditors',
    '4J50': 'European Council',
    '4J60': 'Economic and Social Committee',
    '4J70': 'Committee of Regions',
    '4J80': 'Other European Community Institutions, Organs and Organisms deprecated',
    '4J810': 'Agency for the Cooperation of Energy Regulators',
    '4J8100': 'European Centre for Disease Prevention and Control',
    '4J8110': 'European Centre for the Development of Vocational Training',
    '4J8120': 'European Chemicals Agency',
    '4J8130': 'European Data Protection Supervisor',
    '4J8140': 'European Defence Agency',
    '4J8150': 'European Environment Agency',
    '4J8160': 'European External Action Service',
    '4J8170': 'European Fisheries Control Agency',
    '4J8180': 'European Food Safety Authority',
    '4J8190': 'European Foundation for the Improvement of Living and Working Conditions',
    '4J820': 'Body of European Regulators for Electronic Communications',
    '4J8200': 'European GNSS Agency',
    '4J8210': 'European Institute for Gender Equality',
    '4J8220': 'European Institute of Innovation and Technology',
    '4J8230': 'European Maritime Safety Agency',
    '4J8240': 'European Medicines Agency',
    '4J8250': 'European Monitoring Centre for Drugs and Drug Addiction',
    '4J8260': 'European Network and Information Security Agency',
    '4J8270': 'European Ombudsman',
    '4J8280': 'European Personnel Selection Office',
    '4J8290': 'European Police College',
    '4J830': 'Community Plant Variety Office',
    '4J8300': 'European Police Office',
    '4J8310': "European Public Prosecutor's Office",
    '4J8320': 'European Railway Agency',
    '4J8330': 'European School of Administration',
    '4J8340': 'European Training Foundation',
    '4J8350': 'European Union Agency for Fundamental Rights',
    '4J8360': 'European Union Institute for Security Studies',
    '4J8370': 'European Union Intellectual Property Office',
    '4J8380': 'European Union Satellite Centre',
    '4J8390': 'Publications Office of the European Union',
    '4J840': 'Computer Emergency Response Team',
    '4J8400': 'The European Union’s Judicial Cooperation Unit',
    '4J8410': 'Translation Centre for the Bodies of the European Union',
    '4J8420': 'ATHENA Mechanism',
    '4J850': 'European Agency for Safety and Health at Work',
    '4J860': 'European Agency for the Management of Operational Cooperation at the External Borders',
    '4J870': 'European Agency for the operational management of large-scale IT systems in the area of freedom, security and justice',
    '4J880': 'European Asylum Support Office',
    '4J890': 'European Aviation Safety Agency',
    '4M0': 'SRB (Single Resolution Board)',
    '4S0': 'ESM (European Stability Mechanism)',
    '4T0': 'Joint Committee of the European Supervisory Authorities (ESAs)',
    '4T10': 'EBA (European Banking Authority)',
    '4T20': 'ESMA (European Securities and Markets Authority)',
    '4T30': 'EIOPA (European Insurance and Occupational Pensions Authority)',
    '4U10': 'Fusion for Energy',
    '4U20': 'EURATOM Supply Agency',
    '4W0': 'EFSF (European Financial Stability Facility)',
    '4Y0': 'All the European Union Institutions including the ECB and ESM deprecated',
    '5B0': 'BIS (Bank for International Settlements)',
    '5C0': 'IADB (Inter-American Development Bank)',
    '5D0': 'AfDB (African Development Bank)',
    '5E0': 'AsDB (Asian Development Bank)',
    '5F0': 'EBRD (European Bank for Reconstruction and Development)',
    '5G0': 'IIC (Inter-American Investment Corporation)',
    '5H0': 'NIB (Nordic Investment Bank)',
    '5I0': 'ECCB (Eastern Caribbean Central Bank)',
    '5J0': 'IBEC (International Bank for Economic Co-operation)',
    '5K0': 'IIB (International Investment Bank)',
    '5L0': 'CDB (Caribbean Development Bank)',
    '5M0': 'AMF (Arab Monetary Fund)',
    '5N0': 'BADEA (Banque arabe pour le développement économique en Afrique)',
    '5O0': 'BCEAO (Banque Centrale des États de l’Afrique de l’Ouest)',
    '5P0': 'CASDB (Central African States Development Bank)',
    '5Q0': 'African Development Fund',
    '5R0': 'Asian Development Fund',
    '5S0': 'Fonds spécial unifié de développement',
    '5T0': 'CABEI (Central American Bank for Economic Integration)',
    '5U0': 'ADC (Andean Development Corporation)',
    '5W0': 'BEAC (Banque des Etats de l`Afrique Centrale)',
    '5X0': 'CEMAC (Communauté Économique et Monétaire de l’Afrique Centrale)',
    '5Y0': 'ECCU (Eastern Caribbean Currency Union)',
    '5Z0': 'Other International Financial Organisations n.i.e.',
    '5Z10': 'Africa Finance Corporation',
    '5Z100': 'International Civil Aviation Organization',
    '5Z110': 'International Cocoa Organization',
    '5Z120': 'International Coffee Organization',
    '5Z130': 'International Copper Study Group',
    '5Z140': 'International Cotton Advisory Committee',
    '5Z150': 'International Grains Council',
    '5Z160': 'International Jute Study Group',
    '5Z170': 'International Lead and Zinc Study Group',
    '5Z180': 'International Maritime Organization',
    '5Z190': 'International Maritime Satellite Organization',
    '5Z20': 'African Development Bank Group',
    '5Z200': 'International Olive Oil Council',
    '5Z210': 'International Rubber Study Group',
    '5Z220': 'International Sugar Organization',
    '5Z230': 'Latin American and the Caribbean Economic System',
    '5Z240': 'Latin American Energy Organization',
    '5Z250': 'Latin American Integration Association',
    '5Z260': 'League of Arab States',
    '5Z270': 'Organisation of Eastern Caribbean States',
    '5Z280': 'Organization of American States',
    '5Z290': 'Organization of Arab Petroleum Exporting Countries',
    '5Z30': 'Arab Fund for Economic and Social Development',
    '5Z300': 'Organization of Central American States',
    '5Z310': 'Organization of the Petroleum Exporting Countries',
    '5Z330': 'South Asian Association for Regional Cooperation',
    '5Z340': 'United Nations Conference on Trade and Development',
    '5Z350': 'West African Economic Community',
    '5Z360': 'West African Health Organisation',
    '5Z370': 'West African Monetary Agency',
    '5Z380': 'West African Monetary Institute',
    '5Z390': 'World Council of Churches',
    '5Z40': 'Asian Clearing Union',
    '5Z400': 'World Intellectual Property Organization',
    '5Z410': 'World Meteorological Organization',
    '5Z420': 'World Tourism Organization',
    '5Z50': 'Colombo Plan',
    '5Z60': 'Economic Community of West African States',
    '5Z70': 'European Free Trade Association',
    '5Z80': 'Fusion for Energy deprecated',
    '5Z90': 'Intergovernmental Council of Copper Exporting Countries',
    '5z30': 'Arab Fund for Economic and Social Development (deprecated)',
    '6A0': 'Other International Organisations (non-financial institutions)',
    '6A10': 'African Union',
    '6A20': 'Association of Southeast Asian Nations',
    '6A30': 'Caribbean Community and Common Market',
    '6A40': 'Central American Common Market',
    '6A50': 'East African Development Bank',
    '6A60': 'ECOWAS Bank for Investment and Development',
    '6A70': 'Latin American Association of Development Financing Institutions',
    '6A80': 'OPEC Fund for International Development',
    '6B0': 'NATO (North Atlantic Treaty Organisation)',
    '6C0': 'Council of Europe',
    '6D0': 'ICRC (International Committee of the Red Cross)',
    '6E0': 'ESA (European Space Agency)',
    '6F0': 'EPO (European Patent Office)',
    '6G0': 'EUROCONTROL (European Organisation for the Safety of Air Navigation)',
    '6H0': 'EUTELSAT (European Telecommunications Satellite Organisation)',
    '6I0': 'EMBL (European Molecular Biology Laboratory)',
    '6J0': 'INTELSAT (International Telecommunications Satellite Organisation)',
    '6K0': 'EBU/UER (European Broadcasting Union/Union européenne de radio-télévision)',
    '6L0': 'EUMETSAT (European Organisation for the Exploitation of Meteorological Satellites)',
    '6M0': 'ESO (European Southern Observatory)',
    '6N0': 'ECMWF (European Centre for Medium-Range Weather Forecasts)',
    '6O0': 'OECD (Organisation for Economic Co-operation and Development)',
    '6P0': 'CERN (European Organisation for Nuclear Research)',
    '6Q0': 'IOM (International Organisation for Migration)',
    '6Z0': 'Other International Non-Financial Organisations n.i.e.',
    '6Z10': 'The Global Fund to Fight AIDS, Tuberculosis and Malaria',
    '6Z20': 'International Centre for Migration Policy Development',
    '7A0': 'WAEMU (West African Economic and Monetary Union)',
    '7B0': 'IDB (Islamic Development Bank)',
    '7C0': 'EDB (Eurasian Development Bank )',
    '7D0': 'Paris Club Creditor Institutions',
    '7E0': 'CEB (Council of Europe Development Bank)',
    '7F0': 'International Union of Credit and Investment Insurers',
    '7G0': 'Black Sea Trade and Development Banks',
    '7H0': 'AFREXIMBANK (African Export-Import Bank)',
    '7I0': 'BLADEX (Banco Latino Americano De Comercio Exterior)',
    '7J0': 'FLAR (Fondo Latino Americano de Reservas)',
    '7K0': "Fonds Belgo-Congolais d'Amortissement et de Gestion",
    '7L0': 'IFFIm (International finance Facility for Immunisation)',
    '7M0': 'EUROFIMA (European Company for the Financing of Railroad Rolling Stock)',
    '7N0': 'Development Bank of Latin America (Banco de Desarrollo de America Latina)',
    '7O0': 'The Eastern and Southern African Trade and Development Bank',
    '9A0': 'International Organisations excl. European Community Institutions (4Y)',
    'AD2': 'Andorra Finance institute',
    'AE1': 'Central Statistical Organization, part of the Ministry of Economy and Planning (United Arab Emirates)',
    'AE2': 'Central Bank of the United Arab Emirates',
    'AE4': 'Ministry of Finance and Industry (United Arab Emirates)',
    'AE_DU6': 'Dubai Financial Services Authority',
    'AF2': 'Da Afghanistan Bank',
    'AF4': 'Ministry of Finance (Afghanistan, Islamic State of)',
    'AG2': 'Eastern Caribbean Central Bank (ECCB) (Antigua and Barbuda)',
    'AG4': 'Ministry of Finance (Antigua and Barbuda)',
    'AI1': 'Central Statistical Office (Anguilla)',
    'AI4': 'Ministry of Finance (Anguilla)',
    'AI99': 'Other competent National Authority (Anguilla)',
    'AL1': 'Institute of Statistics (Albania)',
    'AL2': 'Bank of Albania',
    'AL4': 'Ministère des Finances (Albania)',
    'AM1': 'National Statistics Service (Armenia)',
    'AM2': 'Central Bank of Armenia',
    'AM4': 'Ministry of Finance and Economy (Armenia)',
    'AM99': 'Other competent National Authority (Armenia, Republic of)',
    'AN1': 'Central Bureau of Statistics (Netherlands Antilles)',
    'AN2': 'Bank of the Netherlands Antilles',
    'AN99': 'Other competent National Authority (Netherlands Antilles)',
    'AO1': 'National Institute of Statistics (Angola)',
    'AO2': 'Banco Nacional de Angola',
    'AO4': 'Ministério das Finanças (Angola)',
    'AR1': 'Instituto Nacional de Estadistica y Censos (Argentina)',
    'AR2': 'Banco Central de la Republica Argentina',
    'AR4': 'Ministerio de Economía (Argentina)',
    'AR99': 'Other competent National Authority (Argentina)',
    'AT1': 'Statistik Österreich (Austria)',
    'AT2': 'Oesterreichische Nationalbank (Austria)',
    'AT6': 'FMA (Austria Financial Market Authority)',
    'AT99': 'Other competent National Authority (Austria)',
    'AU1': 'Australian Bureau of Statistics',
    'AU2': 'Reserve Bank of Australia',
    'AU5': 'Department of the Treasury (Australia)',
    'AU99': 'Other competent National Authority (Australia)',
    'AW1': 'Central Bureau of Statistics (Aruba)',
    'AW2': 'Centrale Bank van Aruba',
    'AW99': 'Other competent National Authority (Aruba)',
    'AZ1': 'State Statistical Committee of the Republic of Azerbaijan',
    'AZ2': 'National Bank of Azerbaijan',
    'AZ4': 'Ministry of Finance (Azerbaijan)',
    'AZ99': 'Other competent National Authority (Azerbaijan, Republic of)',
    'B22': 'EU 15 central banks',
    'B32': 'EU 25 central banks',
    'B42': 'EU 27 central banks',
    'B52': 'EU 28 central banks',
    'B62': 'EU27 central banks (fixed composition) as of 31 January 2020 (brexit)',
    'BA1': 'Institute of Statistics (Bosnia and Herzegovina)',
    'BA2': 'Central Bank of Bosnia and Herzegovina',
    'BA4': 'Bosnia and Herzegovina Ministry of Finance and Treasury',
    'BA99': 'Other competent National Authority (Bosnia and Herzegovina)',
    'BB1': 'Barbados Statistical Service',
    'BB2': 'Central Bank of Barbados',
    'BB4': 'Ministry of Finance and  Economic Affairs (Barbados)',
    'BB99': 'Other competent National Authority (Barbados)',
    'BD1': 'Bangladesh Bureau of Statistics',
    'BD2': 'Bangladesh Bank',
    'BD4': 'Ministry of Finance (Bangladesh)',
    'BE1': 'Institut National de Statistiques de Belgique',
    'BE2': 'Banque Nationale de Belgique (Belgium)',
    'BE3': 'Federal Public Service Finance (Belgium)',
    'BE40': 'Federal Planning Bureau',
    'BE9': 'Bureau van Dijk (Belgium)',
    'BE99': 'Other competent National Authority (Belgium)',
    'BF2': 'Banque Centrale des États de l’Afrique de l’Ouest (BCEAO) (Burkina Faso)',
    'BF4': "Ministere de l'Economie et des Finances  (Burkina Faso)",
    'BG1': 'National Statistical Institute of Bulgaria',
    'BG2': 'Bulgarian National Bank',
    'BG3': "Prime Minister's Office (Bulgaria)",
    'BG4': 'Ministry of Finance (Bulgaria)',
    'BG99': 'Other competent National Authority (Bulgaria)',
    'BH1': 'Directorate of Statistics (Bahrain)',
    'BH2': 'Bahrain Monetary Authority',
    'BH4': 'Ministry of Finance and  National Economy (Bahrain)',
    'BH99': 'Other competent National Authority (Bahrain, Kingdom of)',
    'BI2': 'Banque de la Republique du Burundi',
    'BI3': 'Ministère du Plan (Burundi)',
    'BI4': 'Ministère des finances (Burundi)',
    'BJ1': 'Institut National de la Statistique et de l’Analyse Economique (Benin)',
    'BJ2': 'Banque Centrale des États de l’Afrique de l’Ouest (BCEAO) (Benin)',
    'BJ4': 'Ministère des Finances (Benin)',
    'BJ99': 'Other competent National Authority (Benin)',
    'BM1': 'Bermuda Government - Department of Statistics',
    'BM2': 'Bermuda Monetary Authority',
    'BM99': 'Other competent National Authority (Bermuda)',
    'BN1': 'Department of Statistics (Brunei Darussalam)',
    'BN2': 'Brunei Currency and Monetary Board (BCMB)',
    'BN3': 'Department of Economic Planning and Development (DEPD) (Brunei Darussalam)',
    'BN4': 'Ministry of Finance (Brunei Darussalam)',
    'BN99': 'Other competent National Authority (Brunei Darussalam)',
    'BO1': 'Instituto Nacional de Estadistica (Bolivia)',
    'BO2': 'Banco Central de Bolivia',

In [ ]:
print('category_tree')
print(len(datasets['category_tree']))
for e in datasets['category_tree']:
        print('\t', e['name'])
        print('\t', e['code'], len(e['children']))
        for f in e['children']:
            print('\t\t', f['name'])
            print('\t\t', f['code'], len(f['children']))

            for g in f['children']:
                print('\t\t\t', g['name'])
                print('\t\t\t', g['code'])

category_tree
2
	 BISWEB_CATSCHEME

	 BISWEB_CATSCHEME 10
		 International banking

		 WEBSTATS_BANKING 2
			 BIS locational banking
			 WS_LBS_D_PUB
			 BIS consolidated banking
			 WS_CBS_PUB
		 Debt securities

		 WEBSTATS_SEC 1
			 BIS international debt securities (BIS-compiled)
			 WS_DEBT_SEC2_PUB
		 Derivatives

		 WEBSTATS_DER 3
			 OTC derivatives outstanding
			 WS_OTC_DERIV2
			 OTC derivatives turnover
			 WS_DER_OTC_TOV
			 Exchange traded derivatives
			 WS_XTD_DERIV
		 Global liquidity

		 WEBSTATS_GLI 1
			 Global liquidity indicators
			 WS_GLI
		 Total credit

		 WEBSTATS_TOTCRED 1
			 BIS long series on total credit
			 WS_TC
		 Credit gaps

		 WEBSTATS_CREDGAP 1
			 BIS credit-to-GDP gaps
			 WS_CREDIT_GAP
		 Debt service ratio

		 WEBSTATS_DSR 1
			 BIS debt service ratio
			 WS_DSR
		 Property prices

		 WEBSTATS_PP 1
			 Selected residential property prices
			 WS_SPP
		 Consumer prices

		 WEBSTATS_CPI 1
			 BIS long consumer prices
			 WS_LONG_CPI
		 Exchange rates

		 WEBSTATS_EXCHRATES 1
			 US dollar exchange rates
			 WS_XRU
	 Dataportal Category Scheme

	 BIS_DP 11
		 International banking

		 BANKING 4
			 Locational banking statistics

			 LBS
			 Consolidated banking statistics

			 CBS
			 BIS consolidated banking
			 WS_CBS_PUB
			 BIS locational banking
			 WS_LBS_D_PUB
		 Debt securities

		 DEBT_SEC 3
			 Debt securities statistics

			 DSS
			 International debt securities (BIS-compiled)

			 IDS
			 BIS international debt securities (BIS-compiled)
			 WS_DEBT_SEC2_PUB
		 Credit

		 CREDIT 6
			 Credit to the non-financial sector

			 TOTAL_CREDIT
			 Credit-to-GDP gaps

			 CREDIT_GAPS
			 Debt service ratios

			 DSR
			 BIS debt service ratio
			 WS_DSR
			 BIS long series on total credit
			 WS_TC
			 BIS credit-to-GDP gaps
			 WS_CREDIT_GAP
		 Global liquidity

		 GLI 1
			 Global liquidity indicators
			 WS_GLI
		 Derivatives

		 DERIVATIVES 6
			 Exchange-traded derivatives statistics

			 XTD_DER
			 OTC derivatives outstanding

			 OTC_DER
			 Triennial Survey

			 DER
			 Exchange traded derivatives
			 WS_XTD_DERIV
			 OTC derivatives turnover
			 WS_DER_OTC_TOV
			 OTC derivatives outstanding
			 WS_OTC_DERIV2
		 Property prices

		 PP 3
			 Residential property prices

			 RPP
			 Commercial property prices

			 CPP
			 Selected residential property prices
			 WS_SPP
		 Consumer prices

		 CPI 1
			 BIS long consumer prices
			 WS_LONG_CPI
		 Exchange rates

		 EXR 4
			 Bilateral exchange rates

			 XRU
			 Effective exchange rates

			 EER
			 BIS effective exchange rates
			 WS_EER
			 US dollar exchange rates
			 WS_XRU
		 Policy rates

		 CBPOL 1
			 Policy rate
			 WS_CBPOL
		 Payment statistics

		 CPMI 10
			 Retail payments, currency and related indicators

			 CPMI_CT
			 Financial market infrastructures and critical service providers

			 CPMI_FMI
			 CPMI comparative tables type 1
			 WS_CPMI_CT1
			 CPMI comparative tables type 2
			 WS_CPMI_CT2
			 CPMI payment devices (T4)
			 WS_CPMI_DEVICES
			 CPMI cashless payments (T5,T6)
			 WS_CPMI_CASHLESS
			 CPMI institutions (T3)
			 WS_CPMI_INSTITUT
			 CPMI systems (T8,T9,T11,T13,T14,T16,T17,T18,T19)
			 WS_CPMI_SYSTEMS
			 CPMI macro (T1,T2)
			 WS_CPMI_MACRO
			 CPMI participants (T7,T10,T12,T15)
			 WS_CPMI_PARTICIP
		 Central bank statistics

		 CB 2
			 Central bank total assets

			 CBTA
			 Central bank policy rates

			 CBPOL

In [ ]:
client.list_series('BIS', 'CBTA')

HTTPError: 404 Client Error: NOT FOUND for url: https://api.db.nomics.world/v22/series/BIS/CBTA?limit=1000&offset=0

In [ ]:
client.list_series('BIS', 'WS_CBTA')

{'_meta': {'args': {'align_periods': False,
   'dataset_code': 'WS_CBTA',
   'dimensions': {},
   'facets': False,
   'format': 'json',
   'limit': 1000,
   'metadata': True,
   'observations': False,
   'offset': 0,
   'provider_code': 'BIS',
   'q': '',
   'series_code': None},
  'version': '22.1.17'},
 'dataset': {'attributes_labels': {'BREAKS': 'Breaks',
   'COLLECTION': 'Collection Indicator',
   'COLLECTION_DETAIL': 'Collection explanation detail',
   'COMMENT_DSET': '',
   'COMMENT_TS': 'Series comment',
   'COMPILING_ORG': 'Compiling agency',
   'CONF_STATUS': 'Confidentiality - status',
   'DATA_COMP': 'Data compilation',
   'DECIMALS': 'Decimals',
   'DISS_ORG': 'Data dissemination agency',
   'FISCAL_YEAR': 'Fiscal year',
   'METHOD_REF': 'Methodology reference',
   'OBS_PRE_BREAK': 'Observation pre-break value',
   'OBS_STATUS': 'Observation status',
   'SUPP_INFO_BREAKS': 'Supplemental information and breaks',
   'TIME_FORMAT': 'Time format',
   'UNIT_MULT': 'Unit multiplier'},
  'attributes_values_labels': {'BREAKS': {'ADMIN': 'Administrative procedures',
    'CLASS': 'Classifications',
    'CONF': 'Confidentiality',
    'CUR': 'Currency',
    'DEF': 'Definition',
    'LEGAL': 'Legal basis',
    'METH': 'Methodologies',
    'NONSTAT': 'Non-statistical factors',
    'POL': 'Policy',
    'REF_PER': 'Reference period',
    'SAMPLE': 'Sample redesigned',
    'SCOPE': 'Revision of scope or coverage',
    'SOURCE': 'Data source',
    'STD': 'Standard(s)',
    'TRANSF': 'Data transformation',
    'UNIT': 'Statistical unit(s)',
    'VAL': 'Valuation methods',
    'WEIGHT': 'Base weight',
    '_O': 'Other',
    '_U': 'No data/unknown'},
   'COLLECTION': {'A': 'Average of observations through period',
    'B': 'Beginning of period',
    'E': 'End of period',
    'H': 'Highest in period',
    'L': 'Lowest in period',
    'M': 'Middle of period',
    'S': 'Summed through period',
    'U': 'Unknown',
    'V': 'Other',
    'Y': 'Annualised summed'},
   'CONF_STATUS': {'A': 'Primary confidentiality due to small counts',
    'C': 'Confidential statistical information',
    'D': 'Secondary confidentiality set by the sender, not for publication',
    'E': 'Not for publication, restricted for internal use only (equivalent to the code N) until the embargo time elapses; Free for publication (equivalent to the code F) after the embargo time elapses.',
    'F': 'Free (free for publication)',
    'G': 'Primary confidentiality due to dominance by one or two units',
    'M': 'Primary confidentiality due to data declared confidential based on other measures of concentration',
    'N': 'Not for publication, restricted for internal use only',
    'O': 'Primary confidentiality due to dominance by one unit',
    'S': 'Secondary confidentiality set and managed by the receiver, not for publication',
    'T': 'Primary confidentiality due to dominance by two units',
    'X': 'Confidentiality due to military secrecy'},
   'DECIMALS': {'0': 'Zero',
    '1': 'One',
    '10': 'Ten',
    '11': 'Eleven',
    '12': 'Twelve',
    '13': 'Thirteen',
    '14': 'Fourteen',
    '15': 'Fifteen',
    '16': 'Sixteen',
    '2': 'Two',
    '3': 'Three',
    '4': 'Four',
    '5': 'Five',
    '6': 'Six',
    '7': 'Seven',
    '8': 'Eight',
    '9': 'Nine'},
   'DISS_ORG': {'1A0': 'International organisations',
    '1B0': 'UN organisations',
    '1C0': 'IMF (International Monetary Fund)',
    '1D0': 'World Trade Organisation',
    '1E0': 'International Bank for Reconstruction and Development',
    '1F0': 'International Development Association',
    '1G0': 'ICSID (International Centre for Settlement of Investment Disputes)',
    '1H0': 'UNESCO (United Nations Educational, Scientific and Cultural Organisation)',
    '1J0': 'FAO (Food and Agriculture Organisation)',
    '1K0': 'WHO (World Health Organisation)',
    '1L0': 'IFAD (International Fund for Agricultural Development)',
    '1M0': 'IFC (International Finance Corporation)',
    '1N0': 'MIGA (Multilateral Investment Guarantee Agency)',
    '1O0': 'UNICEF (United Nations Children Fund)',
    '1P0': 'UNHCR (United Nations High Commissioner for Refugees)',
    '1Q0': 'UNRWA (United Nations Relief and Works Agency for Palestine)',
    '1R0': 'IAEA (International Atomic Energy Agency)',
    '1S0': 'ILO (International Labour Organisation)',
    '1T0': 'ITU (International Telecommunication Union)',
    '1U0': 'Rest of\xa0UN Organisations\xa0n.i.e.',
    '1V0': 'Universal Postal Union',
    '1X0': 'United Nations Office on Drugs and Crimes(UNODC)',
    '1Y0': 'The United Nations World Food Programme',
    '4A0': 'All the European Union Institutions excluding the ECB and ESM  deprecated',
    '4C0': 'EIB (European Investment Bank)',
    '4D0': 'European Commission (including Eurostat)',
    '4D1': 'Statistical Office of the European Commission (Eurostat)',
    '4E0': 'EDF (European Development Fund)',
    '4F0': 'ECB (European Central Bank)',
    '4G0': 'EIF (European Investment Fund)',
    '4H0': 'European Community of Steel and Coal deprecated',
    '4J0': 'Other EC Institutions, Organs and Organisms covered by General budget deprecated',
    '4J10': 'European Parliament',
    '4J20': 'Council of the European Union',
    '4J30': 'Court of Justice',
    '4J40': 'Court of Auditors',
    '4J50': 'European Council',
    '4J60': 'Economic and Social Committee',
    '4J70': 'Committee of Regions',
    '4J80': 'Other European Community Institutions, Organs and Organisms deprecated',
    '4J810': 'Agency for the Cooperation of Energy Regulators',
    '4J8100': 'European Centre for Disease Prevention and Control',
    '4J8110': 'European Centre for the Development of Vocational Training',
    '4J8120': 'European Chemicals Agency',
    '4J8130': 'European Data Protection Supervisor',
    '4J8140': 'European Defence Agency',
    '4J8150': 'European Environment Agency',
    '4J8160': 'European External Action Service',
    '4J8170': 'European Fisheries Control Agency',
    '4J8180': 'European Food Safety Authority',
    '4J8190': 'European Foundation for the Improvement of Living and Working Conditions',
    '4J820': 'Body of European Regulators for Electronic Communications',
    '4J8200': 'European GNSS Agency',
    '4J8210': 'European Institute for Gender Equality',
    '4J8220': 'European Institute of Innovation and Technology',
    '4J8230': 'European Maritime Safety Agency',
    '4J8240': 'European Medicines Agency',
    '4J8250': 'European Monitoring Centre for Drugs and Drug Addiction',
    '4J8260': 'European Network and Information Security Agency',
    '4J8270': 'European Ombudsman',
    '4J8280': 'European Personnel Selection Office',
    '4J8290': 'European Police College',
    '4J830': 'Community Plant Variety Office',
    '4J8300': 'European Police Office',
    '4J8310': "European Public Prosecutor's Office",
    '4J8320': 'European Railway Agency',
    '4J8330': 'European School of Administration',
    '4J8340': 'European Training Foundation',
    '4J8350': 'European Union Agency for Fundamental Rights',
    '4J8360': 'European Union Institute for Security Studies',
    '4J8370': 'European Union Intellectual Property Office',
    '4J8380': 'European Union Satellite Centre',
    '4J8390': 'Publications Office of the European Union',
    '4J840': 'Computer Emergency Response Team',
    '4J8400': 'The European Union’s Judicial Cooperation Unit',
    '4J8410': 'Translation Centre for the Bodies of the European Union',
    '4J8420': 'ATHENA Mechanism',
    '4J850': 'European Agency for Safety and Health at Work',
    '4J860': 'European Agency for the Management of Operational Cooperation at the External Borders',
    '4J870': 'European Agency for the operational management of large-scale IT systems in the area of freedom, security and justice',
    '4J880': 'European Asylum Support Office',
    '4J890': 'European Aviation Safety Agency',
    '4M0': 'SRB (Single Resolution Board)',
    '4S0': 'ESM (European Stability Mechanism)',
    '4T0': 'Joint Committee of the European Supervisory Authorities (ESAs)',
    '4T10': 'EBA (European Banking Authority)',
    '4T20': 'ESMA (European Securities and Markets Authority)',
    '4T30': 'EIOPA (European Insurance and Occupational Pensions Authority)',
    '4U10': 'Fusion for Energy',
    '4U20': 'EURATOM Supply Agency',
    '4W0': 'EFSF (European Financial Stability Facility)',
    '4Y0': 'All the European Union Institutions including the ECB and ESM deprecated',
    '5B0': 'BIS (Bank for International Settlements)',
    '5C0': 'IADB (Inter-American Development Bank)',
    '5D0': 'AfDB (African Development Bank)',
    '5E0': 'AsDB (Asian Development Bank)',
    '5F0': 'EBRD (European Bank for Reconstruction and Development)',
    '5G0': 'IIC (Inter-American Investment Corporation)',
    '5H0': 'NIB (Nordic Investment Bank)',
    '5I0': 'ECCB (Eastern Caribbean Central Bank)',
    '5J0': 'IBEC (International Bank for Economic Co-operation)',
    '5K0': 'IIB (International Investment Bank)',
    '5L0': 'CDB (Caribbean Development Bank)',
    '5M0': 'AMF (Arab Monetary Fund)',
    '5N0': 'BADEA (Banque arabe pour le développement économique en Afrique)',
    '5O0': 'BCEAO (Banque Centrale des États de l’Afrique de l’Ouest)',
    '5P0': 'CASDB (Central African States Development Bank)',
    '5Q0': 'African Development Fund',
    '5R0': 'Asian Development Fund',
    '5S0': 'Fonds spécial unifié de développement',
    '5T0': 'CABEI (Central American Bank for Economic Integration)',
    '5U0': 'ADC (Andean Development Corporation)',
    '5W0': 'BEAC (Banque des Etats de l`Afrique Centrale)',
    '5X0': 'CEMAC (Communauté Économique et Monétaire de l’Afrique Centrale)',
    '5Y0': 'ECCU (Eastern Caribbean Currency Union)',
    '5Z0': 'Other International Financial Organisations n.i.e.',
    '5Z10': 'Africa Finance Corporation',
    '5Z100': 'International Civil Aviation Organization',
    '5Z110': 'International Cocoa Organization',
    '5Z120': 'International Coffee Organization',
    '5Z130': 'International Copper Study Group',
    '5Z140': 'International Cotton Advisory Committee',
    '5Z150': 'International Grains Council',
    '5Z160': 'International Jute Study Group',
    '5Z170': 'International Lead and Zinc Study Group',
    '5Z180': 'International Maritime Organization',
    '5Z190': 'International Maritime Satellite Organization',
    '5Z20': 'African Development Bank Group',
    '5Z200': 'International Olive Oil Council',
    '5Z210': 'International Rubber Study Group',
    '5Z220': 'International Sugar Organization',
    '5Z230': 'Latin American and the Caribbean Economic System',
    '5Z240': 'Latin American Energy Organization',
    '5Z250': 'Latin American Integration Association',
    '5Z260': 'League of Arab States',
    '5Z270': 'Organisation of Eastern Caribbean States',
    '5Z280': 'Organization of American States',
    '5Z290': 'Organization of Arab Petroleum Exporting Countries',
    '5Z30': 'Arab Fund for Economic and Social Development',
    '5Z300': 'Organization of Central American States',
    '5Z310': 'Organization of the Petroleum Exporting Countries',
    '5Z330': 'South Asian Association for Regional Cooperation',
    '5Z340': 'United Nations Conference on Trade and Development',
    '5Z350': 'West African Economic Community',
    '5Z360': 'West African Health Organisation',
    '5Z370': 'West African Monetary Agency',
    '5Z380': 'West African Monetary Institute',
    '5Z390': 'World Council of Churches',
    '5Z40': 'Asian Clearing Union',
    '5Z400': 'World Intellectual Property Organization',
    '5Z410': 'World Meteorological Organization',
    '5Z420': 'World Tourism Organization',
    '5Z50': 'Colombo Plan',
    '5Z60': 'Economic Community of West African States',
    '5Z70': 'European Free Trade Association',
    '5Z80': 'Fusion for Energy deprecated',
    '5Z90': 'Intergovernmental Council of Copper Exporting Countries',
    '5z30': 'Arab Fund for Economic and Social Development (deprecated)',
    '6A0': 'Other International Organisations (non-financial institutions)',
    '6A10': 'African Union',
    '6A20': 'Association of Southeast Asian Nations',
    '6A30': 'Caribbean Community and Common Market',
    '6A40': 'Central American Common Market',
    '6A50': 'East African Development Bank',
    '6A60': 'ECOWAS Bank for Investment and Development',
    '6A70': 'Latin American Association of Development Financing Institutions',
    '6A80': 'OPEC Fund for International Development',
    '6B0': 'NATO (North Atlantic Treaty Organisation)',
    '6C0': 'Council of Europe',
    '6D0': 'ICRC (International Committee of the Red Cross)',
    '6E0': 'ESA (European Space Agency)',
    '6F0': 'EPO (European Patent Office)',
    '6G0': 'EUROCONTROL (European Organisation for the Safety of Air Navigation)',
    '6H0': 'EUTELSAT (European Telecommunications Satellite Organisation)',
    '6I0': 'EMBL (European Molecular Biology Laboratory)',
    '6J0': 'INTELSAT (International Telecommunications Satellite Organisation)',
    '6K0': 'EBU/UER (European Broadcasting Union/Union européenne de radio-télévision)',
    '6L0': 'EUMETSAT (European Organisation for the Exploitation of Meteorological Satellites)',
    '6M0': 'ESO (European Southern Observatory)',
    '6N0': 'ECMWF (European Centre for Medium-Range Weather Forecasts)',
    '6O0': 'OECD (Organisation for Economic Co-operation and Development)',
    '6P0': 'CERN (European Organisation for Nuclear Research)',
    '6Q0': 'IOM (International Organisation for Migration)',
    '6Z0': 'Other International Non-Financial Organisations n.i.e.',
    '6Z10': 'The Global Fund to Fight AIDS, Tuberculosis and Malaria',
    '6Z20': 'International Centre for Migration Policy Development',
    '7A0': 'WAEMU (West African Economic and Monetary Union)',
    '7B0': 'IDB (Islamic Development Bank)',
    '7C0': 'EDB (Eurasian Development Bank )',
    '7D0': 'Paris Club Creditor Institutions',
    '7E0': 'CEB (Council of Europe Development Bank)',
    '7F0': 'International Union of Credit and Investment Insurers',
    '7G0': 'Black Sea Trade and Development Banks',
    '7H0': 'AFREXIMBANK (African Export-Import Bank)',
    '7I0': 'BLADEX (Banco Latino Americano De Comercio Exterior)',
    '7J0': 'FLAR (Fondo Latino Americano de Reservas)',
    '7K0': "Fonds Belgo-Congolais d'Amortissement et de Gestion",
    '7L0': 'IFFIm (International finance Facility for Immunisation)',
    '7M0': 'EUROFIMA (European Company for the Financing of Railroad Rolling Stock)',
    '7N0': 'Development Bank of Latin America (Banco de Desarrollo de America Latina)',
    '7O0': 'The Eastern and Southern African Trade and Development Bank',
    '9A0': 'International Organisations excl. European Community Institutions (4Y)',
    'AD2': 'Andorra Finance institute',
    'AE1': 'Central Statistical Organization, part of the Ministry of Economy and Planning (United Arab Emirates)',
    'AE2': 'Central Bank of the United Arab Emirates',
    'AE4': 'Ministry of Finance and Industry (United Arab Emirates)',
    'AE_DU6': 'Dubai Financial Services Authority',
    'AF2': 'Da Afghanistan Bank',
    'AF4': 'Ministry of Finance (Afghanistan, Islamic State of)',
    'AG2': 'Eastern Caribbean Central Bank (ECCB) (Antigua and Barbuda)',
    'AG4': 'Ministry of Finance (Antigua and Barbuda)',
    'AI1': 'Central Statistical Office (Anguilla)',
    'AI4': 'Ministry of Finance (Anguilla)',
    'AI99': 'Other competent National Authority (Anguilla)',
    'AL1': 'Institute of Statistics (Albania)',
    'AL2': 'Bank of Albania',
    'AL4': 'Ministère des Finances (Albania)',
    'AM1': 'National Statistics Service (Armenia)',
    'AM2': 'Central Bank of Armenia',
    'AM4': 'Ministry of Finance and Economy (Armenia)',
    'AM99': 'Other competent National Authority (Armenia, Republic of)',
    'AN1': 'Central Bureau of Statistics (Netherlands Antilles)',
    'AN2': 'Bank of the Netherlands Antilles',
    'AN99': 'Other competent National Authority (Netherlands Antilles)',
    'AO1': 'National Institute of Statistics (Angola)',
    'AO2': 'Banco Nacional de Angola',
    'AO4': 'Ministério das Finanças (Angola)',
    'AR1': 'Instituto Nacional de Estadistica y Censos (Argentina)',
    'AR2': 'Banco Central de la Republica Argentina',
    'AR4': 'Ministerio de Economía (Argentina)',
    'AR99': 'Other competent National Authority (Argentina)',
    'AT1': 'Statistik Österreich (Austria)',
    'AT2': 'Oesterreichische Nationalbank (Austria)',
    'AT6': 'FMA (Austria Financial Market Authority)',
    'AT99': 'Other competent National Authority (Austria)',
    'AU1': 'Australian Bureau of Statistics',
    'AU2': 'Reserve Bank of Australia',
    'AU5': 'Department of the Treasury (Australia)',
    'AU99': 'Other competent National Authority (Australia)',
    'AW1': 'Central Bureau of Statistics (Aruba)',
    'AW2': 'Centrale Bank van Aruba',
    'AW99': 'Other competent National Authority (Aruba)',
    'AZ1': 'State Statistical Committee of the Republic of Azerbaijan',
    'AZ2': 'National Bank of Azerbaijan',
    'AZ4': 'Ministry of Finance (Azerbaijan)',
    'AZ99': 'Other competent National Authority (Azerbaijan, Republic of)',
    'B22': 'EU 15 central banks',
    'B32': 'EU 25 central banks',
    'B42': 'EU 27 central banks',
    'B52': 'EU 28 central banks',
    'B62': 'EU27 central banks (fixed composition) as of 31 January 2020 (brexit)',
    'BA1': 'Institute of Statistics (Bosnia and Herzegovina)',
    'BA2': 'Central Bank of Bosnia and Herzegovina',
    'BA4': 'Bosnia and Herzegovina Ministry of Finance and Treasury',
    'BA99': 'Other competent National Authority (Bosnia and Herzegovina)',
    'BB1': 'Barbados Statistical Service',
    'BB2': 'Central Bank of Barbados',
    'BB4': 'Ministry of Finance and  Economic Affairs (Barbados)',
    'BB99': 'Other competent National Authority (Barbados)',
    'BD1': 'Bangladesh Bureau of Statistics',
    'BD2': 'Bangladesh Bank',
    'BD4': 'Ministry of Finance (Bangladesh)',
    'BE1': 'Institut National de Statistiques de Belgique',
    'BE2': 'Banque Nationale de Belgique (Belgium)',
    'BE3': 'Federal Public Service Finance (Belgium)',
    'BE40': 'Federal Planning Bureau',
    'BE9': 'Bureau van Dijk (Belgium)',
    'BE99': 'Other competent National Authority (Belgium)',
    'BF2': 'Banque Centrale des États de l’Afrique de l’Ouest (BCEAO) (Burkina Faso)',
    'BF4': "Ministere de l'Economie et des Finances  (Burkina Faso)",
    'BG1': 'National Statistical Institute of Bulgaria',
    'BG2': 'Bulgarian National Bank',
    'BG3': "Prime Minister's Office (Bulgaria)",
    'BG4': 'Ministry of Finance (Bulgaria)',
    'BG99': 'Other competent National Authority (Bulgaria)',
    'BH1': 'Directorate of Statistics (Bahrain)',
    'BH2': 'Bahrain Monetary Authority',
    'BH4': 'Ministry of Finance and  National Economy (Bahrain)',
    'BH99': 'Other competent National Authority (Bahrain, Kingdom of)',
    'BI2': 'Banque de la Republique du Burundi',
    'BI3': 'Ministère du Plan (Burundi)',
    'BI4': 'Ministère des finances (Burundi)',
    'BJ1': 'Institut National de la Statistique et de l’Analyse Economique (Benin)',
    'BJ2': 'Banque Centrale des États de l’Afrique de l’Ouest (BCEAO) (Benin)',
    'BJ4': 'Ministère des Finances (Benin)',
    'BJ99': 'Other competent National Authority (Benin)',
    'BM1': 'Bermuda Government - Department of Statistics',
    'BM2': 'Bermuda Monetary Authority',
    'BM99': 'Other competent National Authority (Bermuda)',
    'BN1': 'Department of Statistics (Brunei Darussalam)',
    'BN2': 'Brunei Currency and Monetary Board (BCMB)',
    'BN3': 'Department of Economic Planning and Development (DEPD) (Brunei Darussalam)',
    'BN4': 'Ministry of Finance (Brunei Darussalam)',
    'BN99': 'Other competent National Authority (Brunei Darussalam)',
    'BO1': 'Instituto Nacional de Estadistica (Bolivia)',
    'BO2': 'Banco Central de Bolivia',

In [ ]:
def list_all_series(client, provider, dataset):
    all_series = []
    offset = 0
    limit = 1000

    while True:
        data = client.list_series(provider, dataset, limit, offset)
        series = data.get("series", [])
        if not series:
            break
        all_series.extend(series)
        offset += limit

    return all_series

In [ ]:
list_all_series(client, 'BIS', 'WS_CPMI_CT1')

HTTPError: 400 Client Error: BAD REQUEST for url: https://api.db.nomics.world/v22/series/BIS/WS_CPMI_CT1?limit=1000&offset=101000

# 2 - NEW

In [ ]:
from extraction import world_bank

client = world_bank.DBnomicsClient()

In [39]:
datasets_df = io.load_csv(config.METADATA_DIR / 'provider_datasets_selected.csv', index_col=0)
datasets_df.head(5)

,Provider Id,Provider Name,Provider Region,Dataset Id,Dataset Name,Subgroup 1 Id,Subgroup 1 Name,Subgroup 2 Id,Subgroup 2 Name,Country Param Name,Country Param Format,Frequency Param Name,Frequency Annual,Other Param Name
0,IMF,International Monetary Fund,World,BOP,Balance of Payments (BOP),NaN,NaN,NaN,NaN,REF_AREA,ISO2,FREQ,A,INDICATOR
2,IMF,International Monetary Fund,World,CPI,Consumer Price Index (CPI),NaN,NaN,NaN,NaN,REF_AREA,ISO2,FREQ,A,INDICATOR
3,IMF,International Monetary Fund,World,FDI,Financial Development Index,NaN,NaN,NaN,NaN,REF_AREA,ISO2,FREQ,A,INDICATOR
4,IMF,International Monetary Fund,World,FM,Fiscal Monitor (FM),NaN,NaN,NaN,NaN,REF_AREA,ISO2,FREQ,A,INDICATOR
5,IMF,International Monetary Fund,World,FSI,Financial Soundness Indicators (FSIs),NaN,NaN,NaN,NaN,REF_AREA,ISO2,FREQ,A,INDICATOR

In [40]:
providers = datasets_df['Provider Id'].unique()

dataset_params = {}
for i, dataset_row in datasets_df.iterrows():
    provider_id = dataset_row['Provider Id']
    dataset_id = dataset_row['Dataset Id']
    # print('Provider:', provider_id, 'Dataset:', dataset_id)

    if provider_id not in dataset_params.keys():
        dataset_params[provider_id] = {dataset_id: {}}
    else:
        dataset_params[provider_id][dataset_id] = {}

    try:
        dataset_dict = client.list_series(provider_id, dataset_id, limit=1)
        dataset_dim_dict = dataset_dict['dataset']['dimensions_values_labels']
        dataset_dim_dict.pop(dataset_row['Country Param Name'])
        dataset_dim_dict.pop(dataset_row['Frequency Param Name'])

        dataset_params[provider_id][dataset_id] = dataset_dim_dict

    except SyntaxError:
            print('Error querying dataset:', provider_id, dataset_id)

In [41]:
count_dataset_d = {}
count_provider_d = {}
count_d = {}
for provider_id, provider_d in dataset_params.items():
    count_d[provider_id] = {}
    count_dataset_d[provider_id] = {}
    v_provider = 0
    for dataset_id, dataset_d in provider_d.items():
        count_d[provider_id][dataset_id] = {}
        count_dataset_d[provider_id][dataset_id] = {}
        v_dataset = 1
        for param, param_d in dataset_d.items():
            v_dataset = v_dataset * len(param_d)
        
        count_dataset_d[provider_id][dataset_id] = v_dataset
        v_provider = v_provider + v_dataset
    count_provider_d[provider_id] = v_provider

count_provider_d

{'IMF': 18577, 'WB': 3266, 'BIS': 25944883500, 'UNCTAD': 69}

In [42]:
dataset_params['IMF']['BOP'].keys()

dict_keys(['INDICATOR'])

In [121]:
clean_d = {}

for provider, provider_d in dataset_params.items():
    clean_d[provider] = {}
    for dataset, dataset_d in provider_d.items():
        clean_d[provider][dataset] = {}
        
        for param, param_d in dataset_d.items():
            new_d = {}

            for ind, descr in sorted(param_d.items()):
                if ' ' in ind:
                    continue

                if provider == 'IMF' and param == 'INDICATOR':
                    if dataset in ['CPI', 'FDI', 'FM']:
                        new_d[ind] = descr
                    elif '_' in ind:
                        if ind[-3:] == 'USD' or ind[-2:] == 'PT':
                            if dataset != 'BOP' and len(ind.split('_')[0]) >= 3:
                                continue
                            else:
                                new_d[ind] = descr
                                
                        elif ind[-3:] == 'EUR' or ind[-3:] == 'XDC':
                            pass
                        else:
                            print('Weird Indicator', provider, dataset, ind)
                    else:
                        new_d[ind] = descr
                    # else:
                #     print('BAD')

                else:
                    new_d[ind] = descr

                clean_d[provider][dataset][param] = new_d

Weird Indicator IMF FSI All_Indicators
Weird Indicator IMF FSI All_Indicators_Minus_Discontinued
Weird Indicator IMF FSI Discontinued_Indicators
Weird Indicator IMF FSI ENDE_XDC_USD_RATE
Weird Indicator IMF FSI FSNA_NUM
Weird Indicator IMF FSI FSSH_BP
Weird Indicator IMF FSI FSSR_BP
Weird Indicator IMF FSI FS_ODX_ADU_MH
Weird Indicator IMF FSI FS_ODX_EXLN_NUM
Weird Indicator IMF FSI FS_ODX_HI_BP
Weird Indicator IMF FSI FS_ODX_HI_FSSH_BP
Weird Indicator IMF FSI FS_ODX_LDU_MH
Weird Indicator IMF FSI FS_ODX_LI_BP
Weird Indicator IMF FSI FS_ODX_LI_FSSH_BP
Weird Indicator IMF FSI FS_ODX_RD_BP
Weird Indicator IMF FSI FS_ODX_RD_FSSR_BP
Weird Indicator IMF FSI FS_ODX_RL_BP
Weird Indicator IMF FSI FS_ODX_RL_FSSR_BP
Weird Indicator IMF GENDER_EQUALITY All_Indicators
Weird Indicator IMF GENDER_EQUALITY GE_GDI
Weird Indicator IMF GENDER_EQUALITY GE_GII
Weird Indicator IMF HPDD GGXWDG_GDP
Weird Indicator IMF IFS 1C_ALL_INDICATORS
Weird Indicator IMF IFS 26J___XDR
Weird Indicator IMF IFS AIPCO_IX
Weird Indicator IMF IFS AIPEE_IX
Weird Indicator IMF IFS AIPMA_IX
Weird Indicator IMF IFS AIPMI_IX
Weird Indicator IMF IFS AIP_IX
Weird Indicator IMF IFS AIP_SA_IX
Weird Indicator IMF IFS AOMPC_IX
Weird Indicator IMF IFS AOTN_NUM
Weird Indicator IMF IFS AOTV_PE_IX
Weird Indicator IMF IFS AOTV_PE_NUM
Weird Indicator IMF IFS ARS_IX
Weird Indicator IMF IFS EDGE_USD_OZT_RATE
Weird Indicator IMF IFS EDGE_XDR_OZT_RATE
Weird Indicator IMF IFS EDNA_USD_XDC_RATE
Weird Indicator IMF IFS EDNE_USD_XDC_RATE
Weird Indicator IMF IFS EDSA_USD_XDR_RATE
Weird Indicator IMF IFS EDSE_USD_XDR_RATE
Weird Indicator IMF IFS EECUNA_XEU_XDC_RATE
Weird Indicator IMF IFS EECUNE_XEU_XDC_RATE
Weird Indicator IMF IFS EENA_EUR_XDC_RATE
Weird Indicator IMF IFS EENE_EUR_XDC_RATE
Weird Indicator IMF IFS ENDA_XDC_USD_RATE
Weird Indicator IMF IFS ENDE_XDC_USD_RATE
Weird Indicator IMF IFS ENEA_XDC_EUR_RATE
Weird Indicator IMF IFS ENECUA_XDC_XEU_RATE
Weird Indicator IMF IFS ENECUE_XDC_XEU_RATE
Weird Indicator IMF IFS ENEER_IX
Weird Indicator IMF IFS ENEER_ULC_IX
Weird Indicator IMF IFS ENEE_XDC_EUR_RATE
Weird Indicator IMF IFS ENSA_XDC_XDR_RATE
Weird Indicator IMF IFS ENSE_XDC_XDR_RATE
Weird Indicator IMF IFS EREER_IX
Weird Indicator IMF IFS EREER_ULC_IX
Weird Indicator IMF IFS ESDA_XDR_USD_RATE
Weird Indicator IMF IFS ESDE_XDR_USD_RATE
Weird Indicator IMF IFS ESNA_XDR_XDC_RATE
Weird Indicator IMF IFS ESNE_XDR_XDC_RATE
Weird Indicator IMF IFS FIACF_PA
Weird Indicator IMF IFS FIBFR_PA
Weird Indicator IMF IFS FICB_PA
Weird Indicator IMF IFS FICD_PA
Weird Indicator IMF IFS FICPR_PA
Weird Indicator IMF IFS FIDFR_PA
Weird Indicator IMF IFS FIDR_FX_EUR_PA
Weird Indicator IMF IFS FIDR_FX_PA
Weird Indicator IMF IFS FIDR_FX_USD_PA
Weird Indicator IMF IFS FIDR_ON_PA
Weird Indicator IMF IFS FIDR_PA
Weird Indicator IMF IFS FID_FX_PA
Weird Indicator IMF IFS FID_PA
Weird Indicator IMF IFS FIGBY_MT_PA
Weird Indicator IMF IFS FIGBY_PA
Weird Indicator IMF IFS FIGBY_SM_PA
Weird Indicator IMF IFS FIGB_MLT_PA
Weird Indicator IMF IFS FIGB_PA
Weird Indicator IMF IFS FIGB_S_PA
Weird Indicator IMF IFS FIHN_HH_D_AM_1Y_PA
Weird Indicator IMF IFS FIHN_HH_D_FX_PA
Weird Indicator IMF IFS FIHN_HH_D_NC_PA
Weird Indicator IMF IFS FIHN_HH_L_CO_1Y_PA
Weird Indicator IMF IFS FIHN_HH_L_FX_PA
Weird Indicator IMF IFS FIHN_HH_L_HP_O5Y_PA
Weird Indicator IMF IFS FIHN_HH_L_NC_PA
Weird Indicator IMF IFS FIHN_NFC_D_AM_1Y_PA
Weird Indicator IMF IFS FIHN_NFC_D_FX_PA
Weird Indicator IMF IFS FIHN_NFC_D_NC_PA
Weird Indicator IMF IFS FIHN_NFC_L_FX_PA
Weird Indicator IMF IFS FIHN_NFC_L_NC_PA
Weird Indicator IMF IFS FIHN_NFC_L_OT_O1MILL_1Y_PA
Weird Indicator IMF IFS FIHN_NFC_L_OT_O1MILL_3M_1Y_PA
Weird Indicator IMF IFS FIHO_HH_D_AM_2Y_PA
Weird Indicator IMF IFS FIHO_NFC_D_AM_2Y_PA
Weird Indicator IMF IFS FIHO_NFC_D_RP_PA
Weird Indicator IMF IFS FIH_HH_L_CC_1Y_PA
Weird Indicator IMF IFS FIH_HH_L_HP_O5Y_PA
Weird Indicator IMF IFS FIH_NFC_L_1Y_PA
Weird Indicator IMF IFS FII_3M_PA
Weird Indicator IMF IFS FILED_3M_PA
Weird Indicator IMF IFS FILIBOR_1M_PA
Weird Indicator IMF IFS FILIBOR_1Y_PA
Weird Indicator IMF IFS FILIBOR_6M_PA
Weird Indicator IMF IFS FILIBOR_ON_PA
Weird Indicator IMF IFS FILR_FX_EUR_PA
Weird Indicator IMF IFS FILR_FX_PA
Weird Indicator IMF IFS FILR_FX_USD_PA
Weird Indicator IMF IFS FILR_ON_PA
Weird Indicator IMF IFS FILR_PA
Weird Indicator IMF IFS FIMM_FX_PA
Weird Indicator IMF IFS FIMM_MAX_PA
Weird Indicator IMF IFS FIMM_MIN_PA
Weird Indicator IMF IFS FIMM_PA
Weird Indicator IMF IFS FIRAK_PA
Weird Indicator IMF IFS FIRAR_PA
Weird Indicator IMF IFS FIRA_PA
Weird Indicator IMF IFS FIRR_PA
Weird Indicator IMF IFS FIR_PA
Weird Indicator IMF IFS FISDR_PA
Weird Indicator IMF IFS FISR_FX_PA
Weird Indicator IMF IFS FISR_PA
Weird Indicator IMF IFS FITBBE_PA
Weird Indicator IMF IFS FITB_3M_PA
Weird Indicator IMF IFS FITB_FX_PA
Weird Indicator IMF IFS FITB_IX
Weird Indicator IMF IFS FITB_L_PA
Weird Indicator IMF IFS FITB_PA
Weird Indicator IMF IFS FMVB_IX
Weird Indicator IMF IFS FPECS_IX
Weird Indicator IMF IFS FPEFR_EOP_IX
Weird Indicator IMF IFS FPEFR_IX
Weird Indicator IMF IFS FPEF_EOP_IX
Weird Indicator IMF IFS FPEI_EOP_IX
Weird Indicator IMF IFS FPEI_IX
Weird Indicator IMF IFS FPEMF_IX
Weird Indicator IMF IFS FPEMN_IX
Weird Indicator IMF IFS FPEPAMEX_IX
Weird Indicator IMF IFS FPEPFIRS_IX
Weird Indicator IMF IFS FPEPIGPA_IX
Weird Indicator IMF IFS FPEPNAS_IX
Weird Indicator IMF IFS FPEPRTS_IX
Weird Indicator IMF IFS FPEPSEM7_IX
Weird Indicator IMF IFS FPEPSP_IX
Weird Indicator IMF IFS FPEPWIG20_EOP_IX
Weird Indicator IMF IFS FPEPWIG20_IX
Weird Indicator IMF IFS FPESP_EOP_IX
Weird Indicator IMF IFS FPESP_IX
Weird Indicator IMF IFS FPE_EOP_IX
Weird Indicator IMF IFS FPE_IX
Weird Indicator IMF IFS FPOLM_PA
Weird Indicator IMF IFS HLTF_XDR
Weird Indicator IMF IFS HNCA_XDR
Weird Indicator IMF IFS HOO_XDR
Weird Indicator IMF IFS HPG_XDR
Weird Indicator IMF IFS HPHCPQ_PA
Weird Indicator IMF IFS HPHC_XDR
Weird Indicator IMF IFS HPHSPA_PA
Weird Indicator IMF IFS HPL_XDR
Weird Indicator IMF IFS HPQ_XDR
Weird Indicator IMF IFS HPUPQ_PA
Weird Indicator IMF IFS HPURTP_XDR
Weird Indicator IMF IFS HPU_XDR
Weird Indicator IMF IFS HSA_XDR
Weird Indicator IMF IFS LE_IX
Weird Indicator IMF IFS LE_PE_NUM
Weird Indicator IMF IFS LLF_PE_NUM
Weird Indicator IMF IFS LP_PE_NUM
Weird Indicator IMF IFS LU_PE_NUM
Weird Indicator IMF IFS LWR_IX
Weird Indicator IMF IFS NGDP_D_IX
Weird Indicator IMF IFS NGDP_D_SA_IX
Weird Indicator IMF IFS NGDP_R_SA_PU
Weird Indicator IMF IFS NGDP_SA_PU
Weird Indicator IMF IFS PCPIHA_IX
Weird Indicator IMF IFS PCPI_IX
Weird Indicator IMF IFS PMP_IX
Weird Indicator IMF IFS PPPIFG_IX
Weird Indicator IMF IFS PPPIIRM_IX
Weird Indicator IMF IFS PPPII_IX
Weird Indicator IMF IFS PPPI_IX
Weird Indicator IMF IFS PWPI_IX
Weird Indicator IMF IFS PXP_IX
Weird Indicator IMF IFS RAFAGOLDM_XDR
Weird Indicator IMF IFS RAFAGOLDNV_XDR
Weird Indicator IMF IFS RAFAGOLDV_OZT
Weird Indicator IMF IFS RAFAGOLD_XDR
Weird Indicator IMF IFS RAFAIMF_XDR
Weird Indicator IMF IFS RAFASDR_XDR
Weird Indicator IMF IFS RAFA_G_XDR
Weird Indicator IMF IFS RAFA_MV_XDR
Weird Indicator IMF IFS RAFA_XDR
Weird Indicator IMF IFS RAXGFX_XDR
Weird Indicator IMF IFS RAXGO_XDR
Weird Indicator IMF IFS RAXG_XDR
Weird Indicator IMF IFS TMG_D_CIF_IX
Weird Indicator IMF IFS TMG_D_CIF_USD_IX
Weird Indicator IMF IFS TMG_R_CIF_IX
Weird Indicator IMF IFS TXG_D_FOB_IX
Weird Indicator IMF IFS TXG_D_FOB_USD_IX
Weird Indicator IMF IFS TXG_R_FOB_IX
Weird Indicator IMF IRFCL All_Currency_Indicators
Weird Indicator IMF IRFCL All_Indicators
Weird Indicator IMF IRFCL All_Non_Currency_Indicators
Weird Indicator IMF IRFCL All_Published_Indicators
Weird Indicator IMF IRFCL All_Reported_Indicators
Weird Indicator IMF IRFCL All_Total_Maturity_Indicators
Weird Indicator IMF IRFCL Analatical_Indicators
Weird Indicator IMF IRFCL ENDE_XDC_USD_RATE
Weird Indicator IMF IRFCL Exchange_Rate_Indicator
Weird Indicator IMF IRFCL IFS_Gold_Indicators
Weird Indicator IMF IRFCL IFS_Indicators
Weird Indicator IMF IRFCL IFS_non_Gold_Indicators
Weird Indicator IMF IRFCL Negative_Indicators
Weird Indicator IMF IRFCL Positive_Indicators
Weird Indicator IMF IRFCL Published_Non_currency_Indicators
Weird Indicator IMF IRFCL RAFAGOLDVGB_OZT
Weird Indicator IMF IRFCL RAFAGOLDVUG_OZT
Weird Indicator IMF IRFCL RAFAGOLDV_OZT
Weird Indicator IMF IRFCL RAFA_RAPFA_RO
Weird Indicator IMF IRFCL Section_III___Total_Maturity_Indicators
Weird Indicator IMF IRFCL Section_II___Total_Maturity_Indicators
Weird Indicator IMF MFS 26J___XDR
Weird Indicator IMF MFS FIACF_PA
Weird Indicator IMF MFS FIBFR_PA
Weird Indicator IMF MFS FICB_PA
Weird Indicator IMF MFS FICD_PA
Weird Indicator IMF MFS FICPR_PA
Weird Indicator IMF MFS FIDFR_PA
Weird Indicator IMF MFS FIDR_FX_EUR_PA
Weird Indicator IMF MFS FIDR_FX_PA
Weird Indicator IMF MFS FIDR_FX_USD_PA
Weird Indicator IMF MFS FIDR_ON_PA
Weird Indicator IMF MFS FIDR_PA
Weird Indicator IMF MFS FID_FX_PA
Weird Indicator IMF MFS FID_PA
Weird Indicator IMF MFS FIGBY_MT_PA
Weird Indicator IMF MFS FIGBY_PA
Weird Indicator IMF MFS FIGBY_SM_PA
Weird Indicator IMF MFS FIGB_MLT_PA
Weird Indicator IMF MFS FIGB_PA
Weird Indicator IMF MFS FIGB_S_PA
Weird Indicator IMF MFS FIHN_HH_D_AM_1Y_PA
Weird Indicator IMF MFS FIHN_HH_D_FX_PA
Weird Indicator IMF MFS FIHN_HH_D_NC_PA
Weird Indicator IMF MFS FIHN_HH_L_CO_1Y_PA
Weird Indicator IMF MFS FIHN_HH_L_FX_PA
Weird Indicator IMF MFS FIHN_HH_L_HP_O5Y_PA
Weird Indicator IMF MFS FIHN_HH_L_NC_PA
Weird Indicator IMF MFS FIHN_NFC_D_AM_1Y_PA
Weird Indicator IMF MFS FIHN_NFC_D_FX_PA
Weird Indicator IMF MFS FIHN_NFC_D_NC_PA
Weird Indicator IMF MFS FIHN_NFC_L_FX_PA
Weird Indicator IMF MFS FIHN_NFC_L_NC_PA
Weird Indicator IMF MFS FIHN_NFC_L_OT_O1MILL_1Y_PA
Weird Indicator IMF MFS FIHN_NFC_L_OT_O1MILL_3M_1Y_PA
Weird Indicator IMF MFS FIHO_HH_D_AM_2Y_PA
Weird Indicator IMF MFS FIHO_NFC_D_AM_2Y_PA
Weird Indicator IMF MFS FIHO_NFC_D_RP_PA
Weird Indicator IMF MFS FIH_HH_L_CC_1Y_PA
Weird Indicator IMF MFS FIH_HH_L_HP_O5Y_PA
Weird Indicator IMF MFS FIH_NFC_L_1Y_PA
Weird Indicator IMF MFS FII_3M_PA
Weird Indicator IMF MFS FILED_3M_PA
Weird Indicator IMF MFS FILIBOR_1M_PA
Weird Indicator IMF MFS FILIBOR_1Y_PA
Weird Indicator IMF MFS FILIBOR_6M_PA
Weird Indicator IMF MFS FILIBOR_ON_PA
Weird Indicator IMF MFS FILR_FX_EUR_PA
Weird Indicator IMF MFS FILR_FX_PA
Weird Indicator IMF MFS FILR_FX_USD_PA
Weird Indicator IMF MFS FILR_ON_PA
Weird Indicator IMF MFS FILR_PA
Weird Indicator IMF MFS FIMM_FX_PA
Weird Indicator IMF MFS FIMM_MAX_PA
Weird Indicator IMF MFS FIMM_MIN_PA
Weird Indicator IMF MFS FIMM_PA
Weird Indicator IMF MFS FIRAK_PA
Weird Indicator IMF MFS FIRAR_PA
Weird Indicator IMF MFS FIRA_PA
Weird Indicator IMF MFS FIRR_PA
Weird Indicator IMF MFS FIR_PA
Weird Indicator IMF MFS FISDR_PA
Weird Indicator IMF MFS FISR_FX_PA
Weird Indicator IMF MFS FISR_PA
Weird Indicator IMF MFS FITBBE_PA
Weird Indicator IMF MFS FITB_3M_PA
Weird Indicator IMF MFS FITB_FX_PA
Weird Indicator IMF MFS FITB_IX
Weird Indicator IMF MFS FITB_L_PA
Weird Indicator IMF MFS FITB_PA
Weird Indicator IMF MFS FMVB_IX
Weird Indicator IMF MFS FPECS_IX
Weird Indicator IMF MFS FPEFR_EOP_IX
Weird Indicator IMF MFS FPEFR_IX
Weird Indicator IMF MFS FPEF_EOP_IX
Weird Indicator IMF MFS FPEI_EOP_IX
Weird Indicator IMF MFS FPEI_IX
Weird Indicator IMF MFS FPEMF_IX
Weird Indicator IMF MFS FPEMN_IX
Weird Indicator IMF MFS FPEPAMEX_IX
Weird Indicator IMF MFS FPEPFIRS_IX
Weird Indicator IMF MFS FPEPIGPA_IX
Weird Indicator IMF MFS FPEPNAS_IX
Weird Indicator IMF MFS FPEPRTS_IX
Weird Indicator IMF MFS FPEPSEM7_IX
Weird Indicator IMF MFS FPEPSP_IX
Weird Indicator IMF MFS FPEPWIG20_EOP_IX
Weird Indicator IMF MFS FPEPWIG20_IX
Weird Indicator IMF MFS FPESP_EOP_IX
Weird Indicator IMF MFS FPESP_IX
Weird Indicator IMF MFS FPE_EOP_IX
Weird Indicator IMF MFS FPE_IX
Weird Indicator IMF MFS FPOLM_PA
Weird Indicator IMF PGCS kpriv_gdp
Weird Indicator IMF PGCS kpriv_pch
Weird Indicator IMF PGCS kpubl_gdp
Weird Indicator IMF PGCS kpubl_pch
Weird Indicator IMF PGCS priv_rinv
Weird Indicator IMF PGCS priv_rinv_gdp
Weird Indicator IMF PGCS publ_rinv
Weird Indicator IMF PGCS publ_rinv_gdp
Weird Indicator IMF PGCS rinv_gdp
Weird Indicator IMF PGCS rnna_gdp
Weird Indicator IMF PGCS rnna_pch
Weird Indicator IMF PSBSFAD NFFCNR|XDCG23|_Z
Weird Indicator IMF PSBSFAD NFFCNR|XDCG4|F_NN
Weird Indicator IMF PSBSFAD NFFCNR|XDCG5|F_NN
Weird Indicator IMF PSBSFAD NFFCNR|XDCG63F63_65W0|S1
Weird Indicator IMF PSBSFAD NFFCNR|XDCG6X|F_NN
Weird Indicator IMF PSBSFAD NFFCNR|XDCG6|F_NN
Weird Indicator IMF PSBSFAD NFFCNR|XDCGGOB|_Z
Weird Indicator IMF PSBSFAD NFFCNR|XDCGNLB|_Z
Weird Indicator IMF PSBSFAD NFFCNR|XDCGNOB|_Z
Weird Indicator IMF PSBSFAD NFFCO|XDCG23|_Z
Weird Indicator IMF PSBSFAD NFFCO|XDCG4|F_NN
Weird Indicator IMF PSBSFAD NFFCO|XDCG5|F_NN
Weird Indicator IMF PSBSFAD NFFCO|XDCG63F63_65W0|S1
Weird Indicator IMF PSBSFAD NFFCO|XDCG6X|F_NN
Weird Indicator IMF PSBSFAD NFFCO|XDCG6|F_NN
Weird Indicator IMF PSBSFAD NFFCO|XDCGGOB|_Z
Weird Indicator IMF PSBSFAD NFFCO|XDCGNLB|_Z
Weird Indicator IMF PSBSFAD NFFCO|XDCGNOB|_Z
Weird Indicator IMF PSBSFAD NFFCT|XDCG23|_Z
Weird Indicator IMF PSBSFAD NFFCT|XDCG4|F_NN
Weird Indicator IMF PSBSFAD NFFCT|XDCG5|F_NN
Weird Indicator IMF PSBSFAD NFFCT|XDCG63F63_65W0|S1
Weird Indicator IMF PSBSFAD NFFCT|XDCG6X|F_NN
Weird Indicator IMF PSBSFAD NFFCT|XDCG6|F_NN
Weird Indicator IMF PSBSFAD NFFCT|XDCGGOB|_Z
Weird Indicator IMF PSBSFAD NFFCT|XDCGNLB|_Z
Weird Indicator IMF PSBSFAD NFFCT|XDCGNOB|_Z
Weird Indicator IMF PSBSFAD NPCO|XDCG23|_Z
Weird Indicator IMF PSBSFAD NPCO|XDCG4|F_NN
Weird Indicator IMF PSBSFAD NPCO|XDCG5|F_NN
Weird Indicator IMF PSBSFAD NPCO|XDCG63F63_65W0|S1
Weird Indicator IMF PSBSFAD NPCO|XDCG6X|F_NN
Weird Indicator IMF PSBSFAD NPCO|XDCG6|F_NN
Weird Indicator IMF PSBSFAD NPCO|XDCGGOB|_Z
Weird Indicator IMF PSBSFAD NPCO|XDCGNLB|_Z
Weird Indicator IMF PSBSFAD NPCO|XDCGNOB|_Z
Weird Indicator IMF PSBSFAD NPCSWF|XDCG23|_Z
Weird Indicator IMF PSBSFAD NPCSWF|XDCG4|F_NN
Weird Indicator IMF PSBSFAD NPCSWF|XDCG5|F_NN
Weird Indicator IMF PSBSFAD NPCSWF|XDCG63F63_65W0|S1
Weird Indicator IMF PSBSFAD NPCSWF|XDCG6X|F_NN
Weird Indicator IMF PSBSFAD NPCSWF|XDCG6|F_NN
Weird Indicator IMF PSBSFAD NPCSWF|XDCGGOB|_Z
Weird Indicator IMF PSBSFAD NPCSWF|XDCGNLB|_Z
Weird Indicator IMF PSBSFAD NPCSWF|XDCGNOB|_Z
Weird Indicator IMF PSBSFAD NPCT|XDCG23|_Z
Weird Indicator IMF PSBSFAD NPCT|XDCG4|F_NN
Weird Indicator IMF PSBSFAD NPCT|XDCG5|F_NN
Weird Indicator IMF PSBSFAD NPCT|XDCG63F63_65W0|S1
Weird Indicator IMF PSBSFAD NPCT|XDCG6X|F_NN
Weird Indicator IMF PSBSFAD NPCT|XDCG6|F_NN
Weird Indicator IMF PSBSFAD NPCT|XDCGGOB|_Z
Weird Indicator IMF PSBSFAD NPCT|XDCGNLB|_Z
Weird Indicator IMF PSBSFAD NPCT|XDCGNOB|_Z
Weird Indicator IMF PSBSFAD PS|XDCG23|_Z
Weird Indicator IMF PSBSFAD PS|XDCG4|F_NN
Weird Indicator IMF PSBSFAD PS|XDCG5|F_NN
Weird Indicator IMF PSBSFAD PS|XDCG63F63_65W0|S1
Weird Indicator IMF PSBSFAD PS|XDCG6X|F_NN
Weird Indicator IMF PSBSFAD PS|XDCG6|F_NN
Weird Indicator IMF PSBSFAD PS|XDCGGOB|_Z
Weird Indicator IMF PSBSFAD PS|XDCGNLB|_Z
Weird Indicator IMF PSBSFAD PS|XDCGNOB|_Z
Weird Indicator IMF PSBSFAD S1311XDCG23|_Z
Weird Indicator IMF PSBSFAD S1311XDCG4|F_NN
Weird Indicator IMF PSBSFAD S1311XDCG5|F_NN
Weird Indicator IMF PSBSFAD S1311XDCG63F63_65W0|S1
Weird Indicator IMF PSBSFAD S1311XDCG6X|F_NN
Weird Indicator IMF PSBSFAD S1311XDCG6|F_NN
Weird Indicator IMF PSBSFAD S1311XDCGGOB|_Z
Weird Indicator IMF PSBSFAD S1311XDCGNLB|_Z
Weird Indicator IMF PSBSFAD S1311XDCGNOB|_Z
Weird Indicator IMF PSBSFAD S1321XDCG23|_Z
Weird Indicator IMF PSBSFAD S1321XDCG4|F_NN
Weird Indicator IMF PSBSFAD S1321XDCG5|F_NN
Weird Indicator IMF PSBSFAD S1321XDCG63F63_65W0|S1
Weird Indicator IMF PSBSFAD S1321XDCG6X|F_NN
Weird Indicator IMF PSBSFAD S1321XDCG6|F_NN
Weird Indicator IMF PSBSFAD S1321XDCGGOB|_Z
Weird Indicator IMF PSBSFAD S1321XDCGNLB|_Z
Weird Indicator IMF PSBSFAD S1321XDCGNOB|_Z
Weird Indicator IMF PSBSFAD S13XDCG23|_Z
Weird Indicator IMF PSBSFAD S13XDCG4|F_NN
Weird Indicator IMF PSBSFAD S13XDCG5|F_NN
Weird Indicator IMF PSBSFAD S13XDCG63F63_65W0|S1
Weird Indicator IMF PSBSFAD S13XDCG6X|F_NN
Weird Indicator IMF PSBSFAD S13XDCG6|F_NN
Weird Indicator IMF PSBSFAD S13XDCGGOB|_Z
Weird Indicator IMF PSBSFAD S13XDCGNLB|_Z
Weird Indicator IMF PSBSFAD S13XDCGNOB|_Z
Weird Indicator IMF WoRLD All_Indicators
Weird Indicator IMF WoRLD RG_RM_GDP
Weird Indicator IMF WoRLD RS_RM_GDP
Weird Indicator IMF WoRLD RTGSE_RM_GDP
Weird Indicator IMF WoRLD RTGSGV_RM_GDP
Weird Indicator IMF WoRLD RTGSG_RM_GDP
Weird Indicator IMF WoRLD RTGS_RM_GDP
Weird Indicator IMF WoRLD RTIC_RM_GDP
Weird Indicator IMF WoRLD RTII_RM_GDP
Weird Indicator IMF WoRLD RTI_RM_GDP
Weird Indicator IMF WoRLD RTPAY_RM_GDP
Weird Indicator IMF WoRLD RTP_RM_GDP
Weird Indicator IMF WoRLD RTT_RM_GDP
Weird Indicator IMF WoRLD RT_RM_GDP
Weird Indicator IMF WoRLD R_RM_GDP

In [122]:
len(dataset_params['IMF']['BOP']['INDICATOR']), len(clean_d['IMF']['BOP']['INDICATOR'])

(6654, 2218)

In [123]:
clean_d['IMF']['CPI']['INDICATOR'] = {
    # 'PCPIA_IX': 'Clothing and footwear',
    # 'PCPIEC_PC_CP_A_PT': 'Communication, Percentage change, Previous year',
    # 'PCPIED_PC_CP_A_PT': 'Education, Percentage change, Previous year',
    'PCPI_PC_CP_A_PT': 'Consumer Price Index, All items, Percentage change, Previous year'
}
len(dataset_params['IMF']['CPI']['INDICATOR']), len(clean_d['IMF']['CPI']['INDICATOR'])

(178, 1)

In [124]:
dataset_params['IMF'].keys()

dict_keys(['BOP', 'CPI', 'FDI', 'FM', 'FSI', 'GENDER_EQUALITY', 'GFSMAB', 'HPDD', 'IFS', 'IRFCL', 'MFS', 'PGCS', 'PSBSFAD', 'WoRLD'])

In [125]:
len(dataset_params['IMF']['FSI']['INDICATOR']), len(clean_d['IMF']['FSI']['INDICATOR'])

(2453, 669)

In [126]:
len(dataset_params['IMF']['FDI']['INDICATOR']), len(clean_d['IMF']['FDI']['INDICATOR'])

(9, 9)

In [127]:
len(dataset_params['IMF']['CPI']['INDICATOR']), len(clean_d['IMF']['CPI']['INDICATOR'])

(178, 1)

In [128]:
len(dataset_params['IMF']['FSI']['INDICATOR']), len(clean_d['IMF']['FSI']['INDICATOR'])

(2453, 669)

In [129]:
count_dataset_d = {}
count_provider_d = {}
count_d = {}
for provider_id, provider_d in clean_d.items():
    count_d[provider_id] = {}
    count_dataset_d[provider_id] = {}
    v_provider = 0
    for dataset_id, dataset_d in provider_d.items():
        count_d[provider_id][dataset_id] = {}
        count_dataset_d[provider_id][dataset_id] = {}
        v_dataset = 1
        for param, param_d in dataset_d.items():
            v_dataset = v_dataset * len(param_d)
        
        count_dataset_d[provider_id][dataset_id] = v_dataset
        v_provider = v_provider + v_dataset
    count_provider_d[provider_id] = v_provider

count_provider_d

{'IMF': 4346, 'WB': 3266, 'BIS': 25944883500, 'UNCTAD': 69}

In [130]:
count_dataset_d['IMF']

{'BOP': 2218,
 'CPI': 1,
 'FDI': 9,
 'FM': 9,
 'FSI': 669,
 'GENDER_EQUALITY': 0,
 'GFSMAB': 560,
 'HPDD': 0,
 'IFS': 30,
 'IRFCL': 0,
 'MFS': 15,
 'PGCS': 4,
 'PSBSFAD': 831,
 'WoRLD': 0}

In [36]:
bop_indicators_d = dataset_params['IMF']['BOP']['INDICATOR']
format_indicators_d = {}

ind_template = {
    'DESCRIPTION' : '',
    'VERSION' : {},
    # 'SUBCATEGORY' : {},
    'CURRENCY': {},
    'OTHER': {}
}

for ind, descr in sorted(bop_indicators_d.items()):
    ind_sections = ind.split('_')
    descr_sections = descr.split(',')
    ind_id = ind_sections[0]
    ind_descr = ','.join(descr_sections[:-1])

    # if ind_id != 'BACK':
    #     continue

    # ind_sub = ''
    # for i in range(i, len(ind_id)):
    #     if ind_id[0:i] in format_indicators_d.keys():
    #         ind_sub = ind_id[i:]
    #         ind_id = ind_id[0:i]

    #         print('Sub Indicator:', ind_id, ind_sub)
    #         break
    #     else:
    #         continue

    if not ind_id in format_indicators_d.keys():
        format_indicators_d[ind_id] = ind_template

    # if ind_sub != '':
    desrc_ind = format_indicators_d[ind_id]['DESCRIPTION']
    descr_sub = ','.join(ind_descr).replace(desrc_ind, '')
    # format_indicators_d[ind_id]['SUBCATEGORY'][ind_sub] = descr_sub
    # else:

    if ind_descr == 'Total' and ind_id == 'BACK':
        print(ind, descr)
    format_indicators_d[ind_id]['DESCRIPTION'] = ind_descr

    if len(ind_sections) > 2:
        # print(ind_sections)
        for i in range(1, len(ind_sections)-1):
            ind_sect = ind_sections[i]

            if ind_sect == 'BP6':
                format_indicators_d[ind_id]['VERSION'][ind_sect] = ind_sect
            else:
                format_indicators_d[ind_id]['OTHER'][ind_sect] = [ind_sect]

    format_indicators_d[ind_id]['CURRENCY'][ind_sections[-1]] = descr_sections[-1]

    # break

format_indicators_d

{'BACK': {'DESCRIPTION': 'Total',
  'VERSION': {'BP6': 'BP6'},
  'CURRENCY': {'EUR': ' Euro',
   'USD': ' US Dollars',
   'XDC': ' National Currency'},
  'OTHER': {'SPE': ['SPE'],
   'MLT': ['MLT'],
   'S': ['S'],
   'L': ['L'],
   'CD': ['CD'],
   'DB': ['DB'],
   'NRES': ['NRES'],
   '1YOL': ['1YOL'],
   'CB': ['CB'],
   'FX': ['FX'],
   'EUR': ['EUR'],
   'JPY': ['JPY'],
   'OTH': ['OTH'],
   'USD': ['USD'],
   'NC': ['NC'],
   'UA': ['UA'],
   'GG': ['GG'],
   'ICL': ['ICL'],
   'ODC': ['ODC'],
   'OTSOFC': ['OTSOFC'],
   'OTSOTH': ['OTSOTH'],
   'OTS': ['OTS'],
   'NV': ['NV'],
   'I': ['I'],
   'SDR': ['SDR'],
   'X': ['X'],
   'CL': ['CL'],
   'DS': ['DS'],
   'D': ['D'],
   'OL': ['OL'],
   'O': ['O'],
   'RL': ['RL']}},
 'BAXEF': {'DESCRIPTION': 'Total',
  'VERSION': {'BP6': 'BP6'},
  'CURRENCY': {'EUR': ' Euro',
   'USD': ' US Dollars',
   'XDC': ' National Currency'},
  'OTHER': {'SPE': ['SPE'],
   'MLT': ['MLT'],
   'S': ['S'],
   'L': ['L'],
   'CD': ['CD'],
   'DB': ['DB'],
   'NRES': ['NRES'],
   '1YOL': ['1YOL'],
   'CB': ['CB'],
   'FX': ['FX'],
   'EUR': ['EUR'],
   'JPY': ['JPY'],
   'OTH': ['OTH'],
   'USD': ['USD'],
   'NC': ['NC'],
   'UA': ['UA'],
   'GG': ['GG'],
   'ICL': ['ICL'],
   'ODC': ['ODC'],
   'OTSOFC': ['OTSOFC'],
   'OTSOTH': ['OTSOTH'],
   'OTS': ['OTS'],
   'NV': ['NV'],
   'I': ['I'],
   'SDR': ['SDR'],
   'X': ['X'],
   'CL': ['CL'],
   'DS': ['DS'],
   'D': ['D'],
   'OL': ['OL'],
   'O': ['O'],
   'RL': ['RL']}},
 'BCAXF': {'DESCRIPTION': 'Total',
  'VERSION': {'BP6': 'BP6'},
  'CURRENCY': {'EUR': ' Euro',
   'USD': ' US Dollars',
   'XDC': ' National Currency'},
  'OTHER': {'SPE': ['SPE'],
   'MLT': ['MLT'],
   'S': ['S'],
   'L': ['L'],
   'CD': ['CD'],
   'DB': ['DB'],
   'NRES': ['NRES'],
   '1YOL': ['1YOL'],
   'CB': ['CB'],
   'FX': ['FX'],
   'EUR': ['EUR'],
   'JPY': ['JPY'],
   'OTH': ['OTH'],
   'USD': ['USD'],
   'NC': ['NC'],
   'UA': ['UA'],
   'GG': ['GG'],
   'ICL': ['ICL'],
   'ODC': ['ODC'],
   'OTSOFC': ['OTSOFC'],
   'OTSOTH': ['OTSOTH'],
   'OTS': ['OTS'],
   'NV': ['NV'],
   'I': ['I'],
   'SDR': ['SDR'],
   'X': ['X'],
   'CL': ['CL'],
   'DS': ['DS'],
   'D': ['D'],
   'OL': ['OL'],
   'O': ['O'],
   'RL': ['RL']}},
 'BCA': {'DESCRIPTION': 'Total',
  'VERSION': {'BP6': 'BP6'},
  'CURRENCY': {'EUR': ' Euro',
   'USD': ' US Dollars',
   'XDC': ' National Currency'},
  'OTHER': {'SPE': ['SPE'],
   'MLT': ['MLT'],
   'S': ['S'],
   'L': ['L'],
   'CD': ['CD'],
   'DB': ['DB'],
   'NRES': ['NRES'],
   '1YOL': ['1YOL'],
   'CB': ['CB'],
   'FX': ['FX'],
   'EUR': ['EUR'],
   'JPY': ['JPY'],
   'OTH': ['OTH'],
   'USD': ['USD'],
   'NC': ['NC'],
   'UA': ['UA'],
   'GG': ['GG'],
   'ICL': ['ICL'],
   'ODC': ['ODC'],
   'OTSOFC': ['OTSOFC'],
   'OTSOTH': ['OTSOTH'],
   'OTS': ['OTS'],
   'NV': ['NV'],
   'I': ['I'],
   'SDR': ['SDR'],
   'X': ['X'],
   'CL': ['CL'],
   'DS': ['DS'],
   'D': ['D'],
   'OL': ['OL'],
   'O': ['O'],
   'RL': ['RL']}},
 'BEFDDAAI': {'DESCRIPTION': 'Total',
  'VERSION': {'BP6': 'BP6'},
  'CURRENCY': {'EUR': ' Euro',
   'USD': ' US Dollars',
   'XDC': ' National Currency'},
  'OTHER': {'SPE': ['SPE'],
   'MLT': ['MLT'],
   'S': ['S'],
   'L': ['L'],
   'CD': ['CD'],
   'DB': ['DB'],
   'NRES': ['NRES'],
   '1YOL': ['1YOL'],
   'CB': ['CB'],
   'FX': ['FX'],
   'EUR': ['EUR'],
   'JPY': ['JPY'],
   'OTH': ['OTH'],
   'USD': ['USD'],
   'NC': ['NC'],
   'UA': ['UA'],
   'GG': ['GG'],
   'ICL': ['ICL'],
   'ODC': ['ODC'],
   'OTSOFC': ['OTSOFC'],
   'OTSOTH': ['OTSOTH'],
   'OTS': ['OTS'],
   'NV': ['NV'],
   'I': ['I'],
   'SDR': ['SDR'],
   'X': ['X'],
   'CL': ['CL'],
   'DS': ['DS'],
   'D': ['D'],
   'OL': ['OL'],
   'O': ['O'],
   'RL': ['RL']}},
 'BEFDDAAPI': {'DESCRIPTION': 'Total',
  'VERSION': {'BP6': 'BP6'},
  'CURRENCY': {'EUR': ' Euro',
   'USD': ' US Dollars',
   'XDC': ' National Currency'},
  'OTHER': {'SPE': ['SPE'],
   'MLT': ['MLT'],
   'S': ['S'],
   'L': ['L'],
   'CD': ['CD'],
   'DB': ['DB'],
   'NRES': ['NRES'],
   '1YOL': ['1YOL'],
   'CB': ['CB'],
   'FX': ['FX'],
   'EUR': ['EUR'],
   'JPY': ['JPY'],
   'OTH': ['OTH'],
   'USD': ['USD'],
   'NC': ['NC'],
   'UA': ['UA'],
   'GG': ['GG'],
   'ICL': ['ICL'],
   'ODC': ['ODC'],
   'OTSOFC': ['OTSOFC'],
   'OTSOTH': ['OTSOTH'],
   'OTS': ['OTS'],
   'NV': ['NV'],
   'I': ['I'],
   'SDR': ['SDR'],
   'X': ['X'],
   'CL': ['CL'],
   'DS': ['DS'],
   'D': ['D'],
   'OL': ['OL'],
   'O': ['O'],
   'RL': ['RL']}},
 'BEFDDAAP': {'DESCRIPTION': 'Total',
  'VERSION': {'BP6': 'BP6'},
  'CURRENCY': {'EUR': ' Euro',
   'USD': ' US Dollars',
   'XDC': ' National Currency'},
  'OTHER': {'SPE': ['SPE'],
   'MLT': ['MLT'],
   'S': ['S'],
   'L': ['L'],
   'CD': ['CD'],
   'DB': ['DB'],
   'NRES': ['NRES'],
   '1YOL': ['1YOL'],
   'CB': ['CB'],
   'FX': ['FX'],
   'EUR': ['EUR'],
   'JPY': ['JPY'],
   'OTH': ['OTH'],
   'USD': ['USD'],
   'NC': ['NC'],
   'UA': ['UA'],
   'GG': ['GG'],
   'ICL': ['ICL'],
   'ODC': ['ODC'],
   'OTSOFC': ['OTSOFC'],
   'OTSOTH': ['OTSOTH'],
   'OTS': ['OTS'],
   'NV': ['NV'],
   'I': ['I'],
   'SDR': ['SDR'],
   'X': ['X'],
   'CL': ['CL'],
   'DS': ['DS'],
   'D': ['D'],
   'OL': ['OL'],
   'O': ['O'],
   'RL': ['RL']}},
 'BEFDDAA': {'DESCRIPTION': 'Total',
  'VERSION': {'BP6': 'BP6'},
  'CURRENCY': {'EUR': ' Euro',
   'USD': ' US Dollars',
   'XDC': ' National Currency'},
  'OTHER': {'SPE': ['SPE'],
   'MLT': ['MLT'],
   'S': ['S'],
   'L': ['L'],
   'CD': ['CD'],
   'DB': ['DB'],
   'NRES': ['NRES'],
   '1YOL': ['1YOL'],
   'CB': ['CB'],
   'FX': ['FX'],
   'EUR': ['EUR'],
   'JPY': ['JPY'],
   'OTH': ['OTH'],
   'USD': ['USD'],
   'NC': ['NC'],
   'UA': ['UA'],
   'GG': ['GG'],
   'ICL': ['ICL'],
   'ODC': ['ODC'],
   'OTSOFC': ['OTSOFC'],
   'OTSOTH': ['OTSOTH'],
   'OTS': ['OTS'],
   'NV': ['NV'],
   'I': ['I'],
   'SDR': ['SDR'],
   'X': ['X'],
   'CL': ['CL'],
   'DS': ['DS'],
   'D': ['D'],
   'OL': ['OL'],
   'O': ['O'],
   'RL': ['RL']}},
 'BEFDDCAI': {'DESCRIPTION': 'Total',
  'VERSION': {'BP6': 'BP6'},
  'CURRENCY': {'EUR': ' Euro',
   'USD': ' US Dollars',
   'XDC': ' National Currency'},
  'OTHER': {'SPE': ['SPE'],
   'MLT': ['MLT'],
   'S': ['S'],
   'L': ['L'],
   'CD': ['CD'],
   'DB': ['DB'],
   'NRES': ['NRES'],
   '1YOL': ['1YOL'],
   'CB': ['CB'],
   'FX': ['FX'],
   'EUR': ['EUR'],
   'JPY': ['JPY'],
   'OTH': ['OTH'],
   'USD': ['USD'],
   'NC': ['NC'],
   'UA': ['UA'],
   'GG': ['GG'],
   'ICL': ['ICL'],
   'ODC': ['ODC'],
   'OTSOFC': ['OTSOFC'],
   'OTSOTH': ['OTSOTH'],
   'OTS': ['OTS'],
   'NV': ['NV'],
   'I': ['I'],
   'SDR': ['SDR'],
   'X': ['X'],
   'CL': ['CL'],
   'DS': ['DS'],
   'D': ['D'],
   'OL': ['OL'],
   'O': ['O'],
   'RL': ['RL']}},
 'BEFDDCAP': {'DESCRIPTION': 'Total',
  'VERSION': {'BP6': 'BP6'},
  'CURRENCY': {'EUR': ' Euro',
   'USD': ' US Dollars',
   'XDC': ' National Currency'},
  'OTHER': {'SPE': ['SPE'],
   'MLT': ['MLT'],
   'S': ['S'],
   'L': ['L'],
   'CD': ['CD'],
   'DB': ['DB'],
   'NRES': ['NRES'],
   '1YOL': ['1YOL'],
   'CB': ['CB'],
   'FX': ['FX'],
   'EUR': ['EUR'],
   'JPY': ['JPY'],
   'OTH': ['OTH'],
   'USD': ['USD'],
   'NC': ['NC'],
   'UA': ['UA'],
   'GG': ['GG'],
   'ICL': ['ICL'],
   'ODC': ['ODC'],
   'OTSOFC': ['OTSOFC'],
   'OTSOTH': ['OTSOTH'],
   'OTS': ['OTS'],
   'NV': ['NV'],
   'I': ['I'],
   'SDR': ['SDR'],
   'X': ['X'],
   'CL': ['CL'],
   'DS': ['DS'],
   'D': ['D'],
   'OL': ['OL'],
   'O': ['O'],
   'RL': ['RL']}},
 'BEFDDCA': {'DESCRIPTION': 'Total',
  'VERSION': {'BP6': 'BP6'},
  'CURRENCY': {'EUR': ' Euro',
   'USD': ' US Dollars',
   'XDC': ' National Currency'},
  'OTHER': {'SPE': ['SPE'],
   'MLT': ['MLT'],
   'S': ['S'],
   'L': ['L'],
   'CD': ['CD'],
   'DB': ['DB'],
   'NRES': ['NRES'],
   '1YOL': ['1YOL'],
   'CB': ['CB'],
   'FX': ['FX'],
   'EUR': ['EUR'],
   'JPY': ['JPY'],
   'OTH': ['OTH'],
   'USD': ['USD'],
   'NC': ['NC'],
   'UA': ['UA'],
   'GG': ['GG'],
   'ICL': ['ICL'],
   'ODC': ['ODC'],
   'OTSOFC': ['OTSOFC'],
   'OTSOTH': ['OTSOTH'],
   'OTS': ['OTS'],
   'NV': ['NV'],
   'I': ['I'],
   'SDR': ['SDR'],
   'X': ['X'],
   'CL': ['CL'],
   'DS': ['DS'],
   'D': ['D'],
   'OL': ['OL'],
   'O': ['O'],
   'RL': ['RL']}},
 'BEFDDRAI': {'DESCRIPTION': 'Total',
  'VERSION': {'BP6': 'BP6'},
  'CURRENCY': {'EUR': ' Euro',
   'USD': ' US Dollars',
   'XDC': ' National Currency'},
  'OTHER': {'SPE': ['SPE'],
   'MLT': ['MLT'],
   'S': ['S'],
   'L': ['L'],
   'CD': ['CD'],
   'DB': ['DB'],
   'NRES': ['NRES'],
   '1YOL': ['1YOL'],
   'CB': ['CB'],
   'FX': ['FX'],
   'EUR': ['EUR'],
   'JPY': ['JPY'],
   'OTH': ['OTH'],
   'USD': ['USD'],
   'NC': ['NC'],
   'UA': ['UA'],
   'GG': ['GG'],
   'ICL': ['ICL'],
   'ODC': ['ODC'],
   'OTSOFC': ['OTSOFC'],
   'OTSOTH': ['OTSOTH'],
   'OTS': ['OTS'],
   'NV': ['NV'],
   'I': ['I'],
   'SDR': ['SDR'],
   'X': ['X'],
   'CL': ['CL'],
   'DS': ['DS'],
   'D': ['D'],
   'OL': ['OL'],
   'O': ['O'],
   'RL': ['RL']}},
 'BEFDDRAP': {'DESCRIPTION': 'Total',
  'VERSION': {'BP6': 'BP6'},
  'CURRENCY': {'EUR': ' Euro',
   'USD': ' US Dollars',
   'XDC': ' National Currency'},
  'OTHER': {'SPE': ['SPE'],
   'MLT': ['MLT'],
   'S': ['S'],
   'L': ['L'],
   'CD': ['CD'],
   'DB': ['DB'],
   'NRES': ['NRES'],
   '1YOL': ['1YOL'],
   'CB': ['CB'],
   'FX': ['FX'],
   'EUR': ['EUR'],
   'JPY': ['JPY'],
   'OTH': ['OTH'],
   'USD': ['USD'],
   'NC': ['NC'],
   'UA': ['UA'],
   'GG': ['GG'],
   'ICL': ['ICL'],
   'ODC': ['ODC'],
   'OTSOFC': ['OTSOFC'],
   'OTSOTH': ['OTSOTH'],
   'OTS': ['OTS'],
   'NV': ['NV'],
   'I': ['I'],
   'SDR': ['SDR'],
   'X': ['X'],
   'CL': ['CL'],
   'DS': ['DS'],
   'D': ['D'],
   'OL': ['OL'],
   'O': ['O'],
   'RL': ['RL']}},
 'BEFDDRA': {'DESCRIPTION': 'Total',
  'VERSION': {'BP6': 'BP6'},
  'CURRENCY': {'EUR': ' Euro',
   'USD': ' US Dollars',
   'XDC': ' National Currency'},
  'OTHER': {'SPE': ['SPE'],
   'MLT': ['MLT'],
   'S': ['S'],
   'L': ['L'],
   'CD': ['CD'],
   'DB': ['DB'],
   'NRES': ['NRES'],
   '1YOL': ['1YOL'],
   'CB': ['CB'],
   'FX': ['FX'],
   'EUR': ['EUR'],
   'JPY': ['JPY'],
   'OTH': ['OTH'],
   'USD': ['USD'],
   'NC': ['NC'],
   'UA': ['UA'],
   'GG': ['GG'],
   'ICL': ['ICL'],
   'ODC': ['ODC'],
   'OTSOFC': ['OTSOFC'],
   'OTSOTH': ['OTSOTH'],
   'OTS': ['OTS'],
   'NV': ['NV'],
   'I': ['I'],
   'SDR': ['SDR'],
   'X': ['X'],
   'CL': ['CL'],
   'DS': ['DS'],
   'D': ['D'],
   'OL': ['OL'],
   'O': ['O'],
   'RL': ['RL']}},
 'BEFDDRPI': {'DESCRIPTION': 'Total',
  'VERSION': {'BP6': 'BP6'},
  'CURRENCY': {'EUR': ' Euro',
   'USD': ' US Dollars',
   'XDC': ' National Currency'},
  'OTHER': {'SPE': ['SPE'],
   'MLT': ['MLT'],
   'S': ['S'],
   'L': ['L'],
   'CD': ['CD'],
   'DB': ['DB'],
   'NRES': ['NRES'],
   '1YOL': ['1YOL'],
   'CB': ['CB'],
   'FX': ['FX'],
   'EUR': ['EUR'],
   'JPY': ['JPY'],
   'OTH': ['OTH'],
   'USD': ['USD'],
   'NC': ['NC'],
   'UA': ['UA'],
   'GG': ['GG'],
   'ICL': ['ICL'],
   'ODC': ['ODC'],
   'OTSOFC': ['OTSOFC'],
   'OTSOTH': ['OTSOTH'],
   'OTS': ['OTS'],
   'NV': ['NV'],
   'I': ['I'],
   'SDR': ['SDR'],
   'X': ['X'],
   'CL': ['CL'],
   'DS': ['DS'],
   'D': ['D'],
   'OL': ['OL'],
   'O': ['O'],
   'RL': ['RL']}},
 'BEFDDRPP': {'DESCRIPTION': 'Total',
  'VERSION': {'BP6': 'BP6'},
  'CURRENCY': {'EUR': ' Euro',
   'USD': ' US Dollars',
   'XDC': ' National Currency'},
  'OTHER': {'SPE': ['SPE'],
   'MLT': ['MLT'],
   'S': ['S'],
   'L': ['L'],
   'CD': ['CD'],
   'DB': ['DB'],
   'NRES': ['NRES'],
   '1YOL': ['1YOL'],
   'CB': ['CB'],
   'FX': ['FX'],
   'EUR': ['EUR'],
   'JPY': ['JPY'],
   'OTH': ['OTH'],
   'USD': ['USD'],
   'NC': ['NC'],
   'UA': ['UA'],
   'GG': ['GG'],
   'ICL': ['ICL'],
   'ODC': ['ODC'],
   'OTSOFC': ['OTSOFC'],
   'OTSOTH': ['OTSOTH'],
   'OTS': ['OTS'],
   'NV': ['NV'],
   'I': ['I'],
   'SDR': ['SDR'],
   'X': ['X'],
   'CL': ['CL'],
   'DS': ['DS'],
   'D': ['D'],
   'OL': ['OL'],
   'O': ['O'],
   'RL': ['RL']}},
 'BEFDDRP': {'DESCRIPTION': 'Total',
  'VERSION': {'BP6': 'BP6'},
  'CURRENCY': {'EUR': ' Euro',
   'USD': ' US Dollars',
   'XDC': ' National Currency'},
  'OTHER': {'SPE': ['SPE'],
   'MLT': ['MLT'],
   'S': ['S'],
   'L': ['L'],
   'CD': ['CD'],
   'DB': ['DB'],
   'NRES': ['NRES'],
   '1YOL': ['1YOL'],
   'CB': ['CB'],
   'FX': ['FX'],
   'EUR': ['EUR'],
   'JPY': ['JPY'],
   'OTH': ['OTH'],
   'USD': ['USD'],
   'NC': ['NC'],
   'UA': ['UA'],
   'GG': ['GG'],
   'ICL': ['ICL'],
   'ODC': ['ODC'],
   'OTSOFC': ['OTSOFC'],
   'OTSOTH': ['OTSOTH'],
   'OTS': ['OTS'],
   'NV': ['NV'],
   'I': ['I'],
   'SDR': ['SDR'],
   'X': ['X'],
   'CL': ['CL'],
   'DS': ['DS'],
   'D': ['D'],
   'OL': ['OL'],
   'O': ['O'],
   'RL': ['RL']}},
 'BEFDDSAI': {'DESCRIPTION': 'Total',
  'VERSION': {'BP6': 'BP6'},
  'CURRENCY': {'EUR': ' Euro',
   'USD': ' US Dollars',
   'XDC': ' National Currency'},
  'OTHER': {'SPE': ['SPE'],
   'MLT': ['MLT'],
   'S': ['S'],
   'L': ['L'],
   'CD': ['CD'],
   'DB': ['DB'],
   'NRES': ['NRES'],
   '1YOL': ['1YOL'],
   'CB': ['CB'],
   'FX': ['FX'],
   'EUR': ['EUR'],
   'JPY': ['JPY'],
   'OTH': ['OTH'],
   'USD': ['USD'],
   'NC': ['NC'],
   'UA': ['UA'],
   'GG': ['GG'],
   'ICL': ['ICL'],
   'ODC': ['ODC'],
   'OTSOFC': ['OTSOFC'],
   'OTSOTH': ['OTSOTH'],
   'OTS': ['OTS'],
   'NV': ['NV'],
   'I': ['I'],
   'SDR': ['SDR'],
   'X': ['X'],
   'CL': ['CL'],
   'DS': ['DS'],
   'D': ['D'],
   'OL': ['OL'],
   'O': ['O'],
   'RL': ['RL']}},
 'BEFDDSAP': {'DESCRIPTION': 'Total',
  'VERSION': {'BP6': 'BP6'},
  'CURRENCY': {'EUR': ' Euro',
   'USD': ' US Dollars',
   'XDC': ' National Currency'},
  'OTHER': {'SPE': ['SPE'],
   'MLT': ['MLT'],
   'S': ['S'],
   'L': ['L'],
   'CD': ['CD'],
   'DB': ['DB'],
   'NRES': ['NRES'],
   '1YOL': ['1YOL'],
   'CB': ['CB'],
   'FX': ['FX'],
   'EUR': ['EUR'],
   'JPY': ['JPY'],
   'OTH': ['OTH'],
   'USD': ['USD'],
   'NC': ['NC'],
   'UA': ['UA'],
   'GG': ['GG'],
   'ICL': ['ICL'],
   'ODC': ['ODC'],
   'OTSOFC': ['OTSOFC'],
   'OTSOTH': ['OTSOTH'],
   'OTS': ['OTS'],
   'NV': ['NV'],
   'I': ['I'],
   'SDR': ['SDR'],
   'X': ['X'],
   'CL': ['CL'],
   'DS': ['DS'],
   'D': ['D'],
   'OL': ['OL'],
   'O': ['O'],
   'RL': ['RL']}},
 'BEFDDSA': {'DESCRIPTION': 'Total',
  'VERSION': {'BP6': 'BP6'},
  'CURRENCY': {'EUR': ' Euro',
   'USD': ' US Dollars',
   'XDC': ' National Currency'},
  'OTHER': {'SPE': ['SPE'],
   'MLT': ['MLT'],
   'S': ['S'],
   'L': ['L'],
   'CD': ['CD'],
   'DB': ['DB'],
   'NRES': ['NRES'],
   '1YOL': ['1YOL'],
   'CB': ['CB'],
   'FX': ['FX'],
   'EUR': ['EUR'],
   'JPY': ['JPY'],
   'OTH': ['OTH'],
   'USD': ['USD'],
   'NC': ['NC'],
   'UA': ['UA'],
   'GG': ['GG'],
   'ICL': ['ICL'],
   'ODC': ['ODC'],
   'OTSOFC': ['OTSOFC'],
   'OTSOTH': ['OTSOTH'],
   'OTS': ['OTS'],
   'NV': ['NV'],
   'I': ['I'],
   'SDR': ['SDR'],
   'X': ['X'],
   'CL': ['CL'],
   'DS': ['DS'],
   'D': ['D'],
   'OL': ['OL'],
   'O': ['O'],
   'RL': ['RL']}},
 'BEFDD': {'DESCRIPTION': 'Total',
  'VERSION': {'BP6': 'BP6'},
  'CURRENCY': {'EUR': ' Euro',
   'USD': ' US Dollars',
   'XDC': ' National Currency'},
  'OTHER': {'SPE': ['SPE'],
   'MLT': ['MLT'],
   'S': ['S'],
   'L': ['L'],
   'CD': ['CD'],
   'DB': ['DB'],
   'NRES': ['NRES'],
   '1YOL': ['1YOL'],
   'CB': ['CB'],
   'FX': ['FX'],
   'EUR': ['EUR'],
   'JPY': ['JPY'],
   'OTH': ['OTH'],
   'USD': ['USD'],
   'NC': ['NC'],
   'UA': ['UA'],
   'GG': ['GG'],
   'ICL': ['ICL'],
   'ODC': ['ODC'],
   'OTSOFC': ['OTSOFC'],
   'OTSOTH': ['OTSOTH'],
   'OTS': ['OTS'],
   'NV': ['NV'],
   'I': ['I'],
   'SDR': ['SDR'],
   'X': ['X'],
   'CL': ['CL'],
   'DS': ['DS'],
   'D': ['D'],
   'OL': ['OL'],
   'O': ['O'],
   'RL': ['RL']}},
 'BEFDE': {'DESCRIPTION': 'Total',
  'VERSION': {'BP6': 'BP6'},
  'CURRENCY': {'EUR': ' Euro',
   'USD': ' US Dollars',
   'XDC': ' National Currency'},
  'OTHER': {'SPE': ['SPE'],
   'MLT': ['MLT'],
   'S': ['S'],
   'L': ['L'],
   'CD': ['CD'],
   'DB': ['DB'],
   'NRES': ['NRES'],
   '1YOL': ['1YOL'],
   'CB': ['CB'],
   'FX': ['FX'],
   'EUR': ['EUR'],
   'JPY': ['JPY'],
   'OTH': ['OTH'],
   'USD': ['USD'],
   'NC': ['NC'],
   'UA': ['UA'],
   'GG': ['GG'],
   'ICL': ['ICL'],
   'ODC': ['ODC'],
   'OTSOFC': ['OTSOFC'],
   'OTSOTH': ['OTSOTH'],
   'OTS': ['OTS'],
   'NV': ['NV'],
   'I': ['I'],
   'SDR': ['SDR'],
   'X': ['X'],
   'CL': ['CL'],
   'DS': ['DS'],
   'D': ['D'],
   'OL': ['OL'],
   'O': ['O'],
   'RL': ['RL']}},
 'BEFD': {'DESCRIPTION': 'Total',
  'VERSION': {'BP6': 'BP6'},
  'CURRENCY': {'EUR': ' Euro',
   'USD': ' US Dollars',
   'XDC': ' National Currency'},
  'OTHER': {'SPE': ['SPE'],
   'MLT': ['MLT'],
   'S': ['S'],
   'L': ['L'],
   'CD': ['CD'],
   'DB': ['DB'],
   'NRES': ['NRES'],
   '1YOL': ['1YOL'],
   'CB': ['CB'],
   'FX': ['FX'],
   'EUR': ['EUR'],
   'JPY': ['JPY'],
   'OTH': ['OTH'],
   'USD': ['USD'],
   'NC': ['NC'],
   'UA': ['UA'],
   'GG': ['GG'],
   'ICL': ['ICL'],
   'ODC': ['ODC'],
   'OTSOFC': ['OTSOFC'],
   'OTSOTH': ['OTSOTH'],
   'OTS': ['OTS'],
   'NV': ['NV'],
   'I': ['I'],
   'SDR': ['SDR'],
   'X': ['X'],
   'CL': ['CL'],
   'DS': ['DS'],
   'D': ['D'],
   'OL': ['OL'],
   'O': ['O'],
   'RL': ['RL']}},
 'BEFISGIMF': {'DESCRIPTION': 'Total',
  'VERSION': {'BP6': 'BP6'},
  'CURRENCY': {'EUR': ' Euro',
   'USD': ' US Dollars',
   'XDC': ' National Currency'},
  'OTHER': {'SPE': ['SPE'],
   'MLT': ['MLT'],
   'S': ['S'],
   'L': ['L'],
   'CD': ['CD'],
   'DB': ['DB'],
   'NRES': ['NRES'],
   '1YOL': ['1YOL'],
   'CB': ['CB'],
   'FX': ['FX'],
   'EUR': ['EUR'],
   'JPY': ['JPY'],
   'OTH': ['OTH'],
   'USD': ['USD'],
   'NC': ['NC'],
   'UA': ['UA'],
   'GG': ['GG'],
   'ICL': ['ICL'],
   'ODC': ['ODC'],
   'OTSOFC': ['OTSOFC'],
   'OTSOTH': ['OTSOTH'],
   'OTS': ['OTS'],
   'NV': ['NV'],
   'I': ['I'],
   'SDR': ['SDR'],
   'X': ['X'],
   'CL': ['CL'],
   'DS': ['DS'],
   'D': ['D'],
   'OL': ['OL'],
   'O': ['O'],
   'RL': ['RL']}},
 'BEFISIG': {'DESCRIPTION': 'Total',
  'VERSION': {'BP6': 'BP6'},
  'CURRENCY': {'EUR': ' Euro',
   'USD': ' US Dollars',
   'XDC': ' National Currency'},
  'OTHER': {'SPE': ['SPE'],
   'MLT': ['MLT'],
   'S': ['S'],
   'L': ['L'],
   'CD': ['CD'],
   'DB': ['DB'],
   'NRES': ['NRES'],
   '1YOL': ['1YOL'],
   'CB': ['CB'],
   'FX': ['FX'],
   'EUR': ['EUR'],
   'JPY': ['JPY'],
   'OTH': ['OTH'],
   'USD': ['USD'],
   'NC': ['NC'],
   'UA': ['UA'],
   'GG': ['GG'],
   'ICL': ['ICL'],
   'ODC': ['ODC'],
   'OTSOFC': ['OTSOFC'],
   'OTSOTH': ['OTSOTH'],
   'OTS': ['OTS'],
   'NV': ['NV'],
   'I': ['I'],
   'SDR': ['SDR'],
   'X': ['X'],
   'CL': ['CL'],
   'DS': ['DS'],
   'D': ['D'],
   'OL': ['OL'],
   'O': ['O'],
   'RL': ['RL']}},
 'BEFIS': {'DESCRIPTION': 'Total',
  'VERSION': {'BP6': 'BP6'},
  'CURRENCY': {'EUR': ' Euro',
   'USD': ' US Dollars',
   'XDC': ' National Currency'},
  'OTHER': {'SPE': ['SPE'],
   'MLT': ['MLT'],
   'S': ['S'],
   'L': ['L'],
   'CD': ['CD'],
   'DB': ['DB'],
   'NRES': ['NRES'],
   '1YOL': ['1YOL'],
   'CB': ['CB'],
   'FX': ['FX'],
   'EUR': ['EUR'],
   'JPY': ['JPY'],
   'OTH': ['OTH'],
   'USD': ['USD'],
   'NC': ['NC'],
   'UA': ['UA'],
   'GG': ['GG'],
   'ICL': ['ICL'],
   'ODC': ['ODC'],
   'OTSOFC': ['OTSOFC'],
   'OTSOTH': ['OTSOTH'],
   'OTS': ['OTS'],
   'NV': ['NV'],
   'I': ['I'],
   'SDR': ['SDR'],
   'X': ['X'],
   'CL': ['CL'],
   'DS': ['DS'],
   'D': ['D'],
   'OL': ['OL'],
   'O': ['O'],
   'RL': ['RL']}},
 'BEFOE': {'DESCRIPTION': 'Total',
  'VERSION': {'BP6': 'BP6'},
  'CURRENCY': {'EUR': ' Euro',
   'USD': ' US Dollars',
   'XDC': ' National Currency'},
  'OTHER': {'SPE': ['SPE'],
   'MLT': ['MLT'],
   'S': ['S'],
   'L': ['L'],
   'CD': ['CD'],
   'DB': ['DB'],
   'NRES': ['NRES'],
   '1YOL': ['1YOL'],
   'CB': ['CB'],
   'FX': ['FX'],
   'EUR': ['EUR'],
   'JPY': ['JPY'],
   'OTH': ['OTH'],
   'USD': ['USD'],
   'NC': ['NC'],
   'UA': ['UA'],
   'GG': ['GG'],
   'ICL': ['ICL'],
   'ODC': ['ODC'],
   'OTSOFC': ['OTSOFC'],
   'OTSOTH': ['OTSOTH'],
   'OTS': ['OTS'],
   'NV': ['NV'],
   'I': ['I'],
   'SDR': ['SDR'],
   'X': ['X'],
   'CL': ['CL'],
   'DS': ['DS'],
   'D': ['D'],
   'OL': ['OL'],

In [37]:
format_indicators_d['BACK']

{'DESCRIPTION': 'Total',
 'VERSION': {'BP6': 'BP6'},
 'CURRENCY': {'EUR': ' Euro',
  'USD': ' US Dollars',
  'XDC': ' National Currency'},
 'OTHER': {'SPE': ['SPE'],
  'MLT': ['MLT'],
  'S': ['S'],
  'L': ['L'],
  'CD': ['CD'],
  'DB': ['DB'],
  'NRES': ['NRES'],
  '1YOL': ['1YOL'],
  'CB': ['CB'],
  'FX': ['FX'],
  'EUR': ['EUR'],
  'JPY': ['JPY'],
  'OTH': ['OTH'],
  'USD': ['USD'],
  'NC': ['NC'],
  'UA': ['UA'],
  'GG': ['GG'],
  'ICL': ['ICL'],
  'ODC': ['ODC'],
  'OTSOFC': ['OTSOFC'],
  'OTSOTH': ['OTSOTH'],
  'OTS': ['OTS'],
  'NV': ['NV'],
  'I': ['I'],
  'SDR': ['SDR'],
  'X': ['X'],
  'CL': ['CL'],
  'DS': ['DS'],
  'D': ['D'],
  'OL': ['OL'],
  'O': ['O'],
  'RL': ['RL']}}

In [ ]:
new_d = {}
for provider_id, provider_d in dataset_params.items():
    new_d[provider_id] = {}
    for dataset_id, dataset_d in provider_d.items():
        new_d[provider_id][dataset_id] = {}
        for param, param_d in dataset_d.items():
            new_d[provider_id][dataset_id][param] = {}

            new_param_d = {}
            for k, v in param_d.items():
                if (k[-4:] == '_EUR' or k[-4:] == '_XDC') and (k[:-4] + '_USD') in param_d.keys():
                    pass
                else:
                    new_param_d[k] = v

            new_d[provider_id][dataset_id][param] = new_param_d

In [ ]:
count_dataset_d = {}
count_d = {}
for provider_id, provider_d in new_d.items():
    count_d[provider_id] = {}
    count_dataset_d[provider_id] = {}
    for dataset_id, dataset_d in provider_d.items():
        count_d[provider_id][dataset_id] = {}
        count_dataset_d[provider_id][dataset_id] = {}
        v = 1
        for param, param_d in dataset_d.items():
            v = v * len(new_d[provider_id][dataset_id][param])
        
        count_dataset_d[provider_id][dataset_id] = v

In [ ]:
import json

json_str = json.dumps(new_d, indent=4)
with open(config.METADATA_DIR / 'datasets_dimensions.json', 'w') as f:
    f.write(json_str)

In [ ]:
count_dataset_d = {}
count_d = {}
for provider_id, provider_d in new_d.items():
    count_d[provider_id] = {}
    count_dataset_d[provider_id] = {}
    for dataset_id, dataset_d in provider_d.items():
        count_d[provider_id][dataset_id] = {}
        count_dataset_d[provider_id][dataset_id] = {}
        v = 1
        for param, param_d in dataset_d.items():
            v = v * len(new_d[provider_id][dataset_id][param])
        
        count_dataset_d[provider_id][dataset_id] = v

In [ ]:
count_d

{'IMF': {'BOP': {'INDICATOR': 2218},
  'CPI': {'INDICATOR': 178},
  'FDI': {'INDICATOR': 9},
  'FM': {'INDICATOR': 9},
  'FSI': {'INDICATOR': 959},
  'GENDER_EQUALITY': {'INDICATOR': 3},
  'GFSMAB': {'CLASSIFICATION': 35, 'REF_SECTOR': 8, 'UNIT_MEASURE': 2},
  'HPDD': {'INDICATOR': 1},
  'IFS': {'INDICATOR': 1301},
  'IRFCL': {'INDICATOR': 295, 'REF_SECTOR': 5},
  'MFS': {'INDICATOR': 575},
  'PGCS': {'INDICATOR': 15},
  'PSBSFAD': {'INDICATOR': 1235},
  'WoRLD': {'INDICATOR': 15}},
 'WB': {'DBS': {'indicator': 194},
  'ESY': {'indicator': 115},
  'FDX': {'indicator': 1226},
  'GEM': {'indicator': 36},
  'GEP': {'indicator': 1},
  'JOB': {'indicator': 166},
  'WDI': {'indicator': 1492},
  'WGI': {'indicator': 36}},
 'BIS': {'WS_GLI': {'BORROWERS_SECTOR': 20,
   'CURR_DENOM': 324,
   'LENDERS_SECTOR': 20,
   'L_INSTR': 23,
   'L_POS_TYPE': 8,
   'UNIT_MEASURE': 1088},
  'WS_CREDIT_GAP': {'CG_DTYPE': 3, 'TC_BORROWERS': 5, 'TC_LENDERS': 20}},
 'UNCTAD': {'MTTASA': {'flow': 2, 'measure': 2},
  'MTBA': {'measure': 2},
  'MTTGRA': {'flow': 2, 'measure': 1},
  'MPCADIOEAIA': {'flow': 2, 'measure': 3},
  'GASBTBIA': {'flow': 1, 'measure': 4, 'series': 2},
  'GASBTOIA': {'flow': 4, 'measure': 2, 'series': 2},
  'FDIIAOFASA': {'direction': 2, 'measure': 5, 'mode': 2},
  'GDPTAPCCAC2PA': {'measure': 4},
  'RGDPTAPCGRA': {'measure': 2},
  'NGTAPCA': {'measure': 2},
  'TAUPA': {'measure': 2},
  'TPGRA': {'measure': 1}},
 'ILO': {'EAR_GGAP_OCU_RT': {'classif1': 29, 'source': 150},
  'SDG_1041_NOC_RT': {'source': 199},
  'EES_TEES_ECO_OCU_NB': {'classif1': 56, 'classif2': 29, 'source': 238},
  'PSE_TPSE_GOV_NB': {'classif1': 10, 'source': 204},
  'GDP_205U_NOC_NB': {'source': 274},
  'SDG_B821_NOC_RT': {'source': 199},
  'INJ_FATL_ECO_NB': {'classif1': 61, 'source': 205}}}

In [ ]:
count_dataset_d

{'IMF': {'BOP': 2218,
  'CPI': 178,
  'FDI': 9,
  'FM': 9,
  'FSI': 959,
  'GENDER_EQUALITY': 3,
  'GFSMAB': 560,
  'HPDD': 1,
  'IFS': 1301,
  'IRFCL': 1475,
  'MFS': 575,
  'PGCS': 15,
  'PSBSFAD': 1235,
  'WoRLD': 15},
 'WB': {'DBS': 194,
  'ESY': 115,
  'FDX': 1226,
  'GEM': 36,
  'GEP': 1,
  'JOB': 166,
  'WDI': 1492,
  'WGI': 36},
 'BIS': {'WS_GLI': 25944883200, 'WS_CREDIT_GAP': 300},
 'UNCTAD': {'MTTASA': 4,
  'MTBA': 2,
  'MTTGRA': 2,
  'MPCADIOEAIA': 6,
  'GASBTBIA': 8,
  'GASBTOIA': 16,
  'FDIIAOFASA': 20,
  'GDPTAPCCAC2PA': 4,
  'RGDPTAPCGRA': 2,
  'NGTAPCA': 2,
  'TAUPA': 2,
  'TPGRA': 1},
 'ILO': {'EAR_GGAP_OCU_RT': 4350,
  'SDG_1041_NOC_RT': 199,
  'EES_TEES_ECO_OCU_NB': 386512,
  'PSE_TPSE_GOV_NB': 2040,
  'GDP_205U_NOC_NB': 274,
  'SDG_B821_NOC_RT': 199,
  'INJ_FATL_ECO_NB': 12505}}

In [ ]:
with open(config.METADATA_DIR / 'datasets_dimensions.json', 'r') as f:
    d = json.load(f)

print(d)

{'IMF': {'BOP': {'INDICATOR': {'BACK_BP6_USD': 'Net Lending (+) / Net Borrowing (-) (Balance from Current and Capital Account), US Dollars', 'BAXEF_BP6_USD': 'Supplementary Items, Arrears not in Exceptional Financing, US Dollars', 'BCAXF_BP6_USD': 'Supplementary Items, Current Account, Net (Excluding Exceptional Financing), US Dollars', 'BCA_BP6_SPE_USD': 'Current Account, Total, Net, Special Purpose Entities, US Dollar', 'BCA_BP6_USD': 'Current Account, Total, Net, US Dollars', 'BEFDDAAI_BP6_USD': 'Exceptional Financing, Direct Investment, Debt Instruments, Accumulations of Arrears, Original Interest/Coupon, US Dollars', 'BEFDDAAPI_BP6_USD': 'Exceptional Financing, Direct Investment, Debt Instruments, Accumulations of Arrears, Penalty Interest, US Dollars', 'BEFDDAAP_BP6_USD': 'Exceptional Financing, Direct Investment, Debt Instruments, Accumulations of Arrears, Principal, US Dollars', 'BEFDDAA_BP6_USD': 'Exceptional Financing, Direct Investment, Debt Instruments, Accumulations of Arrears, US Dollars', 'BEFDDCAI_BP6_USD': 'Exceptional Financing, Direct Investment, Debt Instruments, Cancellation of Arrears, Interest/Coupon, US Dollars', 'BEFDDCAP_BP6_USD': 'Exceptional Financing, Direct Investment, Debt Instruments, Cancellation of Arrears, Principal, US Dollars', 'BEFDDCA_BP6_USD': 'Exceptional Financing, Direct Investment, Debt Instruments, Cancellation of Arrears, US Dollars', 'BEFDDRAI_BP6_USD': 'Exceptional Financing, Direct Investment, Debt Instruments, Repayment of Arrears, Interest/Coupon, US Dollars', 'BEFDDRAP_BP6_USD': 'Exceptional Financing, Direct Investment, Debt Instruments, Repayment of Arrears, Principal, US Dollars', 'BEFDDRA_BP6_USD': 'Exceptional Financing, Direct Investment, Debt Instruments, Repayment of Arrears, US Dollars', 'BEFDDRPI_BP6_USD': 'Exceptional Financing, Direct Investment, Debt Instruments, Rescheduling of Payments Due in Current Reporting Period, Interest/Coupon, US Dollars', 'BEFDDRPP_BP6_USD': 'Exceptional Financing, Direct Investment, Debt Instruments, Rescheduling of Payments Due in Current Reporting Period, Principal, US Dollars', 'BEFDDRP_BP6_USD': 'Exceptional Financing, Direct Investment, Debt Instruments, Rescheduling of Payments Due in Current Reporting Period, US Dollars', 'BEFDDSAI_BP6_USD': 'Exceptional Financing, Direct Investment, Debt Instruments, Rescheduling of Arrears, Interest/Coupon, US Dollars', 'BEFDDSAP_BP6_USD': 'Exceptional Financing, Direct Investment, Debt Instruments, Rescheduling of Arrears, Principal, US Dollars', 'BEFDDSA_BP6_USD': 'Exceptional Financing, Direct Investment, Debt Instruments, Rescheduling of Arrears, US Dollars', 'BEFDD_BP6_USD': 'Exceptional Financing, Direct Investment, Debt Instruments, US Dollars', 'BEFDE_BP6_USD': 'Exceptional Financing, Direct Investment, Equity Investment Associated with Debt Reduction, US Dollars', 'BEFD_BP6_USD': 'Exceptional Financing, Direct Investment, US Dollars', 'BEFISGIMF_BP6_USD': 'Exceptional Financing, Secondary Income, Grants Received from IMF Subsidy Accounts, US Dollars', 'BEFISIG_BP6_USD': 'Exceptional Financing, Secondary Income, Other Intergovernmental grants, US Dollars', 'BEFIS_BP6_USD': 'Exceptional Financing, Secondary Income, US Dollars', 'BEFOE_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Equity Investment Associated with Debt Reduction, US Dollars', 'BEFOODCBAAI_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Central Bank, Accumulation of Arrears, Original Interest, US Dollars', 'BEFOODCBAAPI_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Central Bank, Accumulation of Arrears, Penalty Interest, US Dollars', 'BEFOODCBAAP_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Central Bank, Accumulation of Arrears, Principal, US Dollars', 'BEFOODCBAA_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Central Bank, Accumulation of Arrears, US Dollars', 'BEFOODCBCAI_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Central Bank, Cancellation of Arrears, Interest, US Dollars', 'BEFOODCBCAP_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Central Bank, Cancellation of Arrears, Principal, US Dollars', 'BEFOODCBCA_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Central Bank, Cancellation of Arrears, US Dollars', 'BEFOODCBND_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Central Bank, New Drawings/Deposits, US Dollars', 'BEFOODCBPP_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Central Bank, Prepayment, US Dollars', 'BEFOODCBRAI_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Central Bank, Repayment of Arrears, Interest, US Dollars', 'BEFOODCBRAP_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Central Bank, Repayment of Arrears, Principal, US Dollars', 'BEFOODCBRA_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Central Bank, Repayment of Arrears, US Dollars', 'BEFOODCBRPI_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Central Bank, Rescheduling of Payments Due in Current Reporting Period, Interest, US Dollars', 'BEFOODCBRPP_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Central Bank, Rescheduling of Payments Due in Current Reporting Period, Principal, US Dollars', 'BEFOODCBRP_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Central Bank, Rescheduling of Payments Due in Current Reporting Period, US Dollars', 'BEFOODCBSAI_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Central Bank, Rescheduling of Arrears, Interest, US Dollars', 'BEFOODCBSAP_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Central Bank, Rescheduling of Arrears, Principal, US Dollars', 'BEFOODCBSA_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Central Bank, Rescheduling of Arrears, US Dollars', 'BEFOODCB_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Central Bank, US Dollars', 'BEFOODDCAAI_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Deposit-taking Corporations, Except Central Bank, Accumulation of Arrears, Original Interest, US Dollars', 'BEFOODDCAAPI_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Deposit-taking Corporations, Except Central Bank, Accumulation of Arrears, Penalty Interest, US Dollars', 'BEFOODDCAAP_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Deposit-taking Corporations, Except Central Bank, Accumulation of Arrears, Principal, US Dollars', 'BEFOODDCAA_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Deposit-taking Corporations, Except Central Bank, Accumulation of Arrears, US Dollars', 'BEFOODDCCAI_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Deposit-taking Corporations, Except Central Bank, Cancellation of Arrears, Interest, US Dollars', 'BEFOODDCCAP_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Deposit-taking Corporations, Except Central Bank, Cancellation of Arrears, Principal, US Dollars', 'BEFOODDCCA_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Deposit-taking Corporations, Except Central Bank, Cancellation of Arrears, US Dollars', 'BEFOODDCND_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Deposit-taking Corporations, Except Central Bank, New Drawings/Deposits on Behalf of Authorities, US Dollars', 'BEFOODDCPP_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Deposit-taking Corporations, Except Central Bank, Prepayment, US Dollars', 'BEFOODDCRAI_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Deposit-taking Corporations, Except Central Bank, Repayment of Arrears, Interest, US Dollars', 'BEFOODDCRAP_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Deposit-taking Corporations, Except Central Bank, Repayment of Arrears, Principal, US Dollars', 'BEFOODDCRA_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Deposit-taking Corporations, Except Central Bank, Repayment of Arrears, US Dollars', 'BEFOODDCRPI_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Deposit-taking Corporations, Except Central Bank, Rescheduling of Payments Due in Current Reporting Period, Interest, US Dollars', 'BEFOODDCRPP_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Deposit-taking Corporations, Except Central Bank, Rescheduling of Payments Due in Current Reporting Period, Principal, US Dollars', 'BEFOODDCRP_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Deposit-taking Corporations, Except Central Bank, Rescheduling of Payments Due in Current Reporting Period, US Dollars', 'BEFOODDCSAI_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Deposit-taking Corporations, Except Central Bank, Rescheduling of Arrears, Interest, US Dollars', 'BEFOODDCSAP_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Deposit-taking Corporations, Except Central Bank, Rescheduling of Arrears, Principal, US Dollars', 'BEFOODDCSA_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Deposit-taking Corporations, Except Central Bank, Rescheduling of Arrears, US Dollars', 'BEFOODDC_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Deposit-taking Corporations, Except Central Bank, US Dollars', 'BEFOODGAAI_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, General Government, Accumulation of Arrears, Original Interest, US Dollars', 'BEFOODGAAPI_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, General Government, Accumulation of Arrears, Penalty Interest, US Dollars', 'BEFOODGAAP_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, General Government, Accumulation of Arrears, Principal, US Dollars', 'BEFOODGAA_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, General Government, Accumulation of Arrears, US Dollars', 'BEFOODGCAI_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, General Government, Cancellation of Arrears, Interest, US Dollars', 'BEFOODGCAP_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, General Government, Cancellation of Arrears, Principal, US Dollars', 'BEFOODGCA_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, General Government, Cancellation of Arrears, US Dollars', 'BEFOODGND_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, General Government, New Drawings/Deposits, US Dollars', 'BEFOODGPP_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, General Government, Prepayment, US Dollars', 'BEFOODGRAI_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, General Government, Repayment of Arrears, Interest, US Dollars', 'BEFOODGRAP_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, General Government, Repayment of Arrears, Principal, US Dollars', 'BEFOODGRA_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, General Government, Repayment of Arrears, US Dollars', 'BEFOODGRPI_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, General Government, Rescheduling of Payments Due in Current Reporting Period, Interest, US Dollars', 'BEFOODGRPP_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, General Government, Rescheduling of Payments Due in Current Reporting Period, Principal, US Dollars', 'BEFOODGRP_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, General Government, Rescheduling of Payments Due in Current Reporting Period, US Dollars', 'BEFOODGSAI_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, General Government, Rescheduling of Arrears, Interest, US Dollars', 'BEFOODGSAP_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, General Government, Rescheduling of Arrears, Principal, US Dollars', 'BEFOODGSA_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, General Government, Rescheduling of Arrears, US Dollars', 'BEFOODG_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, General Government, US Dollars', 'BEFOODOAAI_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Other Sectors, Accumulation of Arrears, Original Interest, US Dollars', 'BEFOODOAAPI_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Other Sectors, Accumulation of Arrears, Penalty Interest, US Dollars', 'BEFOODOAAP_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Other Sectors, Accumulation of Arrears, Principal, US Dollars', 'BEFOODOAA_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Other Sectors, Accumulation of Arrears, US Dollars', 'BEFOODOCAI_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Other Sectors, Cancellation of Arrears, Interest, US Dollars', 'BEFOODOCAP_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Other Sectors, Cancellation of Arrears, Principal, US Dollars', 'BEFOODOCA_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Other Sectors, Cancellation of Arrears, US Dollars', 'BEFOODOFAAI_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Other Financial Corporations, Accumulation of Arrears, Original Interest, US Dollars', 'BEFOODOFAAPI_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Other Financial Corporations, Accumulation of Arrears, Penalty Interest, US Dollars', 'BEFOODOFAAP_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Other Financial Corporations, Accumulation of Arrears, Principal, US Dollars', 'BEFOODOFAA_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Other Financial Corporations, Accumulation of Arrears, US Dollars', 'BEFOODOFCAI_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Other Financial Corporations, Cancellation of Arrears, Interest, US Dollars', 'BEFOODOFCAP_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Other Financial Corporations, Cancellation of Arrears, Principal, US Dollars', 'BEFOODOFCA_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Other Financial Corporations, Cancellation of Arrears, US Dollars', 'BEFOODOFND_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Other Financial Corporations, New Drawings/Deposits on Behalf of Authorities, US Dollars', 'BEFOODOFPP_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Other Financial Corporations, Prepayment, US Dollars', 'BEFOODOFRAI_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Other Financial Corporations, Repayment of Arrears, Interest, US Dollars', 'BEFOODOFRAP_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Other Financial Corporations, Repayment of Arrears, Principal, US Dollars', 'BEFOODOFRA_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Other Financial Corporations, Repayment of Arrears, US Dollars', 'BEFOODOFRPI_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Other Financial Corporations, Rescheduling of Payments Due in Current Reporting Period, Interest, US Dollars', 'BEFOODOFRPP_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Other Financial Corporations, Rescheduling of Payments Due in Current Reporting Period, Principal, US Dollars', 'BEFOODOFRP_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Other Financial Corporations, Rescheduling of Payments Due in Current Reporting Period, US Dollars', 'BEFOODOFSAI_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Other Financial Corporations, Rescheduling of Arrears, Interest, US Dollars', 'BEFOODOFSAP_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Other Financial Corporations, Rescheduling of Arrears, Principal, US Dollars', 'BEFOODOFSA_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Other Financial Corporations, Rescheduling of Arrears, US Dollars', 'BEFOODOF_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Other Financial Corporations, US Dollars', 'BEFOODOND_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Other Sectors, New Drawings/Deposits on Behalf of Authorities, US Dollars', 'BEFOODONFAAI_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Nonfinancial Corporations, Households, NPISHs, Accumulation of Arrears, Original Interest, US Dollars', 'BEFOODONFAAPI_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Nonfinancial Corporations, Households, NPISHs, Accumulation of Arrears, Penalty Interest, US Dollars', 'BEFOODONFAAP_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Nonfinancial Corporations, Households, NPISHs, Accumulation of Arrears, Principal, US Dollars', 'BEFOODONFAA_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Nonfinancial Corporations, Households, NPISHs, Accumulation of Arrears, US Dollars', 'BEFOODONFCAI_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Nonfinancial Corporations, Households, NPISHs, Cancellation of Arrears, Interest, US Dollars', 'BEFOODONFCAP_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Nonfinancial Corporations, Households, NPISHs, Cancellation of Arrears, Principal, US Dollars', 'BEFOODONFCA_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Nonfinancial Corporations, Households, NPISHs, Cancellation of Arrears, US Dollars', 'BEFOODONFND_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instruments, Nonfinancial Corporations, Households, NPISHs, New Drawings/Deposits on Behalf of Authorities, US Dollars', 'BEFOODONFPP_BP6_USD': 'Exceptional Financing, Other Investment - Liabilities, Other Debt Instrumen

In [ ]:
d['BIS']['WS_GLI']

{'BORROWERS_SECTOR': {'A': 'All sectors',
  'B': 'Banks, total',
  'G': 'General government',
  'H': 'Households and NPISHs',
  'N': 'Non-banks, total'},
 'CURR_DENOM': {'USD': 'US dollar'},
 'LENDERS_SECTOR': {'A': 'All sectors',
  'B': 'Banks, total',
  'G': 'General government',
  'H': 'Households and NPISHs',
  'N': 'Non-banks, total'},
 'L_INSTR': {'A': 'All instruments',
  'B': 'Credit (loans & debt securities)',
  'D': 'Debt securities',
  'E': 'Risk-weighted assets',
  'G': 'Loans and deposits',
  'X': 'Equity instruments',
  'Y': 'Residual instrument'},
 'L_POS_TYPE': {'A': 'All'},
 'UNIT_MEASURE': {'770': 'Percentage of GDP'}}

In [ ]:
count_dataset_d = {}
count_provider_d = {}
count_d = {}
for provider_id, provider_d in d.items():
    count_d[provider_id] = {}
    count_dataset_d[provider_id] = {}
    v_provider = 0
    for dataset_id, dataset_d in provider_d.items():
        count_d[provider_id][dataset_id] = {}
        count_dataset_d[provider_id][dataset_id] = {}
        v_dataset = 1
        for param, param_d in dataset_d.items():
            v_dataset = v_dataset * len(param_d)
        
        count_dataset_d[provider_id][dataset_id] = v_dataset
        v_provider = v_provider + v_dataset
    count_provider_d[provider_id] = v_provider

count_provider_d

{'IMF': 8547, 'WB': 3266, 'BIS': 250, 'UNCTAD': 69}

In [ ]:
count_dataset_d

{'IMF': {'BOP': 2218,
  'CPI': 178,
  'FDI': 9,
  'FM': 9,
  'FSI': 959,
  'GENDER_EQUALITY': 3,
  'GFSMAB': 560,
  'HPDD': 1,
  'IFS': 1301,
  'IRFCL': 1475,
  'MFS': 575,
  'PGCS': 9,
  'PSBSFAD': 1235,
  'WoRLD': 15},
 'WB': {'DBS': 194,
  'ESY': 115,
  'FDX': 1226,
  'GEM': 36,
  'GEP': 1,
  'JOB': 166,
  'WDI': 1492,
  'WGI': 36},
 'BIS': {'WS_GLI': 175, 'WS_CREDIT_GAP': 75},
 'UNCTAD': {'MTTASA': 4,
  'MTBA': 2,
  'MTTGRA': 2,
  'MPCADIOEAIA': 6,
  'GASBTBIA': 8,
  'GASBTOIA': 16,
  'FDIIAOFASA': 20,
  'GDPTAPCCAC2PA': 4,
  'RGDPTAPCGRA': 2,
  'NGTAPCA': 2,
  'TAUPA': 2,
  'TPGRA': 1}}

In [ ]:
d = client.list_series('ILO', 'LAP_2FTM_NOC_RT', limit=1)
d

{'_meta': {'args': {'align_periods': False,
   'dataset_code': 'LAP_2FTM_NOC_RT',
   'dimensions': {},
   'facets': False,
   'format': 'json',
   'limit': 1,
   'metadata': True,
   'observations': False,
   'offset': 0,
   'provider_code': 'ILO',
   'q': '',
   'series_code': None},
  'version': '22.1.17'},
 'dataset': {'attributes_labels': {'OBSV_STATUS': 'Observation status'},
  'attributes_values_labels': {'OBSV_STATUS': {'A': 'Adjusted',
    'B': 'Break in series',
    'C': 'Confidential',
    'E': 'Estimate',
    'I': 'Imputation',
    'M': 'Model-based extrapolation',
    'P': 'Provisional',
    'R': 'Real value',
    'S': 'Not significant',
    'U': 'Unreliable'}},
  'code': 'LAP_2FTM_NOC_RT',
  'dimensions_codes_order': ['ref_area', 'source', 'frequency'],
  'dimensions_labels': {'frequency': 'Frequency',
   'ref_area': 'Reference area',
   'source': 'Source'},
  'dimensions_values_labels': {'frequency': {'A': 'Annual'},
   'ref_area': {'X01': 'World',
    'X02': 'World: Low income',
    'X03': 'World: Lower-middle income',
    'X04': 'World: Upper-middle income',
    'X05': 'World: High income',
    'X06': 'Africa',
    'X07': 'Africa: Low income',
    'X08': 'Africa: Lower-middle income',
    'X09': 'Africa: Upper-middle income',
    'X10': 'Northern Africa',
    'X11': 'Northern Africa: Lower-middle income',
    'X13': 'Sub-Saharan Africa',
    'X14': 'Sub-Saharan Africa: Low income',
    'X15': 'Sub-Saharan Africa: Lower-middle income',
    'X16': 'Sub-Saharan Africa: Upper-middle income',
    'X17': 'Central Africa',
    'X18': 'Eastern Africa',
    'X19': 'Southern Africa',
    'X20': 'Western Africa',
    'X21': 'Americas',
    'X23': 'Americas: Lower-middle income',
    'X24': 'Americas: Upper-middle income',
    'X25': 'Americas: High income',
    'X26': 'Latin America and the Caribbean',
    'X28': 'Latin America and the Caribbean: Lower-middle income',
    'X29': 'Latin America and the Caribbean: Upper-middle income',
    'X30': 'Latin America and the Caribbean: High income',
    'X31': 'Caribbean',
    'X32': 'Central America',
    'X33': 'South America',
    'X34': 'Northern America',
    'X35': 'Northern America: High income',
    'X36': 'Arab States',
    'X37': 'Arab States: Lower-middle income',
    'X38': 'Arab States: Upper-middle income',
    'X39': 'Arab States: High income',
    'X40': 'Asia and the Pacific',
    'X41': 'Asia and the Pacific: Low income',
    'X42': 'Asia and the Pacific: Lower-middle income',
    'X43': 'Asia and the Pacific: Upper-middle income',
    'X44': 'Asia and the Pacific: High income',
    'X45': 'Eastern Asia',
    'X48': 'Eastern Asia: High income',
    'X49': 'South-Eastern Asia and the Pacific',
    'X51': 'South-Eastern Asia and the Pacific: Lower-middle income',
    'X52': 'South-Eastern Asia and the Pacific: Upper-middle income',
    'X53': 'South-Eastern Asia and the Pacific: High income',
    'X54': 'South-Eastern Asia',
    'X55': 'Pacific Islands',
    'X56': 'Southern Asia',
    'X58': 'Southern Asia: Lower-middle income',
    'X60': 'Europe and Central Asia',
    'X61': 'Europe and Central Asia: Lower-middle income',
    'X62': 'Europe and Central Asia: Upper-middle income',
    'X63': 'Europe and Central Asia: High income',
    'X64': 'Northern, Southern and Western Europe',
    'X65': 'Northern, Southern and Western Europe: Upper-middle income',
    'X66': 'Northern, Southern and Western Europe: High income',
    'X67': 'Northern Europe',
    'X68': 'Southern Europe',
    'X69': 'Western Europe',
    'X70': 'Eastern Europe',
    'X72': 'Eastern Europe: Upper-middle income',
    'X73': 'Eastern Europe: High income',
    'X74': 'Central Asia',
    'X75': 'Central and Western Asia: Lower-middle income',
    'X76': 'Central and Western Asia: Upper-middle income',
    'X77': 'Central and Western Asia: High income',
    'X78': 'Central and Western Asia',
    'X79': 'Western Asia',
    'X82': 'European Union 28',
    'X83': 'G20',
    'X84': 'ASEAN',
    'X85': 'BRICS',
    'X87': 'World excluding BRICS',
    'X88': 'G7',
    'X89': 'MENA',
    'X90': 'Arab League',
    'X91': 'CARICOM',
    'X92': 'European Union 27',
    'X94': 'Arab States: Low income',
    'X97': 'APEC'},
   'source': {'XA_12987': 'ILO - Modelled Estimates',
    'XA_12988': 'ILO - Modelled Estimates',
    'XA_12989': 'ILO - Modelled Estimates',
    'XA_12990': 'ILO - Modelled Estimates',
    'XA_13329': 'ILO - Modelled Estimates',
    'XA_14065': 'ILO - Modelled Estimates',
    'XA_14066': 'ILO - Modelled Estimates',
    'XA_15672': 'ILO - Modelled Estimates',
    'XA_15716': 'ILO - Modelled Estimates',
    'XA_15724': 'ILO - Modelled Estimates',
    'XA_15736': 'ILO - Modelled Estimates',
    'XA_16111': 'ILO - Modelled Estimates',
    'XA_8372': 'ILO - Modelled Estimates',
    'XA_8373': 'ILO - Modelled Estimates',
    'XA_8374': 'ILO - Modelled Estimates',
    'XA_8375': 'ILO - Modelled Estimates',
    'XA_8376': 'ILO - Modelled Estimates',
    'XA_8377': 'ILO - Modelled Estimates',
    'XA_8378': 'ILO - Modelled Estimates',
    'XA_8379': 'ILO - Modelled Estimates',
    'XA_8380': 'ILO - Modelled Estimates',
    'XA_8381': 'ILO - Modelled Estimates',
    'XA_8382': 'ILO - Modelled Estimates',
    'XA_8383': 'ILO - Modelled Estimates',
    'XA_8384': 'ILO - Modelled Estimates',
    'XA_8385': 'ILO - Modelled Estimates',
    'XA_8386': 'ILO - Modelled Estimates',
    'XA_8387': 'ILO - Modelled Estimates',
    'XA_8388': 'ILO - Modelled Estimates',
    'XA_8389': 'ILO - Modelled Estimates',
    'XA_8390': 'ILO - Modelled Estimates',
    'XA_8391': 'ILO - Modelled Estimates',
    'XA_8392': 'ILO - Modelled Estimates',
    'XA_8393': 'ILO - Modelled Estimates',
    'XA_8394': 'ILO - Modelled Estimates',
    'XA_8395': 'ILO - Modelled Estimates',
    'XA_8396': 'ILO - Modelled Estimates',
    'XA_8397': 'ILO - Modelled Estimates',
    'XA_8398': 'ILO - Modelled Estimates',
    'XA_8399': 'ILO - Modelled Estimates',
    'XA_8400': 'ILO - Modelled Estimates',
    'XA_8401': 'ILO - Modelled Estimates',
    'XA_8402': 'ILO - Modelled Estimates',
    'XA_8403': 'ILO - Modelled Estimates',
    'XA_8404': 'ILO - Modelled Estimates',
    'XA_8405': 'ILO - Modelled Estimates',
    'XA_8406': 'ILO - Modelled Estimates',
    'XA_8407': 'ILO - Modelled Estimates',
    'XA_8408': 'ILO - Modelled Estimates',
    'XA_8409': 'ILO - Modelled Estimates',
    'XA_8411': 'ILO - Modelled Estimates',
    'XA_8412': 'ILO - Modelled Estimates',
    'XA_8413': 'ILO - Modelled Estimates',
    'XA_8415': 'ILO - Modelled Estimates',
    'XA_8416': 'ILO - Modelled Estimates',
    'XA_8417': 'ILO - Modelled Estimates',
    'XA_8419': 'ILO - Modelled Estimates',
    'XA_8420': 'ILO - Modelled Estimates',
    'XA_8421': 'ILO - Modelled Estimates',
    'XA_8422': 'ILO - Modelled Estimates',
    'XA_8423': 'ILO - Modelled Estimates',
    'XA_8424': 'ILO - Modelled Estimates',
    'XA_8425': 'ILO - Modelled Estimates',
    'XA_8426': 'ILO - Modelled Estimates',
    'XA_8427': 'ILO - Modelled Estimates',
    'XA_8428': 'ILO - Modelled Estimates',
    'XA_8429': 'ILO - Modelled Estimates',
    'XA_8432': 'ILO - Modelled Estimates',
    'XA_8434': 'ILO - Modelled Estimates',
    'XA_8435': 'ILO - Modelled Estimates',
    'XA_8436': 'ILO - Modelled Estimates',
    'XA_8438': 'ILO - Modelled Estimates',
    'XA_8440': 'ILO - Modelled Estimates',
    'XA_8441': 'ILO - Modelled Estimates',
    'XA_8442': 'ILO - Modelled Estimates',
    'XA_8443': 'ILO - Modelled Estimates',
    'XA_8444': 'ILO - Modelled Estimates',
    'XA_8446': 'ILO - Modelled Estimates',
    'XA_8447': 'ILO - Modelled Estimates',
    'XA_8448': 'ILO - Modelled Estimates',
    'XA_8449': 'ILO - Modelled Estimates',
    'XA_8450': 'ILO - Modelled Estimates'}},
  'dir_hash': 'b9583d49c913d05b2fc4888b9b5f6c6f563fa7e1',
  'indexed_at': '2023-11-27T04:33:32.919Z',
  'name': "Gender income gap, ratio of women's to men's labour income -- ILO modelled estimates, Nov. 2022 (%)",
  'nb_series': 82,
  'provider_code': 'ILO',
  'provider_name': 'International Labour Organization'},
 'errors': None,
 'provider': {'code': 'ILO',
  'indexed_at': '2024-02-20T03:34:29.870Z',
  'name': 'International Labour Organization',
  'region': 'World',
  'slug': 'ilo',
  'terms_of_use': 'http://www.ilo.org/global/copyright/request-for-permission/lang--en/index.htm',
  'website': 'https://www.ilo.org'},
 'series': {'docs': [{'dataset_code': 'LAP_2FTM_NOC_RT',
    'dataset_name': "Gender income gap, ratio of women's to men's labour income -- ILO modelled estimates, Nov. 2022 (%)",
    'dimensions': {'frequency': 'A', 'ref_area': 'X01', 'source': 'XA_8405'},
    'indexed_at': '2023-11-27T04:33:32.919Z',
    'provider_code': 'ILO',
    'series_code': 'X01.XA_8405.A',
    'series_name': 'World – ILO - Modelled Estimates (XA_8405) – Annual'}],
  'limit': 1,
  'num_found': 82,
  'offset': 0}}

In [ ]:
d.keys()

dict_keys(['_meta', 'dataset', 'errors', 'provider', 'series'])

In [ ]:
d['dataset'].keys()

dict_keys(['attributes_labels', 'attributes_values_labels', 'code', 'dimensions_codes_order', 'dimensions_labels', 'dimensions_values_labels', 'dir_hash', 'indexed_at', 'name', 'nb_series', 'provider_code', 'provider_name'])

In [ ]:
d['dataset']['dimensions_values_labels'].keys()

dict_keys(['frequency', 'ref_area', 'source'])

In [ ]:
d['dataset']['dimensions_values_labels']['ref_area']

{'X01': 'World',
 'X02': 'World: Low income',
 'X03': 'World: Lower-middle income',
 'X04': 'World: Upper-middle income',
 'X05': 'World: High income',
 'X06': 'Africa',
 'X07': 'Africa: Low income',
 'X08': 'Africa: Lower-middle income',
 'X09': 'Africa: Upper-middle income',
 'X10': 'Northern Africa',
 'X11': 'Northern Africa: Lower-middle income',
 'X13': 'Sub-Saharan Africa',
 'X14': 'Sub-Saharan Africa: Low income',
 'X15': 'Sub-Saharan Africa: Lower-middle income',
 'X16': 'Sub-Saharan Africa: Upper-middle income',
 'X17': 'Central Africa',
 'X18': 'Eastern Africa',
 'X19': 'Southern Africa',
 'X20': 'Western Africa',
 'X21': 'Americas',
 'X23': 'Americas: Lower-middle income',
 'X24': 'Americas: Upper-middle income',
 'X25': 'Americas: High income',
 'X26': 'Latin America and the Caribbean',
 'X28': 'Latin America and the Caribbean: Lower-middle income',
 'X29': 'Latin America and the Caribbean: Upper-middle income',
 'X30': 'Latin America and the Caribbean: High income',
 'X31': 'Caribbean',
 'X32': 'Central America',
 'X33': 'South America',
 'X34': 'Northern America',
 'X35': 'Northern America: High income',
 'X36': 'Arab States',
 'X37': 'Arab States: Lower-middle income',
 'X38': 'Arab States: Upper-middle income',
 'X39': 'Arab States: High income',
 'X40': 'Asia and the Pacific',
 'X41': 'Asia and the Pacific: Low income',
 'X42': 'Asia and the Pacific: Lower-middle income',
 'X43': 'Asia and the Pacific: Upper-middle income',
 'X44': 'Asia and the Pacific: High income',
 'X45': 'Eastern Asia',
 'X48': 'Eastern Asia: High income',
 'X49': 'South-Eastern Asia and the Pacific',
 'X51': 'South-Eastern Asia and the Pacific: Lower-middle income',
 'X52': 'South-Eastern Asia and the Pacific: Upper-middle income',
 'X53': 'South-Eastern Asia and the Pacific: High income',
 'X54': 'South-Eastern Asia',
 'X55': 'Pacific Islands',
 'X56': 'Southern Asia',
 'X58': 'Southern Asia: Lower-middle income',
 'X60': 'Europe and Central Asia',
 'X61': 'Europe and Central Asia: Lower-middle income',
 'X62': 'Europe and Central Asia: Upper-middle income',
 'X63': 'Europe and Central Asia: High income',
 'X64': 'Northern, Southern and Western Europe',
 'X65': 'Northern, Southern and Western Europe: Upper-middle income',
 'X66': 'Northern, Southern and Western Europe: High income',
 'X67': 'Northern Europe',
 'X68': 'Southern Europe',
 'X69': 'Western Europe',
 'X70': 'Eastern Europe',
 'X72': 'Eastern Europe: Upper-middle income',
 'X73': 'Eastern Europe: High income',
 'X74': 'Central Asia',
 'X75': 'Central and Western Asia: Lower-middle income',
 'X76': 'Central and Western Asia: Upper-middle income',
 'X77': 'Central and Western Asia: High income',
 'X78': 'Central and Western Asia',
 'X79': 'Western Asia',
 'X82': 'European Union 28',
 'X83': 'G20',
 'X84': 'ASEAN',
 'X85': 'BRICS',
 'X87': 'World excluding BRICS',
 'X88': 'G7',
 'X89': 'MENA',
 'X90': 'Arab League',
 'X91': 'CARICOM',
 'X92': 'European Union 27',
 'X94': 'Arab States: Low income',
 'X97': 'APEC'}

In [ ]:
import requests

url = "https://api.db.nomics.world/v22" + "/series/WB/ESY/?"

r = requests.get(url)
r.raise_for_status()
r.json()

{'_meta': {'args': {'align_periods': False,
   'dataset_code': 'ESY',
   'dimensions': {},
   'facets': False,
   'format': 'json',
   'limit': 1000,
   'metadata': True,
   'observations': False,
   'offset': 0,
   'provider_code': 'WB',
   'q': '',
   'series_code': None},
  'version': '22.1.17'},
 'dataset': {'code': 'ESY',
  'dimensions_codes_order': ['frequency', 'indicator', 'country'],
  'dimensions_values_labels': {'country': {'AFG': 'Afghanistan',
    'AGO': 'Angola',
    'ALB': 'Albania',
    'ARG': 'Argentina',
    'ARM': 'Armenia',
    'ATG': 'Antigua and Barbuda',
    'AZE': 'Azerbaijan',
    'BDI': 'Burundi',
    'BEL': 'Belgium',
    'BEN': 'Benin',
    'BFA': 'Burkina Faso',
    'BGD': 'Bangladesh',
    'BGR': 'Bulgaria',
    'BHS': 'Bahamas, The',
    'BIH': 'Bosnia and Herzegovina',
    'BLR': 'Belarus',
    'BLZ': 'Belize',
    'BOL': 'Bolivia',
    'BRA': 'Brazil',
    'BRB': 'Barbados',
    'BTN': 'Bhutan',
    'BWA': 'Botswana',
    'CAF': 'Central African Republic',
    'CHL': 'Chile',
    'CHN': 'China',
    'CIV': "Cote d'Ivoire",
    'CMR': 'Cameroon',
    'COD': 'Congo, Dem. Rep.',
    'COG': 'Congo, Rep.',
    'COL': 'Colombia',
    'CPV': 'Cabo Verde',
    'CRI': 'Costa Rica',
    'CYP': 'Cyprus',
    'CZE': 'Czech Republic',
    'DJI': 'Djibouti',
    'DMA': 'Dominica',
    'DOM': 'Dominican Republic',
    'ECU': 'Ecuador',
    'EGY': 'Egypt, Arab Rep.',
    'ERI': 'Eritrea',
    'EST': 'Estonia',
    'ETH': 'Ethiopia',
    'FJI': 'Fiji',
    'FSM': 'Micronesia, Fed. Sts.',
    'GAB': 'Gabon',
    'GEO': 'Georgia',
    'GHA': 'Ghana',
    'GIN': 'Guinea',
    'GMB': 'Gambia, The',
    'GNB': 'Guinea-Bissau',
    'GRC': 'Greece',
    'GRD': 'Grenada',
    'GTM': 'Guatemala',
    'GUY': 'Guyana',
    'HND': 'Honduras',
    'HRV': 'Croatia',
    'HUN': 'Hungary',
    'IDN': 'Indonesia',
    'IND': 'India',
    'IRQ': 'Iraq',
    'ISR': 'Israel',
    'ITA': 'Italy',
    'JAM': 'Jamaica',
    'JOR': 'Jordan',
    'KAZ': 'Kazakhstan',
    'KEN': 'Kenya',
    'KGZ': 'Kyrgyz Republic',
    'KHM': 'Cambodia',
    'KNA': 'St. Kitts and Nevis',
    'LAO': 'Lao PDR',
    'LBN': 'Lebanon',
    'LBR': 'Liberia',
    'LCA': 'St. Lucia',
    'LKA': 'Sri Lanka',
    'LSO': 'Lesotho',
    'LTU': 'Lithuania',
    'LUX': 'Luxembourg',
    'LVA': 'Latvia',
    'MAR': 'Morocco',
    'MDA': 'Moldova',
    'MDG': 'Madagascar',
    'MEX': 'Mexico',
    'MKD': 'North Macedonia',
    'MLI': 'Mali',
    'MLT': 'Malta',
    'MMR': 'Myanmar',
    'MNE': 'Montenegro',
    'MNG': 'Mongolia',
    'MOZ': 'Mozambique',
    'MRT': 'Mauritania',
    'MUS': 'Mauritius',
    'MWI': 'Malawi',
    'MYS': 'Malaysia',
    'NAM': 'Namibia',
    'NER': 'Niger',
    'NGA': 'Nigeria',
    'NIC': 'Nicaragua',
    'NPL': 'Nepal',
    'PAK': 'Pakistan',
    'PAN': 'Panama',
    'PER': 'Peru',
    'PHL': 'Philippines',
    'PNG': 'Papua New Guinea',
    'POL': 'Poland',
    'PRT': 'Portugal',
    'PRY': 'Paraguay',
    'PSE': 'West Bank and Gaza',
    'ROU': 'Romania',
    'RUS': 'Russian Federation',
    'RWA': 'Rwanda',
    'SDN': 'Sudan',
    'SEN': 'Senegal',
    'SLB': 'Solomon Islands',
    'SLE': 'Sierra Leone',
    'SLV': 'El Salvador',
    'SRB': 'Serbia',
    'SSD': 'South Sudan',
    'SUR': 'Suriname',
    'SVK': 'Slovak Republic',
    'SVN': 'Slovenia',
    'SWE': 'Sweden',
    'SWZ': 'Eswatini',
    'TCD': 'Chad',
    'TGO': 'Togo',
    'THA': 'Thailand',
    'TJK': 'Tajikistan',
    'TLS': 'Timor-Leste',
    'TON': 'Tonga',
    'TTO': 'Trinidad and Tobago',
    'TUN': 'Tunisia',
    'TUR': 'Turkey',
    'TZA': 'Tanzania',
    'UGA': 'Uganda',
    'UKR': 'Ukraine',
    'URY': 'Uruguay',
    'UZB': 'Uzbekistan',
    'VCT': 'St. Vincent and the Grenadines',
    'VEN': 'Venezuela, RB',
    'VNM': 'Vietnam',
    'VUT': 'Vanuatu',
    'WSM': 'Samoa',
    'XKX': 'Kosovo',
    'YEM': 'Yemen, Rep.',
    'ZAF': 'South Africa',
    'ZMB': 'Zambia',
    'ZWE': 'Zimbabwe'},
   'frequency': {'A': 'Annual'},
   'indicator': {'IC.FRM.BRIB.GRAFT2': 'Bribery depth (% of public transactions where a gift or informal payment was requested)',
    'IC.FRM.BRIB.GRAFT3': 'Bribery incidence (percent of firms experiencing at least one bribe payment request)',
    'IC.FRM.CORR.CORR1': 'Percent of firms expected to give gifts in meetings with tax officials',
    'IC.FRM.CORR.CORR10': 'Percent of firms expected to give gifts to get an operating license',
    'IC.FRM.CORR.CORR11': 'Percent of firms identifying corruption as a major constraint',
    'IC.FRM.CORR.CORR2': 'Percent of firms expected to give gifts to secure government contract',
    'IC.FRM.CORR.CORR3': 'Value of gift expected to secure a government contract (% of contract value)',
    'IC.FRM.CORR.CORR4': 'Percent of firms expected to give gifts to public officials "to get things done"',
    'IC.FRM.CORR.CORR6': 'Percent of firms expected to give gifts to get an electrical connection',
    'IC.FRM.CORR.CORR7': 'Percent of firms expected to give gifts to get a water connection',
    'IC.FRM.CORR.CORR8': 'Percent of firms expected to give gifts to get a construction permit',
    'IC.FRM.CORR.CORR9': 'Percent of firms expected to give gifts to get an import license',
    'IC.FRM.CORR.CRIME9': 'Percent of firms identifying the courts system as a major constraint',
    'IC.FRM.CRM.CRIME1': 'Percent of firms paying for security',
    'IC.FRM.CRM.CRIME10': 'Percent of firms experiencing losses due to theft and vandalism',
    'IC.FRM.CRM.CRIME2_C': 'If the establishment pays for security, average security costs (% of annual sales)',
    'IC.FRM.CRM.CRIME3_C': 'If there were losses, average losses due to theft and vandalism (% of annual sales)',
    'IC.FRM.CRM.CRIME5': 'Products shipped to supply domestic markets that were lost due to theft (% of product value)',
    'IC.FRM.CRM.CRIME8': 'Percent of firms identifying crime, theft and disorder as a major constraint',
    'IC.FRM.EMP.GROW.PEFT2': 'Annual employment growth (%)',
    'IC.FRM.FCHAR.CAR1': 'Age of the establishment (years)',
    'IC.FRM.FCHAR.CAR2': 'Proportion of private domestic ownership in a firm (%)',
    'IC.FRM.FCHAR.CAR7': 'Percent of firms with at least 10% of foreign ownership',
    'IC.FRM.FCHAR.CAR8': 'Percent of firms with at least 10% of government/state ownership',
    'IC.FRM.FCHAR.LFORM3': 'Percent of firms with legal status of Sole Proprietorship',
    'IC.FRM.FIAS.PEFT4': 'Percent of firms buying fixed assets',
    'IC.FRM.FIN.FIN1': 'Proportion of investment financed internally (%)',
    'IC.FRM.FIN.FIN10': 'Value of collateral needed for a loan (% of the loan amount)',
    'IC.FRM.FIN.FIN11': 'Proportion of loans requiring collateral (%)',
    'IC.FRM.FIN.FIN12': 'Percent of firms using banks to finance investments',
    'IC.FRM.FIN.FIN13': 'Percent of firms using banks to finance working capital',
    'IC.FRM.FIN.FIN14': 'Percent of firms with a bank loan/line of credit',
    'IC.FRM.FIN.FIN15': 'Percent of firms with a checking or savings account',
    'IC.FRM.FIN.FIN16': 'Percent of firms identifying access to finance as a major constraint',
    'IC.FRM.FIN.FIN2': 'Proportion of investment financed by banks (%)',
    'IC.FRM.FIN.FIN20': 'Percent of firms not needing a loan',
    'IC.FRM.FIN.FIN21': 'Percent of firms whose recent loan application was rejected',
    'IC.FRM.FIN.FIN22': 'Percent of firms using supplier/customer credit to finance working capital',
    'IC.FRM.FIN.FIN7': 'Proportion of working capital financed by banks (%)',
    'IC.FRM.GEN.GEND1': 'Percent of firms with female participation in ownership',
    'IC.FRM.GEN.GEND2': 'Proportion of permanent full-time workers that are female (%)',
    'IC.FRM.GEN.GEND3': 'Proportion of permanent full-time non-production workers that are female (%)',
    'IC.FRM.GEN.GEND4': 'Percent of firms with a female top manager',
    'IC.FRM.GEN.GEND5': 'Proportion of permanent full-time production workers that are female (%)',
    'IC.FRM.GEN.GEND6': 'Percent of firms with majority female ownership',
    'IC.FRM.INFOR.INFOR1': 'Percent of firms competing against unregistered or informal firms',
    'IC.FRM.INFOR.INFOR2': 'Percent of firms identifying practices of competitors in the informal sector as a major constraint',
    'IC.FRM.INFOR.INFOR4': 'Percent of firms formally registered when they started operations in the country',
    'IC.FRM.INFOR.INFOR5': 'Number of years firm operated without formal registration',
    'IC.FRM.INFRA.IN1': 'Days to obtain an electrical connection (upon application)',
    'IC.FRM.INFRA.IN10_C': 'If a generator is used, average proportion of electricity from a generator (%)',
    'IC.FRM.INFRA.IN11': 'Percent of firms identifying transportation as a major constraint',
    'IC.FRM.INFRA.IN12': 'Percent of firms identifying electricity as a major constraint',
    'IC.FRM.INFRA.IN14': 'Proportion of products lost to breakage or spoilage during shipping to domestic markets (%)',
    'IC.FRM.INFRA.IN16': 'Percent of firms experiencing electrical outages',
    'IC.FRM.INFRA.IN17': 'Percent of firms experiencing water insufficiencies',
    'IC.FRM.INFRA.IN2': 'Number of electrical outages in a typical month',
    'IC.FRM.INFRA.IN3_C': 'If there were outages, average duration of a typical electrical outage (hours)',
    'IC.FRM.INFRA.IN4_C': 'If there were outages, average losses due to electrical outages (% of annual sales)',
    'IC.FRM.INFRA.IN6': 'Number of water insufficiencies in a typical month',
    'IC.FRM.INFRA.IN9': 'Percent of firms owning or sharing a generator',
    'IC.FRM.INNOV.T1': 'Percent of firms with an internationally-recognized quality certification',
    'IC.FRM.INNOV.T10': 'Percent of firms that spend on R&D',
    'IC.FRM.INNOV.T2': 'Percent of firms with an annual financial statement reviewed by external auditors',
    'IC.FRM.INNOV.T3': 'Capacity utilization (%)',
    'IC.FRM.INNOV.T4': 'Percent of firms using technology licensed from foreign companies',
    'IC.FRM.INNOV.T5': 'Percent of firms having their own Web site',
    'IC.FRM.INNOV.T6': 'Percent of firms using e-mail to interact with clients/suppliers',
    'IC.FRM.INNOV.T7': 'Percent of firms that introduced a new product/service',
    'IC.FRM.INNOV.T8': 'Percent of firms whose new product/service is also new to the main market',
    'IC.FRM.INNOV.T9': 'Percent of firms that introduced a process innovation',
    'IC.FRM.OBS.OBST1': 'Percent of firms choosing access to finance as their biggest obstacle',
    'IC.FRM.OBS.OBST10': 'Percent of firms choosing labor regulations as their biggest obstacle',
    'IC.FRM.OBS.OBST11': 'Percent of firms choosing political instability as their biggest obstacle',
    'IC.FRM.OBS.OBST12': 'Percent of firms choosing practices of the informal sector as their biggest obstacle',
    'IC.FRM.OBS.OBST13': 'Percent of firms choosing tax administration as their biggest obstacle',
    'IC.FRM.OBS.OBST14': 'Percent of firms choosing tax rates as their biggest obstacle',
    'IC.FRM.OBS.OBST15': 'Percent of firms choosing transportation as their biggest obstacle',
    'IC.FRM.OBS.OBST2': 'Percent of firms choosing access to land as their biggest obstacle',
    'IC.FRM.OBS.OBST3': 'Percent of firms choosing business licensing and permits as their biggest obstacle',
    'IC.FRM.OBS.OBST4': 'Percent of firms choosing corruption as their biggest obstacle',
    'IC.FRM.OBS.OBST5': 'Percent of firms choosing courts as their biggest obstacle',
    'IC.FRM.OBS.OBST6': 'Percent of firms choosing crime, theft and disorder as their biggest obstacle',
    'IC.FRM.OBS.OBST7': 'Percent of firms choosing customs and trade regulations as their biggest obstacle',
    'IC.FRM.OBS.OBST8': 'Percent of firms choosing electricity as their biggest obstacle',
    'IC.FRM.OBS.OBST9': 'Percent of firms choosing inadequately educated workforce as their biggest obstacle',
    'IC.FRM.PROD.GROW.PEFT3': 'Real annual labor productivity growth (%)',
    'IC.FRM.REG.BUS1': 'Days to obtain an import license',
    'IC.FRM.REG.BUS2': 'Days to obtain an operating license',
    'IC.FRM.REG.BUS3': 'Days to obtain a construction-related permit',
    'IC.FRM.REG.BUS5': 'Percent of firms identifying business licensing and permits as a major constraint',
    'IC.FRM.REG.REG1': 'Senior management time spent dealing with the requirements of government regulation (%)',
    'IC.FRM.REG.REG2_C': 'If there were visits, average number of visits or required meetings with tax officials',
    'IC.FRM.REG.REG4': 'Percent of firms identifying tax rates as a major constraint',
    'IC.FRM.REG.REG5': 'Percent of firms identifying tax administration as a major constraint',
    'IC.FRM.REG.REG6': 'Percent of firms visited or required to meet with tax officials',
    'IC.FRM.SLS.GROW.PEFT1': 'Real annual sales growth (%)',
    'IC.FRM.TRD.TR1': 'Days to clear direct exports through customs',
    'IC.FRM.TRD.TR11': 'Percent of firms using material inputs and/or supplies of foreign origin',
    'IC.FRM.TRD.TR16': 'Percent of firms exporting directly (at least 10% of sales)',
    'IC.FRM.TRD.TR17': 'Percent of firms exporting directly or indirectly (at least 10% of sales)',
    'IC.FRM.TRD.TR2': 'Days to clear imports from customs',
    'IC.FRM.TRD.TR5': 'Proportion of total sales that are exported directly (%)',
    'IC.FRM.TRD.TR8': 'Proportion of total inputs that are of foreign origin (%)',
    'IC.FRM.TRD.TR9': 'Percent of firms identifying customs and trade regulations as a major constraint',
    'IC.FRM.WRKF.WK1': 'Percent of firms offering formal training',
    'IC.FRM.WRKF.WK10': 'Percent of firms identifying an inadequately educated workforce as a major constraint',
    'IC.FRM.WRKF.WK14': 'Number of workers',
    'IC.FRM.WRKF.WK15': 'Proportion of production workers (out of all permanent workers)',
    'IC.FRM.WRKF.WK17': 'Proportion of temporary workers (out of all workers)',
    'IC.FRM.WRKF.WK18': 'Proportion of permanent workers (out of all workers)',
    'IC.FRM.WRKF.WK19': 'Proportion of skilled workers (out of all production workers) (%)',
    'IC.FRM.WRKF.WK2': 'Proportion of workers offered formal training (%)',
    'IC.FRM.WRKF.WK8': "Years of the top manager's experience working in the firm's sector",
    'IC.FRM.WRKF.WK9': 'Percent of firms identifying labor regulations as a major constraint'}},
  'dir_hash': 'dfc9891c32572664f2e51c73da222636d4675fb2',
  'indexed_at': '2022-07-01T19:18:23.311Z',
  'name': 'Enterprise Surveys',
  'nb_series': 16790,
  'provider_code': 'WB',
  'provider_name': 'World Bank'},
 'errors': None,
 'provider': {'code': 'WB',
  'indexed_at': '2024-09-19T06:51:52.592Z',
  'name': 'World Bank',
  'region': 'World',
  'slug': 'wb',
  'website': 'https://www.worldbank.org/'},
 'series': {'docs': [{'dataset_code': 'ESY',
    'dataset_name': 'Enterprise Surveys',
    'dimensions': {'country': 'AFG',
     'frequency': 'A',
     'indicator': 'IC.FRM.BRIB.GRAFT2'},
    'indexed_at': '2022-07-01T19:18:23.311Z',
    'provider_code': 'WB',
    'series_code': 'A-IC.FRM.BRIB.GRAFT2-AFG',
    'series_name': 'Annual – Bribery depth (% of public transactions where a gift or informal payment was requested) – Afghanistan'},
   {'dataset_code': 'ESY',
    'dataset_name': 'Enterprise Surveys',
    'dimensions': {'country': 'AGO',
     'frequency': 'A',
     'indicator': 'IC.FRM.BRIB.GRAFT2'},
    'indexed_at': '2022-07-01T19:18:23.311Z',
    'provider_code': 'WB',
    'series_code': 'A-IC.FRM.BRIB.GRAFT2-AGO',
    'series_name': 'Annual – Bribery depth (% of public transactions where a gift or informal payment was requested) – Angola'},
   {'dataset_code': 'ESY',
    'dataset_name': 'Enterprise Surveys',
    'dimensions': {'country': 'ALB',
     'frequency': 'A',
     'indicator': 'IC.FRM.BRIB.GRAFT2'},
    'indexed_at': '2022-07-01T19:18:23.311Z',
    'provider_code': 'WB',
    'series_code': 'A-IC.FRM.BRIB.GRAFT2-ALB',
    'series_name': 'Annual – Bribery depth (% of public transactions where a gift or informal payment was requested) – Albania'},
   {'dataset_code': 'ESY',
    'dataset_name': 'Enterprise Surveys',
    'dimensions': {'country': 'ARG',
     'frequency': 'A',
     'indicator': 'IC.FRM.BRIB.GRAFT2'},
    'indexed_at': '2022-07-01T19:18:23.311Z',
    'provider_code': 'WB',
    'series_code': 'A-IC.FRM.BRIB.GRAFT2-ARG',
    'series_name': 'Annual – Bribery depth (% of public transactions where a gift or informal payment was requested) – Argentina'},
   {'dataset_code': 'ESY',
    'dataset_name': 'Enterprise Surveys',
    'dimensions': {'country': 'ARM',
     'frequency': 'A',
     'indicator': 'IC.FRM.BRIB.GRAFT2'},
    'indexed_at': '2022-07-01T19:18:23.311Z',
    'provider_code': 'WB',
    'series_code': 'A-IC.FRM.BRIB.GRAFT2-ARM',
    'series_name': 'Annual – Bribery depth (% of public transactions where a gift or informal payment was requested) – Armenia'},
   {'dataset_code': 'ESY',
    'dataset_name': 'Enterprise Surveys',
    'dimensions': {'country': 'ATG',
     'frequency': 'A',
     'indicator': 'IC.FRM.BRIB.GRAFT2'},
    'indexed_at': '2022-07-01T19:18:23.311Z',
    'provider_code': 'WB',
    'series_code': 'A-IC.FRM.BRIB.GRAFT2-ATG',
    'series_name': 'Annual – Bribery depth (% of public transactions where a gift or informal payment was requested) – Antigua and Barbuda'},
   {'dataset_code': 'ESY',
    'dataset_name': 'Enterprise Surveys',
    'dimensions': {'country': 'AZE',
     'frequency': 'A',
     'indicator': 'IC.FRM.BRIB.GRAFT2'},
    'indexed_at': '2022-07-01T19:18:23.311Z',
    'provider_code': 'WB',
    'series_code': 'A-IC.FRM.BRIB.GRAFT2-AZE',
    'series_name': 'Annual – Bribery depth (% of public transactions where a gift or informal payment was requested) – Azerbaijan'},
   {'dataset_code': 'ESY',
    'dataset_name': 'Enterprise Surveys',
    'dimensions': {'country': 'BDI',
     'frequency': 'A',
     'indicator': 'IC.FRM.BRIB.GRAFT2'},
    'indexed_at': '2022-07-01T19:18:23.311Z',
    'provider_code': 'WB',
    'series_code': 'A-IC.FRM.BRIB.GRAFT2-BDI',
    'series_name': 'Annual – Bribery depth (% of public transactions where a gift or informal payment was requested) – Burundi'},
   {'dataset_code': 'ESY',
    'dataset_name': 'Enterprise Surveys',
    'dimensions': {'country': 'BEL',
     'frequency': 'A',
     'indicator': 'IC.FRM.BRIB.GRAFT2'},
    'indexed_at': '2022-07-01T19:18:23.311Z',
    'provider_code': 'WB',
    'series_code': 'A-IC.FRM.BRIB.GRAFT2-BEL',
    'series_name': 'Annual – Bribery depth (% of public transactions where a gift or informal payment was requested) – Belgium'},
   {'dataset_code': 'ESY',
    'dataset_name': 'Enterprise Surveys',
    'dimensions': {'country': 'BEN',
     'frequency': 'A',
     'indicator': 'IC.FRM.BRIB.GRAFT2'},
    'indexed_at': '2022-07-01T19:18:23.311Z',
    'provider_code': 'WB',
    'series_code': 'A-IC.FRM.BRIB.GRAFT2-BEN',
    'series_name': 'Annual – Bribery depth (% of public transactions where a gift or informal payment was requested) – Benin'},
   {'dataset_code': 'ESY',
    'dataset_name': 'Enterprise Surveys',
    'dimensions': {'country': 'BFA',
     'frequency': 'A',
     'indicator': 'IC.FRM.BRIB.GRAFT2'},
    'indexed_at': '2022-07-01T19:18:23.311Z',
    'provider_code': 'WB',
    'series_code': 'A-IC.FRM.BRIB.GRAFT2-BFA',
    'series_name': 'Annual – Bribery depth (% of public transactions where a gift or informal payment was requested) – Burkina Faso'},
   {'dataset_code': 'ESY',
    'dataset_name': 'Enterprise Surveys',
    'dimensions': {'country': 'BGD',
     'frequency': 'A',
     'indicator': 'IC.FRM.BRIB.GRAFT2'},
    'indexed_at': '2022-07-01T19:18:23.311Z',
    'provider_code': 'WB',
    'series_code': 'A-IC.FRM.BRIB.GRAFT2-BGD',
    'series_name': 'Annual – Bribery depth (% of public transactions where a gift or informal payment was requested) – Bangladesh'},
   {'dataset_code': 'ESY',
    'dataset_name': 'Enterprise Surveys',
    'dimensions': {'country': 'BGR',
     'frequency': 'A',
     'indicator': 'IC.FRM.BRIB.GRAFT2'},

In [ ]:
d = r.json()
d.keys()

dict_keys(['_meta', 'dataset', 'errors', 'provider', 'series'])

In [ ]:
d['series']

{'docs': [{'dataset_code': 'ESY',
   'dataset_name': 'Enterprise Surveys',
   'dimensions': {'country': 'CHN',
    'frequency': 'A',
    'indicator': 'IC.FRM.BRIB.GRAFT2'},
   'indexed_at': '2022-07-01T19:18:23.311Z',
   'provider_code': 'WB',
   'series_code': 'A-IC.FRM.BRIB.GRAFT2-CHN',
   'series_name': 'Annual – Bribery depth (% of public transactions where a gift or informal payment was requested) – China'}],
 'limit': 1000,
 'num_found': 1,
 'offset': 0}

In [ ]:
d['dataset'].keys()

dict_keys(['code', 'dimensions_codes_order', 'dimensions_values_labels', 'dir_hash', 'indexed_at', 'name', 'nb_series', 'provider_code', 'provider_name'])

In [ ]:
d['dataset']['dimensions_values_labels'].keys()

dict_keys(['country', 'frequency', 'indicator'])

In [ ]:
d['dataset']['dimensions_values_labels']

{'country': {'AFG': 'Afghanistan',
  'AGO': 'Angola',
  'ALB': 'Albania',
  'ARG': 'Argentina',
  'ARM': 'Armenia',
  'ATG': 'Antigua and Barbuda',
  'AZE': 'Azerbaijan',
  'BDI': 'Burundi',
  'BEL': 'Belgium',
  'BEN': 'Benin',
  'BFA': 'Burkina Faso',
  'BGD': 'Bangladesh',
  'BGR': 'Bulgaria',
  'BHS': 'Bahamas, The',
  'BIH': 'Bosnia and Herzegovina',
  'BLR': 'Belarus',
  'BLZ': 'Belize',
  'BOL': 'Bolivia',
  'BRA': 'Brazil',
  'BRB': 'Barbados',
  'BTN': 'Bhutan',
  'BWA': 'Botswana',
  'CAF': 'Central African Republic',
  'CHL': 'Chile',
  'CHN': 'China',
  'CIV': "Cote d'Ivoire",
  'CMR': 'Cameroon',
  'COD': 'Congo, Dem. Rep.',
  'COG': 'Congo, Rep.',
  'COL': 'Colombia',
  'CPV': 'Cabo Verde',
  'CRI': 'Costa Rica',
  'CYP': 'Cyprus',
  'CZE': 'Czech Republic',
  'DJI': 'Djibouti',
  'DMA': 'Dominica',
  'DOM': 'Dominican Republic',
  'ECU': 'Ecuador',
  'EGY': 'Egypt, Arab Rep.',
  'ERI': 'Eritrea',
  'EST': 'Estonia',
  'ETH': 'Ethiopia',
  'FJI': 'Fiji',
  'FSM': 'Micronesia, Fed. Sts.',
  'GAB': 'Gabon',
  'GEO': 'Georgia',
  'GHA': 'Ghana',
  'GIN': 'Guinea',
  'GMB': 'Gambia, The',
  'GNB': 'Guinea-Bissau',
  'GRC': 'Greece',
  'GRD': 'Grenada',
  'GTM': 'Guatemala',
  'GUY': 'Guyana',
  'HND': 'Honduras',
  'HRV': 'Croatia',
  'HUN': 'Hungary',
  'IDN': 'Indonesia',
  'IND': 'India',
  'IRQ': 'Iraq',
  'ISR': 'Israel',
  'ITA': 'Italy',
  'JAM': 'Jamaica',
  'JOR': 'Jordan',
  'KAZ': 'Kazakhstan',
  'KEN': 'Kenya',
  'KGZ': 'Kyrgyz Republic',
  'KHM': 'Cambodia',
  'KNA': 'St. Kitts and Nevis',
  'LAO': 'Lao PDR',
  'LBN': 'Lebanon',
  'LBR': 'Liberia',
  'LCA': 'St. Lucia',
  'LKA': 'Sri Lanka',
  'LSO': 'Lesotho',
  'LTU': 'Lithuania',
  'LUX': 'Luxembourg',
  'LVA': 'Latvia',
  'MAR': 'Morocco',
  'MDA': 'Moldova',
  'MDG': 'Madagascar',
  'MEX': 'Mexico',
  'MKD': 'North Macedonia',
  'MLI': 'Mali',
  'MLT': 'Malta',
  'MMR': 'Myanmar',
  'MNE': 'Montenegro',
  'MNG': 'Mongolia',
  'MOZ': 'Mozambique',
  'MRT': 'Mauritania',
  'MUS': 'Mauritius',
  'MWI': 'Malawi',
  'MYS': 'Malaysia',
  'NAM': 'Namibia',
  'NER': 'Niger',
  'NGA': 'Nigeria',
  'NIC': 'Nicaragua',
  'NPL': 'Nepal',
  'PAK': 'Pakistan',
  'PAN': 'Panama',
  'PER': 'Peru',
  'PHL': 'Philippines',
  'PNG': 'Papua New Guinea',
  'POL': 'Poland',
  'PRT': 'Portugal',
  'PRY': 'Paraguay',
  'PSE': 'West Bank and Gaza',
  'ROU': 'Romania',
  'RUS': 'Russian Federation',
  'RWA': 'Rwanda',
  'SDN': 'Sudan',
  'SEN': 'Senegal',
  'SLB': 'Solomon Islands',
  'SLE': 'Sierra Leone',
  'SLV': 'El Salvador',
  'SRB': 'Serbia',
  'SSD': 'South Sudan',
  'SUR': 'Suriname',
  'SVK': 'Slovak Republic',
  'SVN': 'Slovenia',
  'SWE': 'Sweden',
  'SWZ': 'Eswatini',
  'TCD': 'Chad',
  'TGO': 'Togo',
  'THA': 'Thailand',
  'TJK': 'Tajikistan',
  'TLS': 'Timor-Leste',
  'TON': 'Tonga',
  'TTO': 'Trinidad and Tobago',
  'TUN': 'Tunisia',
  'TUR': 'Turkey',
  'TZA': 'Tanzania',
  'UGA': 'Uganda',
  'UKR': 'Ukraine',
  'URY': 'Uruguay',
  'UZB': 'Uzbekistan',
  'VCT': 'St. Vincent and the Grenadines',
  'VEN': 'Venezuela, RB',
  'VNM': 'Vietnam',
  'VUT': 'Vanuatu',
  'WSM': 'Samoa',
  'XKX': 'Kosovo',
  'YEM': 'Yemen, Rep.',
  'ZAF': 'South Africa',
  'ZMB': 'Zambia',
  'ZWE': 'Zimbabwe'},
 'frequency': {'A': 'Annual'},
 'indicator': {'IC.FRM.BRIB.GRAFT2': 'Bribery depth (% of public transactions where a gift or informal payment was requested)',
  'IC.FRM.BRIB.GRAFT3': 'Bribery incidence (percent of firms experiencing at least one bribe payment request)',
  'IC.FRM.CORR.CORR1': 'Percent of firms expected to give gifts in meetings with tax officials',
  'IC.FRM.CORR.CORR10': 'Percent of firms expected to give gifts to get an operating license',
  'IC.FRM.CORR.CORR11': 'Percent of firms identifying corruption as a major constraint',
  'IC.FRM.CORR.CORR2': 'Percent of firms expected to give gifts to secure government contract',
  'IC.FRM.CORR.CORR3': 'Value of gift expected to secure a government contract (% of contract value)',
  'IC.FRM.CORR.CORR4': 'Percent of firms expected to give gifts to public officials "to get things done"',
  'IC.FRM.CORR.CORR6': 'Percent of firms expected to give gifts to get an electrical connection',
  'IC.FRM.CORR.CORR7': 'Percent of firms expected to give gifts to get a water connection',
  'IC.FRM.CORR.CORR8': 'Percent of firms expected to give gifts to get a construction permit',
  'IC.FRM.CORR.CORR9': 'Percent of firms expected to give gifts to get an import license',
  'IC.FRM.CORR.CRIME9': 'Percent of firms identifying the courts system as a major constraint',
  'IC.FRM.CRM.CRIME1': 'Percent of firms paying for security',
  'IC.FRM.CRM.CRIME10': 'Percent of firms experiencing losses due to theft and vandalism',
  'IC.FRM.CRM.CRIME2_C': 'If the establishment pays for security, average security costs (% of annual sales)',
  'IC.FRM.CRM.CRIME3_C': 'If there were losses, average losses due to theft and vandalism (% of annual sales)',
  'IC.FRM.CRM.CRIME5': 'Products shipped to supply domestic markets that were lost due to theft (% of product value)',
  'IC.FRM.CRM.CRIME8': 'Percent of firms identifying crime, theft and disorder as a major constraint',
  'IC.FRM.EMP.GROW.PEFT2': 'Annual employment growth (%)',
  'IC.FRM.FCHAR.CAR1': 'Age of the establishment (years)',
  'IC.FRM.FCHAR.CAR2': 'Proportion of private domestic ownership in a firm (%)',
  'IC.FRM.FCHAR.CAR7': 'Percent of firms with at least 10% of foreign ownership',
  'IC.FRM.FCHAR.CAR8': 'Percent of firms with at least 10% of government/state ownership',
  'IC.FRM.FCHAR.LFORM3': 'Percent of firms with legal status of Sole Proprietorship',
  'IC.FRM.FIAS.PEFT4': 'Percent of firms buying fixed assets',
  'IC.FRM.FIN.FIN1': 'Proportion of investment financed internally (%)',
  'IC.FRM.FIN.FIN10': 'Value of collateral needed for a loan (% of the loan amount)',
  'IC.FRM.FIN.FIN11': 'Proportion of loans requiring collateral (%)',
  'IC.FRM.FIN.FIN12': 'Percent of firms using banks to finance investments',
  'IC.FRM.FIN.FIN13': 'Percent of firms using banks to finance working capital',
  'IC.FRM.FIN.FIN14': 'Percent of firms with a bank loan/line of credit',
  'IC.FRM.FIN.FIN15': 'Percent of firms with a checking or savings account',
  'IC.FRM.FIN.FIN16': 'Percent of firms identifying access to finance as a major constraint',
  'IC.FRM.FIN.FIN2': 'Proportion of investment financed by banks (%)',
  'IC.FRM.FIN.FIN20': 'Percent of firms not needing a loan',
  'IC.FRM.FIN.FIN21': 'Percent of firms whose recent loan application was rejected',
  'IC.FRM.FIN.FIN22': 'Percent of firms using supplier/customer credit to finance working capital',
  'IC.FRM.FIN.FIN7': 'Proportion of working capital financed by banks (%)',
  'IC.FRM.GEN.GEND1': 'Percent of firms with female participation in ownership',
  'IC.FRM.GEN.GEND2': 'Proportion of permanent full-time workers that are female (%)',
  'IC.FRM.GEN.GEND3': 'Proportion of permanent full-time non-production workers that are female (%)',
  'IC.FRM.GEN.GEND4': 'Percent of firms with a female top manager',
  'IC.FRM.GEN.GEND5': 'Proportion of permanent full-time production workers that are female (%)',
  'IC.FRM.GEN.GEND6': 'Percent of firms with majority female ownership',
  'IC.FRM.INFOR.INFOR1': 'Percent of firms competing against unregistered or informal firms',
  'IC.FRM.INFOR.INFOR2': 'Percent of firms identifying practices of competitors in the informal sector as a major constraint',
  'IC.FRM.INFOR.INFOR4': 'Percent of firms formally registered when they started operations in the country',
  'IC.FRM.INFOR.INFOR5': 'Number of years firm operated without formal registration',
  'IC.FRM.INFRA.IN1': 'Days to obtain an electrical connection (upon application)',
  'IC.FRM.INFRA.IN10_C': 'If a generator is used, average proportion of electricity from a generator (%)',
  'IC.FRM.INFRA.IN11': 'Percent of firms identifying transportation as a major constraint',
  'IC.FRM.INFRA.IN12': 'Percent of firms identifying electricity as a major constraint',
  'IC.FRM.INFRA.IN14': 'Proportion of products lost to breakage or spoilage during shipping to domestic markets (%)',
  'IC.FRM.INFRA.IN16': 'Percent of firms experiencing electrical outages',
  'IC.FRM.INFRA.IN17': 'Percent of firms experiencing water insufficiencies',
  'IC.FRM.INFRA.IN2': 'Number of electrical outages in a typical month',
  'IC.FRM.INFRA.IN3_C': 'If there were outages, average duration of a typical electrical outage (hours)',
  'IC.FRM.INFRA.IN4_C': 'If there were outages, average losses due to electrical outages (% of annual sales)',
  'IC.FRM.INFRA.IN6': 'Number of water insufficiencies in a typical month',
  'IC.FRM.INFRA.IN9': 'Percent of firms owning or sharing a generator',
  'IC.FRM.INNOV.T1': 'Percent of firms with an internationally-recognized quality certification',
  'IC.FRM.INNOV.T10': 'Percent of firms that spend on R&D',
  'IC.FRM.INNOV.T2': 'Percent of firms with an annual financial statement reviewed by external auditors',
  'IC.FRM.INNOV.T3': 'Capacity utilization (%)',
  'IC.FRM.INNOV.T4': 'Percent of firms using technology licensed from foreign companies',
  'IC.FRM.INNOV.T5': 'Percent of firms having their own Web site',
  'IC.FRM.INNOV.T6': 'Percent of firms using e-mail to interact with clients/suppliers',
  'IC.FRM.INNOV.T7': 'Percent of firms that introduced a new product/service',
  'IC.FRM.INNOV.T8': 'Percent of firms whose new product/service is also new to the main market',
  'IC.FRM.INNOV.T9': 'Percent of firms that introduced a process innovation',
  'IC.FRM.OBS.OBST1': 'Percent of firms choosing access to finance as their biggest obstacle',
  'IC.FRM.OBS.OBST10': 'Percent of firms choosing labor regulations as their biggest obstacle',
  'IC.FRM.OBS.OBST11': 'Percent of firms choosing political instability as their biggest obstacle',
  'IC.FRM.OBS.OBST12': 'Percent of firms choosing practices of the informal sector as their biggest obstacle',
  'IC.FRM.OBS.OBST13': 'Percent of firms choosing tax administration as their biggest obstacle',
  'IC.FRM.OBS.OBST14': 'Percent of firms choosing tax rates as their biggest obstacle',
  'IC.FRM.OBS.OBST15': 'Percent of firms choosing transportation as their biggest obstacle',
  'IC.FRM.OBS.OBST2': 'Percent of firms choosing access to land as their biggest obstacle',
  'IC.FRM.OBS.OBST3': 'Percent of firms choosing business licensing and permits as their biggest obstacle',
  'IC.FRM.OBS.OBST4': 'Percent of firms choosing corruption as their biggest obstacle',
  'IC.FRM.OBS.OBST5': 'Percent of firms choosing courts as their biggest obstacle',
  'IC.FRM.OBS.OBST6': 'Percent of firms choosing crime, theft and disorder as their biggest obstacle',
  'IC.FRM.OBS.OBST7': 'Percent of firms choosing customs and trade regulations as their biggest obstacle',
  'IC.FRM.OBS.OBST8': 'Percent of firms choosing electricity as their biggest obstacle',
  'IC.FRM.OBS.OBST9': 'Percent of firms choosing inadequately educated workforce as their biggest obstacle',
  'IC.FRM.PROD.GROW.PEFT3': 'Real annual labor productivity growth (%)',
  'IC.FRM.REG.BUS1': 'Days to obtain an import license',
  'IC.FRM.REG.BUS2': 'Days to obtain an operating license',
  'IC.FRM.REG.BUS3': 'Days to obtain a construction-related permit',
  'IC.FRM.REG.BUS5': 'Percent of firms identifying business licensing and permits as a major constraint',
  'IC.FRM.REG.REG1': 'Senior management time spent dealing with the requirements of government regulation (%)',
  'IC.FRM.REG.REG2_C': 'If there were visits, average number of visits or required meetings with tax officials',
  'IC.FRM.REG.REG4': 'Percent of firms identifying tax rates as a major constraint',
  'IC.FRM.REG.REG5': 'Percent of firms identifying tax administration as a major constraint',
  'IC.FRM.REG.REG6': 'Percent of firms visited or required to meet with tax officials',
  'IC.FRM.SLS.GROW.PEFT1': 'Real annual sales growth (%)',
  'IC.FRM.TRD.TR1': 'Days to clear direct exports through customs',
  'IC.FRM.TRD.TR11': 'Percent of firms using material inputs and/or supplies of foreign origin',
  'IC.FRM.TRD.TR16': 'Percent of firms exporting directly (at least 10% of sales)',
  'IC.FRM.TRD.TR17': 'Percent of firms exporting directly or indirectly (at least 10% of sales)',
  'IC.FRM.TRD.TR2': 'Days to clear imports from customs',
  'IC.FRM.TRD.TR5': 'Proportion of total sales that are exported directly (%)',
  'IC.FRM.TRD.TR8': 'Proportion of total inputs that are of foreign origin (%)',
  'IC.FRM.TRD.TR9': 'Percent of firms identifying customs and trade regulations as a major constraint',
  'IC.FRM.WRKF.WK1': 'Percent of firms offering formal training',
  'IC.FRM.WRKF.WK10': 'Percent of firms identifying an inadequately educated workforce as a major constraint',
  'IC.FRM.WRKF.WK14': 'Number of workers',
  'IC.FRM.WRKF.WK15': 'Proportion of production workers (out of all permanent workers)',
  'IC.FRM.WRKF.WK17': 'Proportion of temporary workers (out of all workers)',
  'IC.FRM.WRKF.WK18': 'Proportion of permanent workers (out of all workers)',
  'IC.FRM.WRKF.WK19': 'Proportion of skilled workers (out of all production workers) (%)',
  'IC.FRM.WRKF.WK2': 'Proportion of workers offered formal training (%)',
  'IC.FRM.WRKF.WK8': "Years of the top manager's experience working in the firm's sector",
  'IC.FRM.WRKF.WK9': 'Percent of firms identifying labor regulations as a major constraint'}}