# 1 - Imports

In [4]:
%reload_ext autoreload
%autoreload 2

In [5]:
import sys
from pathlib import Path

sys.path.append(str(Path().resolve().parents[0]))

In [6]:
import pandas as pd
import numpy as np

In [7]:
from src.utils import templates, config, io

# 2 - Intigration

In [15]:
import pandas as pd
import numpy as np
from sklearn.feature_selection import VarianceThreshold, mutual_info_regression

In [16]:
dataset = io.load_csv(config.PROCESSED_DATA_DIR / 'final_dataset.csv', index_col=0)
dataset

,YEAR,ISO3_COUNTRY_CODE,OECD_RATING,GEO_REGION,ADMIN_REGION,LENDING_TYPE,INCOME_GROUP,NY.GDP.MKTP.CD,NY.GDP.MKTP.KD.ZG,NY.GDP.MKTP.PP.CD,...,SE.PRM.CUAT.ZS,SP.POP.DPND,SL.TLF.CACT.ZS,GE.EST,RQ.EST,IC.BRE.BI.OS,IC.BRE.BE.OS,IQ.CPA.PADM.XQ,FS.AST.PRVT.GD.ZS,FM.AST.PRVT.GD.ZS
COUNTRY_PERIOD_INDEX,,,,,,,,,,,,,,,,,,,,,
AFG-1999,1999,AFG,7,MEA,MNA,IDX,LIC,NaN,NaN,NaN,...,NaN,108.686031,46.609,NaN,NaN,NaN,NaN,NaN,NaN,NaN
AFG-2000,2000,AFG,7,MEA,MNA,IDX,LIC,3.521418e+09,NaN,1.637703e+10,...,NaN,109.586048,46.562,-2.173946,-2.080253,NaN,NaN,NaN,NaN,NaN
AFG-2001,2001,AFG,-,MEA,MNA,IDX,LIC,2.813572e+09,-9.431974,1.516633e+10,...,NaN,110.219341,46.526,NaN,NaN,NaN,NaN,NaN,NaN,NaN
AFG-2002,2002,AFG,-,MEA,MNA,IDX,LIC,3.825701e+09,28.600001,1.980700e+10,...,NaN,110.534611,46.505,-1.587687,-1.811546,NaN,NaN,NaN,NaN,NaN
AFG-2003,2003,AFG,-,MEA,MNA,IDX,LIC,4.520947e+09,8.832278,2.198200e+10,...,NaN,110.557540,46.497,-1.175768,-1.463108,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ZWE-2019,2019,ZWE,7,SSF,SSA,IDB,LMC,3.335770e+10,-6.332450,6.361373e+10,...,75.001228,85.447906,65.795,-1.310435,-1.486515,NaN,NaN,3.0,3.428022,3.428022
ZWE-2020,2020,ZWE,7,SSF,SSA,IDB,LMC,3.198033e+10,-7.816951,6.488043e+10,...,NaN,84.384381,64.665,-1.342368,-1.434415,NaN,NaN,3.0,3.642132,3.642132
ZWE-2021,2021,ZWE,7,SSF,SSA,IDB,LMC,4.128767e+10,8.468017,7.625453e+10,...,NaN,83.384953,65.397,-1.290561,-1.386109,NaN,NaN,3.0,4.759522,4.759522
ZWE-2022,2022,ZWE,7,SSF,SSA,IDB,LMC,4.075756e+10,6.139263,8.670632e+10,...,NaN,82.547605,65.214,-1.251224,-1.425967,NaN,NaN,3.0,5.826323,5.826323
ZWE-2023,2023,ZWE,7,SSF,SSA,IDB,LMC,3.587178e+10,5.350869,9.463284e+10,...,NaN,81.625352,67.786,-1.170335,-1.338359,NaN,NaN,3.0,6.477697,6.477697

In [75]:
dataset = dataset[dataset['OECD_RATING'] != '-']
dataset

,YEAR,ISO3_COUNTRY_CODE,OECD_RATING,GEO_REGION,ADMIN_REGION,LENDING_TYPE,INCOME_GROUP,NY.GDP.MKTP.CD,NY.GDP.MKTP.KD.ZG,NY.GDP.MKTP.PP.CD,...,SE.PRM.CUAT.ZS,SP.POP.DPND,SL.TLF.CACT.ZS,GE.EST,RQ.EST,IC.BRE.BI.OS,IC.BRE.BE.OS,IQ.CPA.PADM.XQ,FS.AST.PRVT.GD.ZS,FM.AST.PRVT.GD.ZS
COUNTRY_PERIOD_INDEX,,,,,,,,,,,,,,,,,,,,,
AFG-1999,1999,AFG,7,MEA,MNA,IDX,LIC,NaN,NaN,NaN,...,NaN,108.686031,46.609,NaN,NaN,NaN,NaN,NaN,NaN,NaN
AFG-2000,2000,AFG,7,MEA,MNA,IDX,LIC,3.521418e+09,NaN,1.637703e+10,...,NaN,109.586048,46.562,-2.173946,-2.080253,NaN,NaN,NaN,NaN,NaN
AFG-2008,2008,AFG,7,MEA,MNA,IDX,LIC,1.010930e+10,3.924984,3.532112e+10,...,NaN,106.334376,46.682,-1.527795,-1.607167,NaN,NaN,2.0,9.388328,9.388328
AFG-2009,2009,AFG,7,MEA,MNA,IDX,LIC,1.241615e+10,21.390528,4.314095e+10,...,NaN,104.799467,46.746,-1.507752,-1.664508,NaN,NaN,2.0,10.584131,10.584131
AFG-2010,2010,AFG,7,MEA,MNA,IDX,LIC,1.585667e+10,14.362441,4.993663e+10,...,NaN,103.144456,46.815,-1.478316,-1.516528,NaN,NaN,2.0,11.575044,11.575044
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ZWE-2019,2019,ZWE,7,SSF,SSA,IDB,LMC,3.335770e+10,-6.332450,6.361373e+10,...,75.001228,85.447906,65.795,-1.310435,-1.486515,NaN,NaN,3.0,3.428022,3.428022
ZWE-2020,2020,ZWE,7,SSF,SSA,IDB,LMC,3.198033e+10,-7.816951,6.488043e+10,...,NaN,84.384381,64.665,-1.342368,-1.434415,NaN,NaN,3.0,3.642132,3.642132
ZWE-2021,2021,ZWE,7,SSF,SSA,IDB,LMC,4.128767e+10,8.468017,7.625453e+10,...,NaN,83.384953,65.397,-1.290561,-1.386109,NaN,NaN,3.0,4.759522,4.759522
ZWE-2022,2022,ZWE,7,SSF,SSA,IDB,LMC,4.075756e+10,6.139263,8.670632e+10,...,NaN,82.547605,65.214,-1.251224,-1.425967,NaN,NaN,3.0,5.826323,5.826323
ZWE-2023,2023,ZWE,7,SSF,SSA,IDB,LMC,3.587178e+10,5.350869,9.463284e+10,...,NaN,81.625352,67.786,-1.170335,-1.338359,NaN,NaN,3.0,6.477697,6.477697

In [76]:
def filter_missingness(
    X: pd.DataFrame,
    max_missing_ratio: float = 0.5
) -> pd.DataFrame:
    missing_ratio = X.isna().mean()
    keep_cols = missing_ratio[missing_ratio <= max_missing_ratio].index

    
    return X[keep_cols]


def filter_low_variance(
    X: pd.DataFrame,
    threshold: float = 1e-4
) -> pd.DataFrame:
    
    float_features = X.columns[X.dtypes==float]
    non_float_features = X.columns[X.dtypes!=float]

    selector = VarianceThreshold(threshold=threshold)
    selector.fit(X[float_features].fillna(0))

    return X.loc[:, list(non_float_features) + list(selector.get_feature_names_out())]


def filter_correlated(
    X: pd.DataFrame,
    max_corr: float = 0.9
) -> pd.DataFrame:
    corr = X.corr().abs()
    upper = corr.where(np.triu(np.ones(corr.shape), k=1).astype(bool))
    drop_cols = [c for c in upper.columns if any(upper[c] > max_corr)]
    return X.drop(columns=drop_cols)


def select_by_mutual_information(
    X: pd.DataFrame,
    y: pd.Series,
    top_k: int = 100
) -> pd.DataFrame:
    mi = mutual_info_regression(X.fillna(0), y)
    scores = pd.Series(mi, index=X.columns)
    keep = scores.sort_values(ascending=False).head(top_k).index
    return X[keep]

In [77]:
dataset_clean= filter_missingness(dataset, max_missing_ratio=0.5)
dataset_clean

,YEAR,ISO3_COUNTRY_CODE,OECD_RATING,GEO_REGION,ADMIN_REGION,LENDING_TYPE,INCOME_GROUP,NY.GDP.MKTP.CD,NY.GDP.MKTP.KD.ZG,NY.GDP.MKTP.PP.CD,...,SP.POP.TOTL,SP.POP.GROW,SP.URB.TOTL.IN.ZS,EN.POP.DNST,SP.POP.DPND,SL.TLF.CACT.ZS,GE.EST,RQ.EST,FS.AST.PRVT.GD.ZS,FM.AST.PRVT.GD.ZS
COUNTRY_PERIOD_INDEX,,,,,,,,,,,,,,,,,,,,,
AFG-1999,1999,AFG,7,MEA,MNA,IDX,LIC,NaN,NaN,NaN,...,19887785.0,3.728116,18.390327,30.491981,108.686031,46.609,NaN,NaN,NaN,NaN
AFG-2000,2000,AFG,7,MEA,MNA,IDX,LIC,3.521418e+09,NaN,1.637703e+10,...,20130327.0,1.212176,18.558200,30.863847,109.586048,46.562,-2.173946,-2.080253,NaN,NaN
AFG-2008,2008,AFG,7,MEA,MNA,IDX,LIC,1.010930e+10,3.924984,3.532112e+10,...,26482622.0,2.186546,21.124148,40.603195,106.334376,46.682,-1.527795,-1.607167,9.388328,9.388328
AFG-2009,2009,AFG,7,MEA,MNA,IDX,LIC,1.241615e+10,21.390528,4.314095e+10,...,27466101.0,3.646381,21.688548,42.111067,104.799467,46.746,-1.507752,-1.664508,10.584131,10.584131
AFG-2010,2010,AFG,7,MEA,MNA,IDX,LIC,1.585667e+10,14.362441,4.993663e+10,...,28284089.0,2.934687,22.261480,43.365207,103.144456,46.815,-1.478316,-1.516528,11.575044,11.575044
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ZWE-2019,2019,ZWE,7,SSF,SSA,IDB,LMC,3.335770e+10,-6.332450,6.361373e+10,...,15271368.0,1.563534,36.183764,39.476200,85.447906,65.795,-1.310435,-1.486515,3.428022,3.428022
ZWE-2020,2020,ZWE,7,SSF,SSA,IDB,LMC,3.198033e+10,-7.816951,6.488043e+10,...,15526888.0,1.659353,37.009767,40.136714,84.384381,64.665,-1.342368,-1.434415,3.642132,3.642132
ZWE-2021,2021,ZWE,7,SSF,SSA,IDB,LMC,4.128767e+10,8.468017,7.625453e+10,...,15797210.0,1.726011,37.869206,40.835492,83.384953,65.397,-1.290561,-1.386109,4.759522,4.759522
ZWE-2022,2022,ZWE,7,SSF,SSA,IDB,LMC,4.075756e+10,6.139263,8.670632e+10,...,16069056.0,1.706209,38.705521,41.538209,82.547605,65.214,-1.251224,-1.425967,5.826323,5.826323
ZWE-2023,2023,ZWE,7,SSF,SSA,IDB,LMC,3.587178e+10,5.350869,9.463284e+10,...,16340822.0,1.677096,39.291937,42.240719,81.625352,67.786,-1.170335,-1.338359,6.477697,6.477697

In [78]:
# float_features = dataset_clean.columns[dataset_clean.dtypes==float]
non_float_features = dataset_clean.columns[dataset_clean.dtypes!=float]

In [79]:
dataset_clean = dataset_clean[non_float_features].join(filter_low_variance(dataset_clean.drop(columns=non_float_features)))
dataset_clean

,YEAR,ISO3_COUNTRY_CODE,OECD_RATING,GEO_REGION,ADMIN_REGION,LENDING_TYPE,INCOME_GROUP,NY.GDP.MKTP.CD,NY.GDP.MKTP.KD.ZG,NY.GDP.MKTP.PP.CD,...,SP.POP.TOTL,SP.POP.GROW,SP.URB.TOTL.IN.ZS,EN.POP.DNST,SP.POP.DPND,SL.TLF.CACT.ZS,GE.EST,RQ.EST,FS.AST.PRVT.GD.ZS,FM.AST.PRVT.GD.ZS
COUNTRY_PERIOD_INDEX,,,,,,,,,,,,,,,,,,,,,
AFG-1999,1999,AFG,7,MEA,MNA,IDX,LIC,NaN,NaN,NaN,...,19887785.0,3.728116,18.390327,30.491981,108.686031,46.609,NaN,NaN,NaN,NaN
AFG-2000,2000,AFG,7,MEA,MNA,IDX,LIC,3.521418e+09,NaN,1.637703e+10,...,20130327.0,1.212176,18.558200,30.863847,109.586048,46.562,-2.173946,-2.080253,NaN,NaN
AFG-2008,2008,AFG,7,MEA,MNA,IDX,LIC,1.010930e+10,3.924984,3.532112e+10,...,26482622.0,2.186546,21.124148,40.603195,106.334376,46.682,-1.527795,-1.607167,9.388328,9.388328
AFG-2009,2009,AFG,7,MEA,MNA,IDX,LIC,1.241615e+10,21.390528,4.314095e+10,...,27466101.0,3.646381,21.688548,42.111067,104.799467,46.746,-1.507752,-1.664508,10.584131,10.584131
AFG-2010,2010,AFG,7,MEA,MNA,IDX,LIC,1.585667e+10,14.362441,4.993663e+10,...,28284089.0,2.934687,22.261480,43.365207,103.144456,46.815,-1.478316,-1.516528,11.575044,11.575044
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ZWE-2019,2019,ZWE,7,SSF,SSA,IDB,LMC,3.335770e+10,-6.332450,6.361373e+10,...,15271368.0,1.563534,36.183764,39.476200,85.447906,65.795,-1.310435,-1.486515,3.428022,3.428022
ZWE-2020,2020,ZWE,7,SSF,SSA,IDB,LMC,3.198033e+10,-7.816951,6.488043e+10,...,15526888.0,1.659353,37.009767,40.136714,84.384381,64.665,-1.342368,-1.434415,3.642132,3.642132
ZWE-2021,2021,ZWE,7,SSF,SSA,IDB,LMC,4.128767e+10,8.468017,7.625453e+10,...,15797210.0,1.726011,37.869206,40.835492,83.384953,65.397,-1.290561,-1.386109,4.759522,4.759522
ZWE-2022,2022,ZWE,7,SSF,SSA,IDB,LMC,4.075756e+10,6.139263,8.670632e+10,...,16069056.0,1.706209,38.705521,41.538209,82.547605,65.214,-1.251224,-1.425967,5.826323,5.826323
ZWE-2023,2023,ZWE,7,SSF,SSA,IDB,LMC,3.587178e+10,5.350869,9.463284e+10,...,16340822.0,1.677096,39.291937,42.240719,81.625352,67.786,-1.170335,-1.338359,6.477697,6.477697

In [80]:
dataset_clean = dataset_clean[non_float_features].join(filter_correlated(dataset_clean.drop(columns=non_float_features)))
dataset_clean

,YEAR,ISO3_COUNTRY_CODE,OECD_RATING,GEO_REGION,ADMIN_REGION,LENDING_TYPE,INCOME_GROUP,NY.GDP.MKTP.CD,NY.GDP.MKTP.KD.ZG,NY.GDP.PCAP.CD,...,SL.UEM.BASC.ZS,EN.URB.LCTY.UR.ZS,SP.POP.TOTL,SP.POP.GROW,SP.URB.TOTL.IN.ZS,EN.POP.DNST,SP.POP.DPND,SL.TLF.CACT.ZS,GE.EST,FS.AST.PRVT.GD.ZS
COUNTRY_PERIOD_INDEX,,,,,,,,,,,,,,,,,,,,,
AFG-1999,1999,AFG,7,MEA,MNA,IDX,LIC,NaN,NaN,NaN,...,NaN,62.832635,19887785.0,3.728116,18.390327,30.491981,108.686031,46.609,NaN,NaN
AFG-2000,2000,AFG,7,MEA,MNA,IDX,LIC,3.521418e+09,NaN,174.930991,...,NaN,64.272506,20130327.0,1.212176,18.558200,30.863847,109.586048,46.562,-2.173946,NaN
AFG-2008,2008,AFG,7,MEA,MNA,IDX,LIC,1.010930e+10,3.924984,381.733238,...,NaN,55.947738,26482622.0,2.186546,21.124148,40.603195,106.334376,46.682,-1.527795,9.388328
AFG-2009,2009,AFG,7,MEA,MNA,IDX,LIC,1.241615e+10,21.390528,452.053705,...,NaN,53.859058,27466101.0,3.646381,21.688548,42.111067,104.799467,46.746,-1.507752,10.584131
AFG-2010,2010,AFG,7,MEA,MNA,IDX,LIC,1.585667e+10,14.362441,560.621505,...,NaN,52.235805,28284089.0,2.934687,22.261480,43.365207,103.144456,46.815,-1.478316,11.575044
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ZWE-2019,2019,ZWE,7,SSF,SSA,IDB,LMC,3.335770e+10,-6.332450,2184.329239,...,6.506,27.531274,15271368.0,1.563534,36.183764,39.476200,85.447906,65.795,-1.310435,3.428022
ZWE-2020,2020,ZWE,7,SSF,SSA,IDB,LMC,3.198033e+10,-7.816951,2059.674454,...,NaN,26.623672,15526888.0,1.659353,37.009767,40.136714,84.384381,64.665,-1.342368,3.642132
ZWE-2021,2021,ZWE,7,SSF,SSA,IDB,LMC,4.128767e+10,8.468017,2613.605421,...,8.016,25.773192,15797210.0,1.726011,37.869206,40.835492,83.384953,65.397,-1.290561,4.759522
ZWE-2022,2022,ZWE,7,SSF,SSA,IDB,LMC,4.075756e+10,6.139263,2536.400502,...,8.878,25.045614,16069056.0,1.706209,38.705521,41.538209,82.547605,65.214,-1.251224,5.826323
ZWE-2023,2023,ZWE,7,SSF,SSA,IDB,LMC,3.587178e+10,5.350869,2195.224921,...,8.493,24.579040,16340822.0,1.677096,39.291937,42.240719,81.625352,67.786,-1.170335,6.477697

In [81]:
dataset_clean = dataset_clean[non_float_features].join(select_by_mutual_information(
    dataset_clean.drop(columns=non_float_features),
    dataset_clean['OECD_RATING']
))
dataset_clean

,YEAR,ISO3_COUNTRY_CODE,OECD_RATING,GEO_REGION,ADMIN_REGION,LENDING_TYPE,INCOME_GROUP,GE.EST,NY.GDP.PCAP.CD,DT.DOD.DLXF.CD,...,FR.INR.RINR,NE.TRD.GNFS.ZS,SL.UEM.1524.ZS,BG.GSR.NFSV.GD.ZS,NV.SRV.TOTL.KD.ZG,NY.GDP.MKTP.KD.ZG,BX.KLT.DINV.WD.GD.ZS,NY.GNP.MKTP.KD.ZG,NE.GDI.TOTL.KD.ZG,NV.IND.TOTL.KD.ZG
COUNTRY_PERIOD_INDEX,,,,,,,,,,,,,,,,,,,,,
AFG-1999,1999,AFG,7,MEA,MNA,IDX,LIC,NaN,NaN,NaN,...,NaN,NaN,10.180,NaN,NaN,NaN,NaN,NaN,NaN,NaN
AFG-2000,2000,AFG,7,MEA,MNA,IDX,LIC,-2.173946,174.930991,NaN,...,NaN,NaN,10.203,NaN,NaN,NaN,0.004828,NaN,NaN,NaN
AFG-2008,2008,AFG,7,MEA,MNA,IDX,LIC,-1.527795,381.733238,1.994506e+09,...,12.557960,NaN,10.137,20.211726,14.854449,3.924984,0.455360,NaN,NaN,5.741818
AFG-2009,2009,AFG,7,MEA,MNA,IDX,LIC,-1.507752,452.053705,2.106109e+09,...,17.542929,NaN,10.056,20.562137,17.983382,21.390528,0.451889,NaN,NaN,6.107141
AFG-2010,2010,AFG,7,MEA,MNA,IDX,LIC,-1.478316,560.621505,1.975547e+09,...,11.364094,NaN,10.041,20.265308,18.355405,14.362441,1.203118,NaN,NaN,6.270601
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ZWE-2019,2019,ZWE,7,SSF,SSA,IDB,LMC,-1.310435,2184.329239,8.547578e+09,...,-76.631576,46.106544,11.718,4.533750,-3.744152,-6.332450,0.748473,-5.220787,-5.198220,-8.587237
ZWE-2020,2020,ZWE,7,SSF,SSA,IDB,LMC,-1.342368,2059.674454,8.691588e+09,...,-80.610262,40.178406,14.243,3.651449,-12.469129,-7.816951,0.470482,-9.914347,0.832007,-10.039817
ZWE-2021,2021,ZWE,7,SSF,SSA,IDB,LMC,-1.290561,2613.605421,8.951388e+09,...,-30.318195,44.114559,15.208,2.860813,6.864652,8.468017,0.575185,7.419142,31.286247,4.929101
ZWE-2022,2022,ZWE,7,SSF,SSA,IDB,LMC,-1.251224,2536.400502,8.793480e+09,...,-38.093651,55.067352,16.984,4.637325,6.625625,6.139263,0.826254,4.879442,-7.765343,4.755452
ZWE-2023,2023,ZWE,7,SSF,SSA,IDB,LMC,-1.170335,2195.224921,9.249294e+09,...,-68.877267,40.291261,15.332,5.675232,5.401212,5.350869,1.684321,10.203678,18.313137,3.242902

In [96]:
io.save_csv(dataset_clean, config.PROCESSED_DATA_DIR / 'preprocessed_dataset.csv', index=True)

# 3 - Preprocessing Transformation Pipeline

In [82]:
from sklearn.impute import KNNImputer
from sklearn.preprocessing import OneHotEncoder, LabelEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

In [84]:
X = dataset_clean.drop(columns=['OECD_RATING'])
y = dataset_clean[['OECD_RATING']]

In [91]:
categorical = X.columns[X.dtypes == 'object']
numerical = X.columns[X.dtypes != 'object']

numeric_processors = Pipeline(
    steps=[('KNNimputer', KNNImputer(n_neighbors=10, weights='distance', keep_empty_features=False))
            ]
)
categorical_processors = Pipeline(
    steps=[('onehotencoder', OneHotEncoder())]
)

X_transformer = ColumnTransformer(
    transformers=[
        ('numeric_processing', numeric_processors, numerical), 
        ('categorical_processing', categorical_processors, categorical)
    ]
)
# X_transformer.set_output(transform='pandas')

y_transformer = LabelEncoder()

In [92]:
X_transformer.fit(X)
X_transformed = X_transformer.transform(X)
X_transformed

<4204x258 sparse matrix of type '<class 'numpy.float64'>'
	with 230495 stored elements in Compressed Sparse Row format>

In [93]:
y_transformed = y_transformer.fit_transform(y)
y_transformed

/Users/hippolytegrandet/Desktop/Dev/country_risk_rating/.venv/lib/python3.9/site-packages/sklearn/preprocessing/_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

array([6, 6, 6, ..., 6, 6, 6])